<?php
$TEACHER_TABLE = array(
	array("学校电话", "01 41 24 41 40", "01 41 24 41 49 (传真)", "ecole@oushinet.com", "", ), 
	array("陈晓燕", "01 49 58 18 54", "06 03 44 75 96", "chenxiaoyan@oushinet.com", "1", ), 
	array("王伟珍", "01 41 24 41 40", "06 52 29 97 03", "ecole@oushinet.com", "2", ), 
	array("徐嘉蓉", "01 41 24 41 41", "06 28 63 80 01", "culture@oushinet.com", "3", ), 
	array("陈晓靓", "01 41 24 41 42", "06 42 61 74 12", "chenxiaojing@oushinet.com", "4", ), 
	array("孙琪", "01 46 64 78 90", "06 25 30 12 13", "sunqi@free.fr", "5", ), 
	array("柏晓群", "01 47 26 64 87", "06 52 29 88 65", "bai_xiaoqun@sina.com", "6", ), 
	array("刁冬梅", "09 83 08 14 67", "06 29 25 57 44", "dongmei_diao@yahoo.fr", "7", ), 
	array("李若梅", "01 71 56 93 32", "06 52 06 33 13", "lrmm123@163.com", "8", ), 
	array("郭瑾", "", "06 88 70 15 93", "winsta3@hotmail.com", "9", ), 
	array("汪丹", "", "07 68 08 00 06", "wangdan@hotmail.fr", "10", ), 
	array("潘净", "01 46 78 23 29", "06 38 49 88 60", "scally190011@163.com", "11", ), 
	array("朱同贞", " ", " 06 34 24 98 51", " zhu.tongzhen@gmail.com", "12", ), 
	array("徐晓玲", " ", "06 62 47 00 78", "nbc8@msn.com", "13", ), 
	array("张莉莉", "01 48 99 18 53", "06 32 50 91 34", "zhangliliane@hotmail.com", "14", ), 
	array("王莹", " ", "07 82 89 76 96", "wangying11628@gmail.com", "17", ), 
	array("徐艳", " 09 53 01 02 65", "06 02 30 27 74", "yan77.su@gmail.com", "18", ), 
	array("刘海", "", "06 98 99 68 84", "liuhaisilentsea@gmail.com", "19", ), 
	array("潘瑾", "", "06 49 84 41 08", "pan.jin.chineseteacher@gmail.com", "20", ) 
);

?>

