<?php

$JY_ADULTE = array(
	"成人",
array("school/adulte.jpg",	 "成人中文课",	 "成人中文课",	 "JY_ADULTE"),
array("汉语学习在法国持续升温，除了青少年外，越来越多的成年人也投入到学习汉语的热潮中。成人汉语班即是针对希望学习汉语的成年人而开办的。", "成人汉语班根据学生的汉语程度分为不同班级。在教学过程中借助现代教学手段，注重听说读写结合，并将通过HSK考试融入教学计划，帮助学生对自己阶段性的学习进行统一评定。", "", "", ""),
array(
	array("上课时间 ", "",
		array("6", "10H30-12H30 (N4)； 13H30-15H30 (N5)    "),
		array("7", "10H30-12H30 (N1 初级) ；13H30-15H30 (N2) ；15H45-17H45 (N3)  "),
	),
	array("报名表", "registerref=adulte"),
),
array(" ",
array("school/huiha.jpg",	 "汉语会话角",	 "汉语会话角",	 ""),
array("为了提高语言学习者的口语表达能力，欧洲时报孔子课堂不定期举办双语角活动，为学习汉语或法语的有关人士提供了一个交流和练习的平台。每次活动的主题广泛取材于《汉语900句》、《汉语301句》以及《体验汉语》等教材。同时，双语角以中国文化为切入点，紧扣时事，并结合欧洲时报文化中心的相关展览或讲座，组织大家进行有目的的学习和研讨。", "", "", ""),
array(
	array("上课时间 ", "",
		array("5", "14H30-16H30"),
	),
),
),
// francais 
array(
	"Cours de chinois pour adultes",
array("school/adulte.jpg",	 "adultes",	 "adultes",	 "JY_ADULTE"),
array("L'enseignement du chinois mandarin ne cesse de prendre de l'ampleur. En dehors des enfants et des adolescents, de plus en plus d'adultes se lancent dans l'apprentissage de cette langue, c'est pourquoi nous avons ouvert des cours de chinois pour adultes.", "Les cours pour adultes sont divisés en différent niveaux. Les cours empruntent des méthodes d'enseignement modernes, et accordent une importance à l'apprentissage simultanée de la compréhension et à l'expression écrites et orales. Le programme comprend également l'épreuve du HSK qui permet à chacun des apprenants d'évaluer les progrès accomplis.", "", ""),
array(
	array("Horaires", "",
		array("Samedi", "10H30-12H30 (N4)； 13H30-15H30 (N5)    "),
		array("Dimanche", "10H30-12H30 (N1 débutant) ；13H30-15H30 (N2) ；15H45-17H45 (N3)  "),
	),
	array("Inscription", "/french/register/?registerref=adulte"),
),
array(" ",
array("school/huiha.jpg",	 "Cours de conversation",	 "Cours de conversation",	 ""),
array("Le cours de conversation constitue une plateforme d’échanges où se rencontrent des Français et des Chinois pour faire des exercices oraux. Ceux qui apprennent le chinois et ceux qui apprennent le français échangent leurs idées dans la langue voulue sous la direction d’un enseignant qui choisit le thème, soit dans le manuel, soit autour d’une exposition ou d’une conférence du centre culturel.", "", "", ""),
array(
	array("Horaires ", "",
		array("Vendredi", "14H30-16H30"),
	),
),
),
),
1 // new version with franch
);
?>