<?php

$JY_CONCOURS = array(
	"中华文化大赛",
array("school/wenhuaconcours.jpg",	 "中华文化大赛",	 "中华文化大赛",	 "JY_CONCOURS"),
array("为进一步激发海外华裔青少年学习汉语和中华文化兴趣，提升效应，扩大影响，同时亦为满足海外华文学校师生需求，中国海外交流协会在总结以往三届知识竞赛经验的基础上，将“海外华裔青少年中华文化知识竞赛”改为“海外华裔青少年中华文化大赛”。", "大赛分为海外预赛和国内决赛两个环节，知识竞赛、演讲比赛和中华才艺比赛三项。知识竞赛的内容主要出自三常教材（《中国文化常识》、《中国历史常识》和《中国地理常识》），知识竞赛成绩169（满分260分）以上的考生，才能具备参考演讲和才艺比赛资格。每国演讲比赛和才艺比赛的前5名将受邀回国参加决赛。", "", "", ""),
array(
	array("", "",
	),
	array("报名表", "/files/baoming5.pdf"),
),
// francais 
array(
	"Concours sur les connaissances de la civilisation chinoise",
array("school/wenhuaconcours.jpg",	 "concours de la culture chinois",	 "concours de la culture chinois",	 "JY_CONCOURS"),
array("En 2012, après la réussite des trois expériences précédentes, l’AEOMC (Association des Échanges d’outre-mer de Chine) ", "a changé le nom de son 4e Concours international sur les connaissances de la civilisation chinoise en ", "«Grand Concours culturel pour les Jeunes et Adolescents des Chinois d’outre-mer». ", "La première étape du concours commence dans les pays où vivent les candidats, ", "sous forme de questions-réponses autour des trois manuels principaux sur la civilisation chinoise, ", "à savoir : «Connaissances générales en culture chinoise», «Connaissances générales en histoire chinoise» et ", "«Connaissances générales en géographie chinoise». ", "Tous ceux qui ont eu des notes supérieures à 169/260 participent alors à la compétition suivante sur l’éloquence et ", "l’art classique chinois. Les cinq premiers de chaque pays seront invités par l’AEOMC aux compétitions finales en Chine.", "", "", ""),
array(
	array("", "",
	),
	array("Inscription", "/files/baoming5.pdf"),
),
),
1 // new version with franch
);
?>