<?php

$JY_CHILDREN = array(
	"幼儿",
array("school/children1.jpg",	 "幼儿中文课",	 "幼儿中文课",	 "JY_CHILDREN"),
array("幼儿汉语班以培养学龄前儿童对中文学习的兴趣为目的，分为唱游班和识字班。除了使用《快乐华语》、《汉语乐园》和《中文真有趣》等主要教材外，还针对幼儿的学习特点，采用儿歌、动画、游戏等多种手段，寓教于乐，让孩子们在玩乐中体会中文的奥妙。", "", "", ""),
array(
	$T_C_C,
	array("报名表", "registerref=children"),
),
// francais 
array(
	"Cours de chinois préscolaire",
array("school/children1.jpg",	 "préscolaire",	 "préscolaire",	 "JY_CHILDREN"),
array("Le cours de chinois préscolaire est destiné aux élèves de 5 ou 6 ans dans le but de susciter leur intérêt pour apprendre une langue réputée difficile. À l’aide de jeux, de chansons, de vers classiques, ou de dessins animés, l’enseignant mobilise tous les atouts accessibles aux enfants pour les initier à la langue. Les manuels «My First Chinese Words», «Paradis du Chinois» et «Magical Chinese» ont été adaptés aux enfants français pour être mieux assimilés.", "", "", ""),
array(
	$T_C_C_F,
	array("Inscription", "registerref=chinois"),
),
),
1 // new version with franch
);
?>