<?php

$JY_PIANO = array(
	"钢琴",
array("school/piano.jpg",	 "钢琴课",	 "钢琴课",	 "JY_PIANO"),
array("钢琴课采用一对一教学。教师在教学中注重丰富学生的生活，陶冶情操，开阔视野，使学生身心愉悦健康。最重要的是，通过钢琴学习，使学生了解构成音乐的基本要素，懂得理解和表现音乐的规律，从而全面提高音乐素养和文化艺术修养。", ""),
array(
	$T_GQ,
	array("报名表", "../register/?registerref=piano"),
),
// francais 
array(
	"Cours de piano",
array("school/piano.jpg",	 "Piano",	 "Piano",	 "JY_PIANO"),
array("Le cours de piano est individuel avec des professeurs diplômés en musique. Le cours est en fonction de chaque profil, met à la disposition des méthodes et outils pour permettre d'atteindre l'objectif de chaque enfant. Par l'apprentissage du piano, les élèves comprennent les éléments de base de la musique, expriment leurs sentiments et améliorent leur qualité culturelle et artistique.  Apprendre à jouer du piano favorise le développement personnel et apporte de nombreux bienfaits.", ""),
array(
	array("Horaires", "",
		array("Mercredi", "en journée"),
		array("Samedi", "en journée"),
		array("Dimanche", "en journée"),
	),
	array("Inscription", "/french/register/?registerref=piano"),
),
),
1 // new version with franch
);
?>