<?php

$JY_SHUHUA = array(
	"书画",
array("school/shufa2.jpg;school/shufa.jpg",	 "书画课",	 "书画课",	 "JY_SHUHUA"),
array("中国书法和绘画经过几千年的历史基奠，已经成为中国的国粹。练习书画不仅能陶冶人的情操，培养高雅的业余爱好和文明的风度，还能给人以愉悦，激发人的感情，宁神健魄。教学中，教师注重因材施教，针对个人的水平和特色做个性化的辅导。", "", "执教老师：王小军（中国美术学院毕业）", "执教老师：马剑虹（法国书画家协会会长）", ""),
array(
	$T_SH,
	array("报名表", "../register/?registerref=shuhua"),
),
// francais 
array(
	"Cours de calligraphie et de peinture chinoise",
array("school/shufa.jpg",	 "calligraphie et peinture",	 "calligraphie et peinture",	 "JY_SHUHUA"),
array("La calligraphie et la peinture chinoises ont une histoire commune vieille de milliers d'années, et représentent la quintessence profonde de la Chine. Pratiquer l’art de la calligraphie c’est non seulement se cultiver, mais c’est aussi le plaisir d'acquérir de l'élégance et la paix de l’âme. L'enseignement est très personnalisé.", "", "Professeur: WANG Xiaojun (Diplômé de l’Ecole des Beaux-Arts de Chine)", "Professeur: MA Jianhong (président de l’association le Pinceau d’or)", "", ""),
array(
	$T_SH_F,
	array("Inscription", "/french/register/?registerref=shuhua"),
),
),
1 // new version with franch
);
?>