<?php

$JY_WUDAO = array(
	"舞蹈",
array("school/chaiyipeixun.jpg",	 "少儿健美舞课",	 "少儿健美舞课",	 "JY_WUDAO"),
array("少儿舞蹈训练，在教学上用童心追求童趣，不仅培养学生健美的体魄，发展其灵活性，柔韧性和协调性。而且在潜移默化中培养美的情操，引导学生对舞蹈表现形式和情感内涵的整体把握。", ""),
array(
	$T_WD,
	array("报名表", "../register/?registerref=dance"),
),
// francais 
array(
	"Cours d’aérobic pour enfants",
array("school/chaiyipeixun.jpg",	 "aérobic pour enfants",	 "aérobic pour enfants",	 "JY_WUDAO"),
array("Dans le but de favoriser chez les enfants une bonne constitution physique qui allie tonus, coordination et souplesse, nous avons cherché à nous appuyer sur leur spontanéité pour leur enseigner la danse, qui leur permette de développer sensibilité et émotion artistiques.", ""),
array(
	$T_WD_F,
	array("Inscription", "/french/register/?registerref=dance"),
),
),
1 // new version with franch
);
?>