<?php

$JY_WUSHU = array(
	"武术",
array("school/wushu.jpg",	 "少儿武术课",	 "少儿武术课",	 "JY_WUSHU"),
array("武术是中国传统的体育项目，更是中国人民在长期的社会实践中不断积累和丰富起来的运动形式。武术注重内外兼修，是一项宝贵的文化遗产，也是中国传统文化的重要组成部分。练习武术除能强身健体、锻炼意志外﹐还能培养机智勇敢﹑坚韧不屈等优良性格。", "", ""),
array(
	$T_WS,
	array("报名表", "../register/?registerref=wushu"),
),
// francais 
array(
	"Cours de Kungfu pour enfants",
array("school/wushu.jpg",	 "kungfu",	 "kungfu",	 "JY_WUSHU"),
array("L'art martial (Wushu en chinois) est un sport traditionnel chinois, qui a été développé en Chine au fil des siècles. Wushu est un patrimoine culturel précieux. La pratique de Wushu sert non seulement à renforcer la forme physique, mais aussi à cultiver et développer des caractères importants, comme la discipline, la preuve de volonté et de courage.", "", ""),
array(
	$T_WS_F,
),
),
1 // new version with franch
);
?>