<?php

$JY_YOUTH = array(
	"青少年",
array("jiaoyu_450.jpg",	 "青少年中文课",	 "青少年中文课",	 "JY_YOUTH"),
array("青少年汉语班面对七岁以上的青少年学生，主要使用《汉语》和《中文》两套教材，并根据班级水平及学生特色，辅以《跟我学汉语》、《快乐汉语》、《长城汉语》、《声典》等多种汉办指定教材，丰富教学内容。拥有《汉语》从拼音开始至十一册的班，以及《中文》九册班。教师认真负责，教室配备多媒体教学设备，教学手段多样化，教学质量高。", ""),
array(
	array("上课时间 ", "",
		array("星期三", "14H—17H15"),
		array("星期六", "10H30—17H45"),
		array("星期日", "10H30—17H45"),
	),
	array("报名表", "../register/?registerref=chinois"),
),
// francais 
array(
	"Cours de chinois pour enfants et adolescents",
array("jiaoyu_450.jpg",	 "enfants et adolescents",	 "enfants et adolescents",	 "JY_YOUTH"),
array("Les cours de chinois pour enfants et adolescents à partir de 7 ans occupent une place prépondérante dans les activités culturelles de l’association. Les manuels utilisés sont en principe «HAN YU» et «ZHONG WEN», avec en complément «Apprends le chinois avec moi», «Kuaile hanyu», «Great Wall Chinese», «Soundic» selon le niveau des classes qui va de Pinyin jusqu’au niveau 11. La compétence des professeurs expérimentés, les installations multimédias, la variété des moyens pédagogiques garantissent de bons résultats à la plupart des élèves.", ""),
array(
	array("Horaires", "",
		array("Mercredi", "14H—17H15"),
		array("Samedi", "10H30—17H45"),
		array("Dimanche", "10H30—17H45"),
	),
	array("Inscription", "registerref=chinois"),
),
),
1 // new version with franch
);
?>