<?php

// 成人法文课 
$T_A_F	= array("Jeudi:10H00-12H00");
	

// 成人中文课
$T_A_C = array("Samedi:10H30—12H30 (N4)", "Samedi: 13H30-15H30 (N5)", "Dimanche: 10H30-12H30 (N1)",  "Dimanche: 13H30-15H30  (N2)",  "Dimanche: 15H45-17H45  (N3)");


// 汉法双语会话角" 
$T_A_H = array("Vendredi:14H30-16H30");

//幼儿中文课,
$T_C_C = array("Dimanche：10H30—11H30（5ans）", "Dimanche：11H40—12H40（6 ans）");				 

// 形体塑身" 
$T_XT = array("Mercredi:15H30-17H30");

// 瑜伽 
$T_YJ = array("Samedi:10H30-12H00", "Samedi:13H30-15H00", "Samedi:15H15-16H45");

//木兰拳 
$T_ML = array("Vendredi:14H30-16H00");

// 气功课 
$T_QG = array("Vendredi:12H30-13H30");

// 太极
$T_TJ = array("Dimanche：10H30-12H00");

// 徒步健身俱乐部 
$T_TB = array("12 avril, Samedi: 14:30-17:30");

$T_SL =	array("Samedi:15H30-17H30");

// 健身舞 
$T_JS = array("Jeudi:14H30-16H30");

$T_GD = array("Dimanche 10H30-12H30");

// 合唱团 
$T_HC =	array("Dimanche:14H00-18H00");

// 古琴课
$T_GUQ = array("Mercredi 13:20-14:20","Mercredi 14:25-15:25","Mercredi 15:35-16:35","Mercredi 16:40-17:40");

// 电脑初级班 
$T_DL1 = array("Dimanche:10H30-13H00");

// 电脑高级班 
$T_DL2 = array("Dimanche:14H00-16H00");

// 网络销售速成班 
$T_WL = array("Samedi:14H30-16H30");

// 书画班  
$T_SH =	array("Mercredi 15H45—17H15",  "Dimanche 10H30—12H30");
// 书画班  
$T_CSH =	array("Samedi 14H00—15H30", "Samedi 15H45—17H15");

// 钢琴课 
$T_GQ = array("Mercredi", "Samedi", "Dimanche");

// 少儿健身舞班 
$T_WD = array("Mercredi:14H00—15H30", "Mercredi:15H45—17H15");

// 少儿武术课 
$T_WS = array("Samedi:14H00—15H30", "Samedi:15H45—17H15");

// 少儿武术课 
$T_FS = array("Samedi:11H00—12H30");

$T_YCT = 		array("Dimanche : 10H30-12H30");
$T_CONCOURS = 	array("Dimanche : 10H30-12H30");

// 暑期班
$T_SQ = 		array("Lundi-Samedi:14h00-15h30 et 15h45-17h15");

//暑期少儿武术班
$T_SQWS = 		array("Lundi-Vendredi:14h00-17h15");

//"冬季大乐园"
$T_DLY = array("Paris:26 Dec-2 Jan");
$T_DLY_P = array("100 € /P");

//"夏令营"
$T_ETE =	array("Beijing:7 Juillet-2 Août", 	"Beijing-Mongolie:7 Juillet-2 Août");
$T_ETE_P = 	array("2100 € /P （visa non inclus）", "2300 € /P （visa non inclus）");


//拼音班(7岁起）, 
$T_CC0 = array(
	"Samedi:10:30-12:30",
	"Mercredi/Samedi 14:00—15:30", 
	"Mercredi/Dimanche 15:45-17:15", 
);
// "汉语一册"
$T_HY1 = array(
	"Samedi 10:30-12:30", 
	"Dimanche 10:30-12:30", 
	"Mercredi/Samedi 15:45-17:15", 
	"Mercredi/Dimanche 14:00-15:30"
);
//"汉语二册", 	
$T_HY2 = array(
	"Samedi 10:30-12:30", 
	//"Dimanche 10:30-12:30", 
	"Mercredi/Samedi 15:45-17:15",
	"Mercredi/Dimanche 14:00-15:30"
);

$T_HY3 = array(
	"Samedi 10:30-12:30",
	"Dimanche 10:30-12:30",
		"Mercredi/Samedi 14:00-15:30",
		"Mercredi/Dimanche 15:45-17:15",
);

$T_HY4 = array(
	"Samedi 10:30-12:30", 
	"Mercredi/Samedi 14:00-15:30", 
	"Mercredi/Samedi 15:15-17:15", 
);

$T_HY5 = array(
	"Samedi 15:40-17:40", 
	"Dimanche:13:30-15:30",
	"Mercredi/Samedi 15:45-17:15",
);
$T_HY6 = array(
	"Samedi 13:30-15:30",
	"Mercredi/Samedi 14:00-15:30",
);
$T_HY7 = array(
	"Dimanche 13:30-15:30"
);
$T_HY8 = array(
		"Samedi 13:30-15:30",
		"Dimanche 10:30-12:30",
		"Dimanche 15:40-17:40",
);
$T_HY10 = array(
	"Samedi 13:30-15:30", 

);
$T_HY12 = array("Samedi 15:40-17:40");
$T_ZW10 = array("Samedi 15:40-17:40");
$T_LV12 = array("Dimanche 10:30-12:30");
$T_LV23 = array("Dimanche 13:30-15:30");



?>
