<?php

$FETE_TAB = array(
		//array(11, 11, $FIRST_WAR, "FIRST_WAR"),
		array(11, 3, 4, $TOUSSAINT, "TOUSSAINT"),
		//array(12, 5, $EXAMEN_YCT, "EXAMEN_YCT"),
		//array(12, 6, $EXAMEN_HSK, "EXAMEN_HSK"),
		array(12, 26, 29,30, $NOEL, "NOEL"),
		//	array(12, 24, 27, 28, 31, $DLY, "DLY"),
//	array(1, 3, 4, $DLY, "DLY"),
		array(1, 2, $NOUVEL_AN, "NOUVEL_AN"),
		array(1, 26,27, $FETE_PRINTEMPS, "FETE_PRINTEMPS"),
		array(3, 23, 24, $EXAMEN_YCT, "EXAMEN_YCT"),
		array(3, 19, $EXAMEN_HSK, "EXAMEN_HSK"),
		array(4, 20,21,24, $BAQUES, "BAQUES"),
		//array(4, 30, $FETE_TRAVAIL, "FETE_TRAVAIL"),
		array(5, 1, $FETE_TRAVAIL, "FETE_TRAVAIL"),
		//array(5, 6,7, $FETE_MAI8, "FETE_MAI8"),
		array(6,8, 9, $PENTECOTE, "PENTECOTE"),
);

$NOTE_TAB = array(
		array(12, 1, 2, "二次班考试", "examin2"),
		array(1, 19, 20, "一次班考试", "examin1"),
		array(3, 2, 3, "二次班考试", "examin2"),
		array(6, 1, 2, "期终考试", "examin"),
);

/* change these values for schedule table */
$START_M = 9;
$END_M = 6;
$START_DAY = 15; // first day should be modified each year
$END_DAY = 31;
$START_WEEK = 6;
$M2_DAY = 28; 	// this year 29 day


$START_DAY1 = 12;
$START_DAY2 = 30;


$PROGRAM_JPG = "2018-2019-programm.jpg";
$PROGRAM_PDF = "2018-2019programm.pdf";

$PROGRAM_JPG2 = "Programme-2018.jpg";
$PROGRAM_PDF2 = "Programme-2018.pdf";

?>

