<?php
 $JY_NEWS11 = array(
"Félicitation à nos élèves",
"14e Concours International de Rédaction en Chinois pour les jeunes ",
"",
"29 avril 2014",
array(
),
array(
"Félicitations à nos élèves qui ont été lauréats du 14è Concours International de Rédaction en Chinois pour les jeunes", 
"&nbsp;&nbsp;&nbsp;<b>Premier Prix ：</b> WANG Ying de «Ma famille», CHEN Jialing de «Ma ville natale et ma famille»", 
"<IMG SRC='".$PHOTO_PATH."wenyunews/huojiang.jpg' width=500>", 
"<IMG SRC='".$PHOTO_PATH."wenyunews/huojiang1.jpg' width=500>", 
"&nbsp;&nbsp;&nbsp;<b>Seconde Prix ：</b> CHEN Jianjie de «Ma tante», CHEN Pinzhen «Ma famille»", 
"&nbsp;&nbsp;&nbsp;<b>Troisième Prix ：</b>LUOMING Qiantian «Ma ville natale», LIANG Zhaoxuan «Ma famille»,", 
"<span class=spanarticle>XU Yalin «Ma famille»,  LIN Jiating «Ma famille»</span>", 
"<div class=note_title><h1>Félicitation à tous ces lauréats encore une fois!</h1></div>", 
"
", "")
);
?>