<?php 

$JY_NEWS3 = array("Les résultats de l’examen du YCT de novembre 2013 sont sortis", 
	"Les résultats de l’examen du YCT de novembre 2013 sont sortis ","","Le 28 décembre 2013",
	array(), 
	array(
"Les résultats du YCT du 16 novembre 2013 sont sortis. Les étudiants peuvent s’en enquérir sur le site <a href='http://www.chinesetest.cn' target=_blank>http://www.chinesetest.cn</a> 
avec leur numéro d’examen, leur nom et le code de vérification.",
"<IMG SRC='".$PHOTO_PATH."YCTSite.jpg' width=500>",
"193 étudiants au total ont participé à cet examen, 95% l’ont réussi et plus d’un tiers ont eu 200/200. Les 151 étudiants de la Classe Confucius de Nouvelles d’Europe l’ont réussi, mis à part 2 personnes au niveau IV. ",
"Félicitations à tous et bonne continuation à tout le monde !"

	), 

);

?>