<?php
 $JY_NEWS13 = array(
"La rentrée arrive",
"Ça y est, les vacances sont terminées, nous sommes prêts pour la rentrée. Préparez vos affaires de chinois et les devoirs des vacances pour le premier cours.",
"",
"le 6 septembre 2014",
array(
),
array("  Ça y est, les vacances sont terminées, nous sommes prêts pour la rentrée. Préparez vos affaires de chinois et les devoirs des vacances pour le premier cours.", "", "  Les parents doivent se présenter au premier cours de la rentrée.", "", "A noter les dates de la rentrée :", "Cours de mercredi/samedi	le 13 septembre 2014", "Cours de mercredi/dimanche	le 14 septembre 2014", "Cours de mercredi		le 17 septembre 2014", ""),
);
?>