<?php
 $JY_NEWS10 = array(
"Inscriptions pour l’année scolaire 2014-2015 ",
"Cours de chinois pour tous les niveaux ",
"",
"11 avril 2014",
array(
),
array(
"Parmi les pionnières dans l’initiation au mandarin destinée à la jeune génération des ressortissants chinois à Paris, l’école de chinois de «Nouvelles d’Europe» a su acquérir depuis sa création une bonne réputation grâce aux résultats de ses élèves. Les inscriptions pour l'année scolaire 2014-2015 peuvent se faire dès à présent ; les parents d'élèves sont donc invités à inscrire leurs enfants aux différents cours. ",
"", 
"<b>I.	Cours de Pinyin </b>
", "<IMG src='".$PHOTO_PATH."school/newclasse800x500.jpg' width=500>
", "Le Pinyin : il s’agit de la transcription phonétique du chinois en alphabet latin, apprendre les 4 tons pour parler chinois avec le bon accent en évitant les malentendus.",
"<b>Niveau ：</b> Débutant", 
"<b>Âge : </b> Enfant à partir de 7 ans
", "<b>Horaires ：</b>
", "<b>1. Classe du dimanche : </b> dimanche  10:30—12:30
", "<b>2. Classe du mercredi et samedi ;</b>  mercredi 14:00—15:30，samedi 13:30—15:00
", "<b>3. Classe du mercredi et dimanche : </b>  mercredi 15:45—17:15，dimanche 15:15—16:45
", "
", "<b>II.	Cours de chinois pour tous les niveaux </b>
", "<IMG src='".$PHOTO_PATH."school/classediver800x500.jpg' width=500>
", "L'École chinoise du journal «Nouvelles d’Europe» propose des classes avec plusieurs niveaux différents. Le support des cours sont les livres « Hanyu » volumes 1 à 12. Les élèves de l’extérieur devront  passer un test pour être répartis dans les classes adaptées à leur niveau. ", 
"<b>Horaire ： </b> mercredi après-midi, samedi, dimanche
", "
", "<b>III.	Cours divers</b>
", "En dehors des cours de chinois, les cours de piano, de danse folklorique, de Kung-fu, de calligraphie et de peinture classique chinoise attirent chaque année de nouveaux adhérents.", 
"<b>Classe et horaire ：</b>
", "<b>Cours préscolaire （enfant de 6 ans）： </b>	samedi 14:00-15:00
", "<b>Cours préscolaire （enfant de 4-5 ans）： </b> samedi 15:15-16:15   
", "<b>Kung-fu ： </b>   mercredi 14:00-15:30    15:45-17:15
", "<b>Danse folklorique ： </b> mercredi 14:00-15:30    15:45-17:15
", "<b>Calligraphie et peinture ：</b>	 mercredi 14:00-15:30    15:45-17:15
", "<b>Piano ： </b>	  cours individuel，mercredi, samedi, dimanche
", "<b>Contacts ：</b> 01 41 24 41 40 （Mme Wang） ou 01 41 24 41 44 （Mme Chen）
", "
", "
", "
", "
", "")
);
?>