<?php
 $JY_NEWS18 = array(
"Nouvelle classe de calligraphie chinoise",
"Le nouveau cours de calligraphie chinoise se fait avec soit pinceau, soit stylo plume ou stylo.",
"",
"Le 22 octobre 2014",
array(
),
array(	"<IMG src='".$PHOTO_PATH."jiaoyunews/caligraphie.jpg' width=500>",
	"Le nouveau cours de calligraphie chinoise se fait avec plusieurs styles, chaque élève peut la pratiquer soit au pinceau, soit au stylo plume ou au stylo.",
	"",
	"Date：du mi-novembre 2014 – mi-juin 2015",
	"Horaire：Samedi 13H30 – 15H30",
	"Professeur：peintre célèbre Monsieur Ma Jianhong",
	"Contact：01 41 24 41 42",
	""),
);
?>