<?php
 $JY_NEWS21 = array(
"L’ouverture de la Ruche Culturelle Chinoise",
"L’ouverture de la Ruche Culturelle Chinoise",
"",
"28 déc 2014",
array(
),
array(	"Le stage de la Ruche Culturelle Chinoise 2014 de Paris est organisé par le bureau des affaires des Chinois d’outre-mer, assisté par le bureau des affaires des Chinois d’outre-mer de la province du Shandong et L’Association des Amis de Nouvelles d’Europe.",
	"<IMG src='".$PHOTO_PATH."jiaoyunews/ouverture 1.jpg' width=500>",
	"Ce stage a lieu à Paris du 27 décembre 2014 au 3 janvier 2015 à L’Association des Amis de Nouvelles d’Europe à Gentilly. Ce programme a donné aux jeunes une opportunité de connaître la culture traditionnelle chinoise.",
	"<IMG src='".$PHOTO_PATH."jiaoyunews/ouverture 2.jpg' width=500>",
	"Les 8 enseignants de niveau supérieur sélectionnés par le bureau des affaires des Chinois d’outre-mer de la province du Shandong vont donner une dizaine de cours, riches de contenus diversifiés, comme la civilisation chinoise, le Kung-fu, la danse et la musique traditionnelles chinoises, la peinture et la calligraphie chinoises et les arts artisanaux(papier découpé, masque d'opéra et pâte à modeler), qui sont destinés aux jeunes ressortissants chinois mais aussi les jeunes Français qui s'intéressent à la culture chinoise.",
	"<IMG src='".$PHOTO_PATH."jiaoyunews/20141229094650365.jpg' width=500>",
	""),
);
?>