<?php
 $JY_NEWS15 = array(
"Le cours de chinois pour adultes",
"Plus en plus de français s’intéressent à la culture chinoise, et plus en plus de gens commencent d'apprendre le chinois ",
"",
"le 16 septembre 2014",
array(
),
array(	"<IMG src='".$PHOTO_PATH."jiaoyunews/cours de chinois2.JPG' width=500>",
	"De plus en plus de Français s’intéressent à la culture chinoise, et de plus en plus de gens commencent à apprendre le chinois. Selon votre niveau, 3 types de cours sont proposés.",
	"",
	"Samedi：",
	"10H30—12H30 : Intermédiaire",
	"13H30—15H30 : Débutant",
	"",
	"Dimanche:",
	"10H30—12H30 : Avancé",
	"",
	"Du 20/09/2014 au 28/06/2015",
	"",
	"Contact:06 49 84 41 08 (Mme PAN)/01 41 24 41 41 (Mme XU)",
	"",
	"Un cours d'essai gratuit, à saisir.",
	""),
);
?>