<?php
 $JY_NEWS2 = array(
 "L’école de chinois et la Classe Confucius de Nouvelles d’Europe déménagent à Gentilly", 
 "L’école de chinois et la Classe Confucius de Nouvelles d’Europe déménagent à Gentilly", "", "Le 10 décembre 2013",
array(), 
array(
"Les Amis de Nouvelles d’Europe (Association, école de chinois et Classe Confucius) s’installent au 48-50 rue Benoît-Malon à Gentilly à partir de décembre 2013.",
"<IMG SRC='".$PHOTO_PATH."school/school.jpg' width=500>",
"Le nouveau local est situé au sud de Paris, tout à côté de la Cité Universitaire. Ce nouveau, beau et grand édifice est caractéristique de l’architecture traditionnelle française tout en respectant la conception chinoise d’équilibre entre l’homme et la nature. Toutes les infrastructures sont conçues pour la convenance et la sécurité des élèves. ",
"<IMG SRC='".$PHOTO_PATH."school/school2.jpg' width=500>",
"Les équipements multimédias sont installés dans de lumineuses salles de formation. ",
"<IMG SRC='".$PHOTO_PATH."school/danceroom.jpg' width=500>",
"Le mur de miroirs et le parquet en bambou nous permettent de suivre plus facilement les cours de danse ou d’arts martiaux.",
"<IMG SRC='".$PHOTO_PATH."school/childrenroom.jpg' width=500>",
"Les poufs aux couleurs vives ont été choisis particulièrement pour les enfants d’âge préscolaire.  ",
"<IMG SRC='".$PHOTO_PATH."school/pianoroom.jpg' width=500>",
"Le nouveau site dispose également d’une salle de piano, d’une salle informatique, d’une salle de calligraphie et peinture, et d’une bibliothèque."
)

 
);
?>