<?php
 $JY_NEWS12 = array(
"Inscriptions des cours de chinois pour adultes",
"Les inscriptions pour l'année scolaire 2014-2015 peuvent se faire dès à présent",
"",
"31 mai 2014",
array(
),
array(
"<IMG src='".$PHOTO_PATH."school/adulte.jpg' width=500>", 
"Pour répondre aux besoins des adultes, nous avons mis en place depuis quelques années des cours pour ceux qui souhaitent acquérir certaines connaissances sur la langue chinoise. Le manuel principal est «Le chinois contemporain», avec en complément «Great Wall Chinese», tous les deux édités par Hanban. Les élèves sont répartis dans deux classes selon leur niveau. Étant donné la faible disponibilité des élèves après les cours, nous sélectionnons les textes et nous consacrons plus de temps aux exercices en classe.",
"Les inscriptions pour l'année scolaire 2014-2015 peuvent se faire dès à présent. Les élèves devront  passer un test pour être répartis dans les classes adaptées à leur niveau, sauf pour les débutants.", 
"Horaire：", "<IMG src='".$PHOTO_PATH."wenyunews/coursadultes600.jpg' width=500>", "", "")
);
?>