<?php
 $JY_NEWS8 = array(
"Nouveaux cours de calligraphie et de peinture le mercredi",
"Par professeur Ma Jianhong ",
"",
"1 mars 2014",
array(
),
array(
"Organisée en juin 2013, l’exposition des œuvres réalisées par les étudiants de la classe de peinture de l’Association des Amis de Nouvelles d’Europe a remporté un grand succès. Sous la direction de l’enseignant Ma Jianhong, Président de l'Association le Pinceau d’Or, les étudiants ont beaucoup progressé. ", 
"<IMG src='".$PHOTO_PATH."school/shufa-600.jpg' width=500>", 
"A la suite de la demande des élèves et des parents, nous avons décidé d’ajouter deux cours le mercredi à partir du mois de mars. ", 
"La calligraphie et la peinture chinoises ont une histoire commune vieille de milliers d'années, et représentent la quintessence profonde de la Chine. Pratiquer l’art de la calligraphie c’est non seulement se cultiver, mais c’est aussi le plaisir d'acquérir de l'élégance et la paix de l’âme. L'enseignement est très personnalisé. ",
"Le cours de calligraphie et de peinture va durer trois mois, du 19 mars 2014 au 18 juin 2014. ",
"<b>Horaires: </b> Mercredi 14h00 - 15h30 ; 15h45 - 16h15",
"<b>Contacts : </b> 01 41 24 41 42 (Madame CHEN) ou 01 41 24 41 40 (Madame WANG)",
"")
);
?>