<?php
 $JY_NEWS19 = array(
"Le stage de la Ruche Culturelle Chinoise 2014 à Paris",
" Ce programme a donné aux jeunes chinois d'outre-mer une opportunité de connaître la culture",
"",
"22-10-2014",
array(
),
array(	"<IMG src='".$PHOTO_PATH."jiaoyunews/dlydly-fr.JPG' width=500>",
	"Le stage de la Ruche Culturelle Chinoise 2014 sera lancé à Paris pour une activité de promotion de la culture chinoise, organisée par le bureau des affaires des ressortissants chinois de la province du Shandong. Ce programme a donné aux jeunes chinois d'outre-mer une opportunité de connaître la culture traditionnelle chinoise.",
	"L'activité va durer une semaine et en proposant une dizaine de cours, comme la civilisation chinoise, le Kung-fu, la danse et la musique traditionnelles chinoises, la peinture et la calligraphie chinoises et les arts artisanaux(papier découpé, masque d'opéra et pâte à modeler), qui sont destinés aux jeunes ressortissants chinois. Les Français qui s'intéressent à la culture chinoise peuvent également s'inscrire aux cours. ",
	"",
	"Date d'activité:",
	"Du 27/12/2014 - 03/01/2015 de 14h00 à 17h40",
	"Lieu d'activité: ",
	"L’Association des Amis de Nouvelles d’Europe",
	"48-50 Rue Benoît Malon，94250 Gentilly",
	"",
	"Frais d'inscription : 100 Euros",
	"",
	"L’inscription sera auprès de l’Association des Amis de Nouvelles d’Europe.",
	"Contact : 06 25 30 12 13 Mme Sun / 01 41 24 41 40 Mme Wang",
	"Email : sunqi26@gmail.com",
	"Site web : www.culture-oushi.com",
	"La cérémonie d'ouverture aura lieu le 27 décembre 2014.",
	"<A href='../files/2014中华文化大乐园巴黎营报名表格.pdf'>fiche d'inscription à télécharger</A>",
	""),
);
?>