<?php
 $JY_NEWS22 = array(
"La clôture du stage de la Ruche Culturelle Chinoise 2015",
"La clôture du stage de la Ruche Culturelle Chinoise 2015",
"",
"5 jan. 2015",
array(
),
array(	"<IMG src='".$PHOTO_PATH."jiaoyunews/1.jpg' width=500>",
	"Le stage de la Ruche Culturelle Chinoise 2014 de Paris organisé par le bureau des affaires des Chinois d’outre-mer, assisté par le bureau des affaires des Chinois d’outre-mer de la province du Shandong et L’Association des Amis de Nouvelles d’Europe s’est achevé le 3 janvier 2015 à L’Association des Amis de Nouvelles d’Europe à Gentilly. ",
	"<IMG src='".$PHOTO_PATH."jiaoyunews/U416P894T5D32561F42DT20150105100736.jpg' width=500>",
	"Des 150 d’adolescents environ ont suivi les cours de peinture et de calligraphie chinoise, de Kung-fu, de danse et de musique traditionnelles chinoises, et de arts artisanaux(papier découpé, masque d'opéra et pâte à modeler). Pendant 8 jours, ce stage a offert un moment idéal pour les enfants lors des vacances de Noël pour non seulement s’amuser, mais aussi pour leur permir de ressentir le charme de la culture chinoise.",
	"<IMG src='".$PHOTO_PATH."jiaoyunews/045604hkuufo9ndo33qll5.jpg' width=500>"),
);
?>