<?php
 $JY_NEWS16 = array(
"Apprendre en dansant",
"Les enfants apprennent avec plaisir d’exprimer des émotions et des sensations",
"",
"Le 19 septembre 2014",
array(
),
array(	"<IMG src='".$PHOTO_PATH."jiaoyunews/danseenfant-1.JPG' width=500>",
	"Les enfants apprennent avec plaisir à exprimer leurs émotions et leurs sensations à travers les gestes, les regards,  la danse  apporte également beaucoup au corps comme à l’esprit. Avec la danse chinoise, les enfants connaissent davantage la culture chinoise, ainsi que plusieurs styles de danse  illustrent de différents paysages.",
	"<IMG src='".$PHOTO_PATH."jiaoyunews/danseenfant2.JPG' width=500>",
	"Les enfants, venez danser avec nous ! ",
	"<IMG src='".$PHOTO_PATH."jiaoyunews/danseenfant-3.jpg' width=500>",
	"Date：17/09/2014 - 17/06/2015",
	"Horaire: Mercredi 14H00 – 15H30，15H45 – 17H15",
	"Professeur: Mme Zhu",
	"Contact：01 41 24 41 42(Mme Chen)/ 06 64 85 15 19(Mme Zhu)",
	""),
);
?>