<?php
 $JY_NEWS7 = array(
 
 "L’ouverture de la Ruche Culturelle Chinoise", 
 "Le stage de la Ruche Culturelle Chinoise 2013 de Paris est organisé par le bureau des affaires des Chinois d’outre-mer，","",
 "Le 23 décembre 2013 ",
			array("../photos/A2-7.JPG",""), 
array(
"Le stage de la Ruche Culturelle Chinoise 2013 de Paris est organisé par le bureau des affaires des Chinois d’outre-mer, assisté par le bureau des affaires des Chinois d’outre-mer de la province du Zhejiang , l’Association pour la Promotion de l’Éducation de la Langue chinoise en France et l’Association d’ALCIE. Ce stage a lieu à Paris du 23 décembre 2013 au 4 janvier 2014. Plus de 10 cours (les vertues chinoises, la culture chinoise, la lecture classique de la poésie, l’histoire et la géographie chinoises, les arts martiaux, la musique et la danse folklorique, la calligraphie, la peinture, les arts et métiers traditionnels) sont proposés aux enfants. Ce stage a offert un moment idéal pour les enfants lors des vacances de Noël pour non seulement s’amuser, mais aussi pour pouvoir développer leur connaissance de la culture chinoise. ")
 
 );
?>