<?php
 $JY_NEWS5 = array(
 "Les arts chinois par des enseignants du Yunnan", 
 "Organisé par l’Association des échanges avec l’étranger de Chine et le centre culturel et éducatif à l’étranger du Yunnan","",
 "16 décembre 2013",
	array(),
	array(
"Organisé par l’Association des échanges avec l’étranger de Chine et le Centre culturel et éducatif à l’étranger du Yunnan, un groupe d’enseignants chinois de la province Yunnan est venu en Ile-de-France pour former des talents chinois. ",
"<IMG SRC='".$PHOTO_PATH."yunnan/yunnan1.jpg' width=500>",
"Initié par l’Association pour la Promotion de l’Éducation de la Langue chinoise en France, ce groupe a passé deux jours entiers à donner des cours aux enseignants et aux élèves de quatre écoles de chinois. La formation comportait trois parties principales : la musique chinoise, l’acrobatie, et la calligraphie. ",
"<IMG SRC='".$PHOTO_PATH."yunnan/yunnan11.jpg' width=500>",	
"Après cet événement, la majorité des enseignants et des étudiants ont exprimé leur souhait de pouvoir bénéficier à nouveau de ce type d’événement afin de mieux connaître l’art traditionnel et la culture chinois.  ",
"<IMG SRC='".$PHOTO_PATH."yunnan/yunnan12.jpg' width=500>",
	)

 );
?>