<?php
 $JY_NEWS9 = array(
"Nouvelles classes en vacance d'été",
"Les vacances d’été approchent",
"",
"11 avril 2014",
array(
),
array(
"<IMG src='".$PHOTO_PATH."school/vacance600.jpg' width=500>", 
"Les vacances d’été approchent à grands pas, c'est le moment pour inscrire vos enfants aux activités proposées par l'Association des Amis de Nouvelles d’Europe.", 
"<b>Date : </b> Date : 7 juillet – 18 juillet (2 semaines)
", "<b>Classes : </b> Pinyin, Conversation, Ecriture, Peinture et calligraphie, Wushu(Kungfu), Danse, Jeu de Go
", "<b>Horaire :  </b> du lundi au samedi 14H00 -15H30; 15H45 – 17H15
", "<b>Contacts :  </b> 01 41 24 41 40 (Mme Wang) ou 01 41 24 41 44 (Mme Chen)",
" ")
);
?>