<?php
 $JY_NEWS6 = 
 	array("L’inscription à l’examen d’YCT (Youth Chinese Test) du 23 mars est ouverte", " ", "","le 26 décembre 2013",
		array(
			"../photos/school/YCTkaoshi.jpg",	"",
			"../photos/school/yctneirong.jpg",	"",
		),
		array(
"La Classe Confucius de Nouvelles d’Europe organise le YCT le 23 mars 2014. L’écrit du YCT (niveau 1 à 4) comprend une épreuve écrite et d’écoute. ",
"Horaires d’examen et frais d’inscription :",
"— Niveau I : 10h30 - 11h05, à 5 euros",
"— Niveau II : 14h00 - 14h50, à 10 euros",
"— Niveau III : 11h45 - 12h45, à 15 euros",
"— Niveau IV : 15h30 - 16h55, à 20 euros",
"Lieu d’examen : 48-50, Rue Benoît Malon, 94250 Gentilly",
"Inscription : ",
" Sur internet : <a href='http://www.chinesetest.cn' target=_blank>http://www.chinesetest.cn</a> ",
" Sur place : La Classe Confucius de Nouvelles d’Europe, Bureau 002",
"Paiement :",
"Vous pouvez payer en espèces ou en chèque sur place, ou envoyer le chèque à : Association des Amis de Nouvelles d’Europe, 48-50, Rue Benoît Malon, 94250 Gentilly.",
"Date limite d’inscription et de paiement : 21 février 2014."
	) 
 
 );
?>