<?php
 $JY_NEWS1 = array(
"Deux nouvelles classe d’aérobic pour les enfants sont ouvertes",
" ",
"",
"20 janvier 2014",
array(
),
array(
"Dans le but de favoriser chez les enfants une bonne constitution physique qui allie tonus, coordination et souplesse, nous avons cherché à nous appuyer sur leur spontanéité pour leur enseigner la danse, qui puisse leur permettre de développer une sensibilité et une émotion artistiques.  ", 
"<IMG SRC='".$PHOTO_PATH."school/chaiyipeixun.jpg' width=500>", "Le cours d’aérobic va durer trois mois et demi, du 5 mars 2014 au 18 juin 2014. ", "<b>Horaires :  </b> mercredi 14h00 - 15h30 ; 15h45 - 16h15. ", "<b>Contact : </b> 01 41 24 41 40 (Madame Wang) ", "", "", "")
);
?>