<?php
 $JL_NEWS24 = array(
"中华文化大乐园优秀才艺学生交流团专场演出",
"2014中华文化大乐园优秀才艺学生交流团法国展演巴黎专场将于10月19日下午15点和晚上19点30分",
"",
"2014年10月6日",
array(
),
array("<IMG src='".$PHOTO_PATH."jiaoliunews/dlyspectacle.jpg' width=500>", "2014中华文化大乐园优秀才艺学生交流团法国展演巴黎专场将于2014年10月19日下午15点和晚上19点30分在巴黎ISSY会议中心 (Palais des Congrès d'Issy, 25 avenue Victor Cresson 92130 Issy les Moulineaux) 拉开帷幕。由中国国务院侨务办公室主办，湖南快乐出发传媒有限公司承办，欧洲时报传媒集团协办的这两场演出，聚集了从国内选拔出来的19名7岁到21岁的优秀青少年，他们将为大家呈现一台歌舞、乐器、杂技及武术等组成的精彩节目.", "", "演出时间：2014年10月19日星期日15h00， 19h30两场", "演出地点：Palais des Congrès d'Issy", "25 avenue Victor Cresson 92130 Issy les Moulineaux", "", "", ""),
);
?>