<?php 

$JL_NEWS6 =		array("开门迎街坊，香槟待朋友", 
			"2013年12月15日上午，欧洲时报文化中心举行了新址揭牌仪式，",
			"","2013年12月15日",
			array("../photos/meeting/openparty.jpg","", "../photos/meeting/party2.jpg","", "../photos/meeting/party.png",""), 
			$NEW_WELCOM

);


$JL_NEWS6_s = array(
"新址开幕酒会",
array("spectcocktail/cocktailtitre-600.jpg", "新址开幕酒会",  "JL_NEWS6_sp", ), //images
array(
"2013年12月15日下午，欧洲时报文化中心在当日上午的新址揭牌仪式后，举办了香槟酒会招待新朋旧友。",
"在邀请大家参观设计雅致大方的新馆同时，中心不但以香槟美食相待，更用丰富的图片向大家介绍了文化中心举办的各种群众文化活动。大家欣喜地欢聚一堂，频频举杯，共祝美好未来！"
), //text
$JL_NEWS6_sp // photo list
);

?>