<?php

$JL_EXPO = array(
	$JL_NEWS19_s, $JL_NEWS17_s, $JL_NEWS11_s, $JL_NEWS10_s, $JL_NEWS9_s, $JL_NEWS7_s, $JL_NEWS3_s, $JL_NEWS_SF_s
);

$JL_EXPO_NAME = array(
	"JL_NEWS19_s", "JL_NEWS17_s", "JL_NEWS11_s", "JL_NEWS10_s", "JL_NEWS9_s", "JL_NEWS7_s", "JL_NEWS3_s", "JL_NEWS_SF_s"
);

$JL_CONF = array(
	$JL_NEWS16_s, $JL_NEWS14_s, $JL_NEWS13_s, $JL_NEWS12_s, $JL_NEWS5_s, $JL_NEWS_DB_s
);

$JL_CONF_NAME = array(
	"JL_NEWS16_s", "JL_NEWS14_s", "JL_NEWS13_s", "JL_NEWS12_s", "JL_NEWS5_s", "JL_NEWS_DB_s"
);

$JL_FETE = array(
	$jlpage_75_s, $JL_NEWS24_3_s, $WY_NEWS12_s, $JL_NEWS8_s, $JL_NEWS6_s, $JL_NEWS_ML_s
);

$JL_FETE_NAME = array(
	"jlpage_75_s", "JL_NEWS24_3_s", "WY_NEWS12_s", "JL_NEWS8_s", "JL_NEWS6_s", "JL_NEWS_ML_s"
);



?>