<?php
 $JY_NEWS12 = array(
"欧洲时报成人中文班开始招生",
"成人汉语班使用《当代中文》作为主教材，《长城汉语》作为辅助教材，",
"",
"2014年5月31日",
array(
),
array(	"<IMG src='".$PHOTO_PATH."school/adulte.jpg' width=500>",
	"汉语学习在法国持续升温，除了青少年外，越来越多的成年人也投入到学习汉语的热潮中。成人汉语班即是针对希望学习汉语的成年人而开办的。成人汉语班使用《当代中文》作为主教材，《长城汉语》作为辅助教材，根据学生的汉语程度分为初级班和提高班。在教学过程中借助现代教学手段，注重教学内容的实用性，以练为主，使学生能学有所用。",
	"2014-2015学年度报名现在开始。报名时将由老师对学生（除初学者）进行一个简单水平测试。",
	"上课时间：",
	"<IMG src='".$PHOTO_PATH."wenyunews/coursadultes600.jpg' width=500>",
	""),
array(
"Inscriptions des cours de chinois pour adultes",
"Les inscriptions pour l'année scolaire 2014-2015 peuvent se faire dès à présent",
"",
"",
array(
),
array(	"<IMG src='".$PHOTO_PATH."school/adulte.jpg' width=500>",
	"Pour répondre aux besoins des adultes, nous avons mis en place depuis quelques années des cours pour ceux qui souhaitent acquérir certaines connaissances sur la langue chinoise. Le manuel principal est «Le chinois contemporain», avec en complément «Great Wall Chinese», tous les deux édités par Hanban. Les élèves sont répartis dans deux classes selon leur niveau. Étant donné la faible disponibilité des élèves après les cours, nous sélectionnons les textes et nous consacrons plus de temps aux exercices en classe.",
	"Les inscriptions pour l'année scolaire 2014-2015 peuvent se faire dès à présent. Les élèves devront  passer un test pour être répartis dans les classes adaptées à leur niveau, sauf pour les débutants.",
	"&quot;Horaire：",
	"<IMG src='".$PHOTO_PATH."wenyunews/coursadultes600.jpg' width=500>"),
)
);
?>