<?php
 $JY_NEWS14 = array(
"成人法语班",
"为了帮助旅法的华侨、华裔更好地融入法国社会，提高法语水平，加强交流能力，欧洲时报文化中心开办了成人法文班。",
"",
"2014年9月16日",
array(
),
array(	"<IMG src='".$PHOTO_PATH."jiaoyunews/cours de fr.JPG' width=500> ",
	"为了帮助旅法的华侨、华裔更好地融入法国社会，提高法语水平，加强交流能力，欧洲时报文化中心开办了成人法文班。",
	"成人法文班提倡纯语境的小班教学，每班不超过10人。教学内容紧密结合日常生活需要，注重听说能力的培养。任教老师曾在法国公立学校执教多年，具备教授外国人法语的教师资格证书，具有丰富的教学经验。报名后将由老师进行一对一的水平测试，提出分班建议。",
	"",
	"每周四19H00-21H00（学生假期及节假日除外）",
	"联系电话：01 41 24 41 42 / 44 （陈老师）",
	""),
array(
"Cours de français pour adultes",
"Cours de français pour adult s’adresse à tous les niveaux",
"",
"le 16 septembre 2014",
array(
),
array(	"<IMG src='".$PHOTO_PATH."jiaoyunews/cours de fr.JPG' width=500>",
	"Le cours de langue française s’adresse à tous les niveaux. L’objectif est de pouvoir commencer à communiquer en français pour les débutants, puis d’acquérir une autonomie permettant de faire face à la plupart des situations de la vie courante. Puis les cours peuvent permettre de perfectionner la pratique et la compréhension du français. Ces cours sont basés sur les méthodes de communication, et supposent la participation active des élèves.",
	"Le professeur de français, qui a reçu une formation à l’Alliance française de Paris, a longtemps été instituteur dans le 13è arrondissement de Paris, et il a déjà enseigné aux adultes dans diverses associations.",
	"Après l’inscription, le professeur fait passer un test individuel pour trouver le cours correspondant au niveau de chacun.",
	"",
	"Date: 25/09/2014-25/06/2015 ",
	"Tous les jeudis hors vacances scolaires et jours fériés ",
	"19H00-21H00",
	"",
	"Contact: 01 41 24 41 42 / 44 (Mme Chen)",
	""),
)
);
?>