<?php
 $JY_NEWS3 = array(
"2013年11月YCT成绩揭晓",
"2013年11月16日在欧洲时报孔子课堂举行的YCT考试成绩已经揭晓 ",
"",
"2013年12月28日",
array(
),
array(	"2013年11月16日在欧洲时报孔子课堂举行的YCT考试成绩已经揭晓。考生们可登录 <a href=http://www.chinesetest.cn/index.do target=_blank>http://www.chinesetest.cn</a>，输入自己的准考证号、姓名及验证码进行查询。",
	"<IMG SRC='".$PHOTO_PATH."YCTSite.jpg' width=500>",
	"这次考试实际参考的学生共193名，其中95%的考生都通过了考试，超过三分之一的考生获得了满分。本欧洲时报孔子课堂共有151名学生参加了本次考试，除四级有两人不合格外，其余全部合格，一二级的满分率过半。",
	"宝剑锋从磨砺出，梅花香自苦寒来。向所有取得好成绩的考生祝贺！并期待大家在更高一级的考试中取得更好的成绩！",
	""),
array(
"L’école de chinois et la Classe Confucius de Nouvelles d’Europe déménagent à Gentilly",
"",
"",
"",
array(
),
array(	"Les résultats du YCT du 16 novembre 2013 sont sortis. Les étudiants peuvent s’en enquérir sur le site <a href='http://www.chinesetest.cn' target=_blank>http://www.chinesetest.cn</a> ",
	"avec leur numéro d’examen, leur nom et le code de vérification.",
	"<IMG SRC='".$PHOTO_PATH."YCTSite.jpg' width=500>",
	"193 étudiants au total ont participé à cet examen, 95% l’ont réussi et plus d’un tiers ont eu 200/200. Les 151 étudiants de la Classe Confucius de Nouvelles d’Europe l’ont réussi, mis à part 2 personnes au niveau IV.",
	"Félicitations à tous et bonne continuation à tout le monde !"),
)
);
?>