<?php
 $JY_NEWS8 = array(
"新增周三书画课",
"应广大学生及家长的要求，欧洲时报中文学校从三月起新增周三书画课。",
"",
"2014年3月1日",
array(
),
array(	"2013年6月，欧洲时报文化中心书画班学生的书画作品汇报展成功举办。学生们在执教老师：法国书画家协会马剑虹会长的悉心指导下，书画水平得到了很大的提高。",
	"<IMG src='".$PHOTO_PATH."school/shufa-600.jpg' width=500>",
	"应广大学生及家长的要求，欧洲时报中文学校从三月起新增周三书画课。",
	"中国书法和绘画经过几千年的历史沉淀，已经成为中国的国粹。练习书画不仅能陶冶人的情操，培养高雅的业余爱好和文明的风度，还能给人以愉悦，激发人的感情，宁神健魄。教学中，教师注重因材施教，针对个人的水平和特色做个性化的辅导。",
	"书画课为期三个月，2014年3月19日开学，至6月18日结束。",
	"上课时间：星期三 14:00 - 15:30，15:45 - 16:15 ",
	"报名电话：01 41 24 41 42（陈老师）/ 01 41 24 41 40（王老师）",
	"相关链接：<a href='http://www.culture-oushi.com/jiaoliu/?action=subitem&resource=exposition&hindex=7'>书画班学生作品汇报展</a>",
	""),
array(
"Nouveaux cours de calligraphie et de peinture le mercredi",
"Par professeur Ma Jianhong",
"",
"",
array(
),
array(	"Organisée en juin 2013, l’exposition des œuvres réalisées par les étudiants de la classe de peinture de l’Association des Amis de Nouvelles d’Europe a remporté un grand succès. Sous la direction de l’enseignant Ma Jianhong, Président de l'Association le Pinceau d’Or, les étudiants ont beaucoup progressé. ",
	"<IMG src='".$PHOTO_PATH."school/shufa-600.jpg' width=500>",
	"A la suite de la demande des élèves et des parents, nous avons décidé d’ajouter deux cours le mercredi à partir du mois de mars. ",
	"La calligraphie et la peinture chinoises ont une histoire commune vieille de milliers d'années, et représentent la quintessence profonde de la Chine. Pratiquer l’art de la calligraphie c’est non seulement se cultiver, mais c’est aussi le plaisir d'acquérir de l'élégance et la paix de l’âme. L'enseignement est très personnalisé.",
	"Le cours de calligraphie et de peinture va durer trois mois, du 19 mars 2014 au 18 juin 2014.",
	"<b>Horaires: </b> Mercredi 14h00 - 15h30 ; 15h45 - 16h15",
	"<b>Contacts : </b> 01 41 24 41 42 (Madame CHEN) ou 01 41 24 41 40 (Madame WANG)"),
)
);
?>