<?php
 $JY_NEWS13 = array(
"新学年开始了",
"轻松愉快的暑假过去了，新的学年又开始了，请同学们准备好你们的中文书包和其它学习用具，投入到新的挑战中去吧。",
"",
"2014年9月6日",
array(
),
array(	"轻松愉快的暑假过去了，新的学年又开始了，请同学们准备好你们的中文书包和其它学习用具，投入到新的挑战中去吧。",
	"请家长配合学校的要求，出席第一节课的家长会，提醒同学们别忘记带假期作业哦。",
	"",
	"开学时间：",
	"周三周六班：9月13日星期六",
	"周三周日班：9月14日星期日",
	"周三班：    9月17日星期三",
	""),
array(
"La rentrée arrive",
"Ça y est, les vacances sont terminées, nous sommes prêts pour la rentrée. Préparez vos affaires de chinois et les devoirs des vacances pour le premier cours.",
"",
"le 6 septembre 2014",
array(
),
array(	"  Ça y est, les vacances sont terminées, nous sommes prêts pour la rentrée. Préparez vos affaires de chinois et les devoirs des vacances pour le premier cours.",
	"",
	"  Les parents doivent se présenter au premier cours de la rentrée.",
	"",
	"A noter les dates de la rentrée :",
	"Cours de mercredi/samedi	le 13 septembre 2014",
	"Cours de mercredi/dimanche	le 14 septembre 2014",
	"Cours de mercredi		le 17 septembre 2014",
	""),
)
);
?>