<?php
 $JY_NEWS18 = array(
"增开周六书法、山水画班",
"书法班既可习写软笔即毛笔，也可练习硬笔即钢笔、原珠笔等。学员各选其爱，也可两者兼学。",
"",
"2014年10月22日",
array(
),
array(	"<IMG src='".$PHOTO_PATH."jiaoyunews/caligraphie.jpg' width=500>",
	"书法班既可习写软笔即毛笔，也可练习硬笔即钢笔、原珠笔等。学员各选其爱，也可两者兼学。",
	"已开设的星期日上午班超额招员，现为满足学习者之需新增开周六下午班。",
	"",
	"学制：约25周，2014年11月中旬 －2015年6月中旬。",
	"上课时间：星期六13H30 – 15H30",
	"学习者可在该时间段里自选1个半小时或2小时的课。",
	"",
	"教学地点：欧洲时报文化中心101室。",
	"聘请著名旅法书法、山水画家马剑虹先生任教。",
	"报名电话 01 41 24 41 42 / 40 / 44",
	""),
array(
"Nouvelle classe de calligraphie chinoise",
"Le nouveau cours de calligraphie chinoise se fait avec soit pinceau, soit stylo plume ou stylo.",
"",
"Le 22 octobre 2014",
array(
),
array(	"<IMG src='".$PHOTO_PATH."jiaoyunews/caligraphie.jpg' width=500>",
	"Le nouveau cours de calligraphie chinoise se fait avec plusieurs styles, chaque élève peut la pratiquer soit au pinceau, soit au stylo plume ou au stylo.",
	"",
	"Date：du mi-novembre 2014 – mi-juin 2015",
	"Horaire：Samedi 13H30 – 15H30",
	"Professeur：peintre célèbre Monsieur Ma Jianhong",
	"Contact：01 41 24 41 42",
	""),
)
);
?>