<?php
 $JY_NEWS23 = array(
"2014年12月YCT、HSK成绩揭晓",
"2014年12月YCT、HSK成绩揭晓",
"",
"2015年1月24日",
array(
),
array(	"2014年12月6日、12月7日在欧洲时报孔子课堂举行的YCT、HSK考试成绩已经揭晓。考生们可登录 <a href='http://www.chinesetest.cn/ChangeLan.do?languge=zh_CN&t=1422139974808' target='_blank'>http://www.chinesetest.cn</A> 输入自己的准考证号、姓名及验证码进行查询。收到从中国寄来的考试成绩报告后，届时将会通知各位考生前来领取成绩单。",
	"<IMG src='".$PHOTO_PATH."jiaoyunews/QQ截图20150125063025.png' width=500>",
	"向所有取得好成绩的考生祝贺！并期待大家在更高一级的考试中取得更好的成绩！"),
array(
"Les résultats de l’examen du YCT et du HSK de décembre 2014 sont sortis",
"Les résultats de l’examen du YCT et du HSK de décembre 2014 sont sortis",
"",
"24 Jan. 2015",
array(
),
array(	"Les résultats du YCT et du HSK du 6 décembre et du 7 décembre 2014 sont sortis. Les étudiants peuvent s’en enquérir sur le site <a href='http://www.chinesetest.cn/ChangeLan.do?languge=fr&t=14221400257068' target='_blank'>http://www.chinesetest.cn</A> avec leur numéro d’examen, leur nom et le code de vérification. Apès avoir reçu les bulletins de notes envoyés de la Chine, nous allons vous contacer.",
	"<IMG src='".$PHOTO_PATH."jiaoyunews/QQ截图20150125063025.png' width=500>",
	"Félicitations à tous et bonne continuation à tout le monde !"),
)
);
?>