<?php
 $JY_NEWS5 = array(
"云南省中华才艺培训团赴法送艺",
"云南省海外交流协会、云南海外文化教育中心组织中华才艺培训团远赴法国",
"",
"2013年12月16日",
array(
),
array(	"云南省海外交流协会、云南海外文化教育中心组织中华才艺培训团远赴法国，为在巴黎大区的华侨华人子弟进行中华才艺的培训。",
	"由法国华文教育协会牵头，云南省中华才艺培训团对四所中文学校的师生进行了为期两天的中华才艺培训。培训内容包括中国声乐、杂技手技和书法绘画三大项目，欧洲时报中文学校、中华圣母堂中文学校、华侨华人会中文学校及华裔互助会中文学校共四所学校的师生兴致勃勃地参加了培训。",
	"很多老师和学生家长都对老师们不远万里、不辞劳苦来到异国他乡传授中国传统文化以及艺术，表示钦佩和感谢！参加才艺培训的同学们也对活动表示出了浓厚的兴趣。大家不但聚精会神地观看老师的示范，而且还十分积极踊跃地参与。每个人都学得津津有味，当培训接近尾声时，大家都意犹未尽，恋恋不舍。",
	"活动结束后，广大师生和学生家长纷纷表示，希望今后能有更多这样的机会能近距离地接触和了解中国的传统文化和艺术。",
	""),
array(
"Les arts chinois par des enseignants du Yunnan",
"Organisé par l’Association des échanges avec l’étranger de Chine et le centre culturel et ",
"",
"",
array(
),
array(	"Organisé par l’Association des échanges avec l’étranger de Chine et le Centre culturel et éducatif à l’étranger du Yunnan, un groupe d’enseignants chinois de la province Yunnan est venu en Ile-de-France pour former des talents chinois.",
	"<IMG SRC='".$PHOTO_PATH."yunnan/yunnan1.jpg' width=500>",
	"Initié par l’Association pour la Promotion de l’Éducation de la Langue chinoise en France, ce groupe a passé deux jours entiers à donner des cours aux enseignants et aux élèves de quatre écoles de chinois. La formation comportait trois parties principales : la musique chinoise, l’acrobatie, et la calligraphie.",
	"<IMG SRC='".$PHOTO_PATH."yunnan/yunnan11.jpg' width=500>	",
	"Après cet événement, la majorité des enseignants et des étudiants ont exprimé leur souhait de pouvoir bénéficier à nouveau de ce type d’événement afin de mieux connaître l’art traditionnel et la culture chinois.",
	"<IMG SRC='".$PHOTO_PATH."yunnan/yunnan12.jpg' width=500>"),
)
);
?>