<?php
 $JY_NEWS9 = array(
"欧洲时报中文学校暑期两周班",
"愉快的假期到了，娱乐+健身+学习， 不离开巴黎，暑期生活也丰富多彩！",
"",
"2014年4月11日",
array(
),
array(	"<IMG src='".$PHOTO_PATH."school/vacance600.jpg' width=500>",
	"",
	"孩子们盼望的暑假就快到了，许多家长因为工作繁忙而无暇顾及和陪伴孩子整个假期，为此我们开设了多种多样的暑期班，娱乐+健身+学习，让孩子们不离开巴黎，也有丰富多彩的暑期生活。同时也为一些缺课和学习成绩不佳的学生提供补习和加强学习内容的机会。",
	"",
	"2014年暑期班现在开始招生，丰富的暑期生活，伴孩子度愉快假期，欢迎报名！",
	"",
	"",
	"",
	"<b>开班日期： </b> 2014年7月7日 - 7月18日两周（周日、节日不上课）",
	"",
	"<b>课程设置： </b> 拼音补习班，口语速成班，汉字书写班，书法绘画班，少儿武术班，少儿健美班，围棋入门班 ",
	"",
	"<b>上课时间： </b> 星期一到星期六   14h00-15h30    15h45-17h15",
	"",
	"<b>友情提醒： </b> 建议参加两项课程，孩子们在学校度过整个下午，亦学亦玩，省心省事。",
	"",
	"<b>报名电话： </b> 01 41 24 41 40 （王老师）/ 01 41 24 41 44 （陈老师）",
	"",
	""),
array(
"Nouvelles classes en vacance d'été",
"",
"",
"",
array(
),
array(	"<IMG src='".$PHOTO_PATH."school/vacance600.jpg' width=500>",
	"Les vacances d’été approchent à grands pas, c'est le moment pour inscrire vos enfants aux activités proposées par l'Association des Amis de Nouvelles d’Europe.",
	"<b>Date : </b> Date : 7 juillet – 18 juillet (2 semaines)",
	"<b>Classes : </b> Pinyin, Conversation, Ecriture, Peinture et calligraphie, Wushu(Kungfu), Danse, Jeu de Go",
	"<b>Horaire :  </b> du lundi au samedi 14H00 -15H30; 15H45 – 17H15",
	"<b>Contacts :  </b> 01 41 24 41 40 (Mme Wang) ou 01 41 24 41 44 (Mme Chen)"),
)
);
?>