<?php
 $JY_NEWS4 = array(
"中华文化大乐园举行闭营式",
"“中华文化大乐园法国巴黎营”在法国巴黎精英中文学校开营，",
"",
"2014年1月4日",
array(
),
array(	"由中国国务院侨务办公室主办，浙江侨务办公室、法国华文教育协会和巴黎精英中文学校协办“中华文化大乐园法国巴黎营”于1月4日举行了闭营仪式。",
	"历时15天的“中华文化大乐园法国巴黎营”自12月23日开营以来，百余名华裔青少年们跟着老师学习打快板、画国画、练书法、跳藏舞以及拳术、珠算和米塑等等，深深感受到中华文化的无穷魅力。浙江省侨办从全省遴选的11名优秀教师不辞劳苦，共给孩子们上了120堂内容丰富、能充分表现中华文化精髓的教学课，圆满地完成了大乐园的各项教学任务。",
	"<IMG SRC='".$PHOTO_PATH."huodong/leyuan2014-3.jpg' width=500>",
	"<IMG SRC='".$PHOTO_PATH."huodong/leyuan2014-4.jpg' width=500>",
	"代表团团长、浙江省侨办徐高春副主任、以及中国驻法临时代办夫人、使馆阳光学校代校长张华女士、法国侨团代表华侨华人爱心会徐乐平会长和巴黎11区政府代表Sophie Pradinas等应邀出席了闭营仪式并致辞。营员们在闭营式上充分展示了他们在大乐园中学到的各种中华才艺，墙上的书画作品、生动活泼的表演赢来了来宾和家长的阵阵称赞！",
	"<IMG SRC='".$PHOTO_PATH."huodong/leyuan2014-2.jpg' width=500>",
	"“中华文化大乐园法国巴黎营”以精彩纷呈的教学成果展示，在一片欢声笑语中圆满闭营。",
	""),
array(
"La clôture du stage de la Ruche Culturelle Chinoise",
"",
"",
"",
array(
),
array(	"<IMG SRC='".$PHOTO_PATH."huodong/leyuan2014-1.jpg' width=500>",
	"Le stage de la Ruche Culturelle Chinoise 2013 de Paris organisé par le bureau des affaires des Chinois d’outre-mer, assisté par le bureau des affaires des Chinois d’outre-mer de la province du Zhejiang et l’Association pour la Promotion de l’Éducation de la Langue chinoise en France s’est achevé le 4 janvier.",
	"<IMG SRC='".$PHOTO_PATH."huodong/leyuan2014-3.jpg' width=500>",
	"<IMG SRC='".$PHOTO_PATH."huodong/leyuan2014-4.jpg' width=500>",
	"Des centaines d’adolescents (principalement d’origine chinoise) ont suivi les cours de peinture chinoise, de calligraphie, de danse tibétaine, d’arts martiaux, de sculpture de pâte de riz etc. Pendant 15 jours, cela leur a permis de ressentir le charme de la culture chinoise.",
	"Les 11 enseignants de niveau supérieur sélectionnés par le bureau des affaires des Chinois d’outre-mer de la province Zhejiang ont donné 120 cours, riches de contenus diversifiés. ",
	"<IMG SRC='".$PHOTO_PATH."huodong/leyuan2014-2.jpg' width=500>"),
)
);
?>