<?php
 $JY_NEWS7 = array(
"中华文化大乐园开园",
" ",
"",
"2013年12月23日",
array(
),
array(	"“中华文化大乐园”是国务院侨办创建的“走出去”的海外办营品牌，旨在满足日益增多的海外华裔青少年了解中华文化的需求，推动中华文化在海外的传承，涵盖侨务资源，促进侨务工作的可持续发展。该活动自2011年开办至今，已有数百名教师到海外授课，足迹遍及20多个国家和地区，参加的营员有万余名。",
	"“2013中华文化大乐园法国巴黎营”由国务院侨务办公室主办，浙江省侨办、法国华文教育协会、法国语言文化国际交流协会相关照片属巴黎精英中文学校具体承办。本次巴黎营从12月23日至2014年1月4日，设有中华美德和中华文化讲座、经典诗文诵读、中国历史地理常识、珠心算、中华武术、民族音乐、民族舞蹈、书法、国画、传统手工艺等10多门课程，希望为孩子们在圣诞节期间提供一个增长知识的好去处。为了这次活动，浙江省侨办精心选派了11名国内中小学一级和高级教师，他们把中国传统文化带到巴黎，让法国华裔儿童青少年以及喜爱中国文化的法国小朋友在家门口就能全面接触和享受到美伦美奂的中国传统文化。",
	"1月4日将在华侨饭店举行盛大的闭营仪式，小朋友们将集中展示学习成果。",
	""),
array(
"L’ouverture de la Ruche Culturelle Chinoise",
"Le stage de la Ruche Culturelle Chinoise 2013 de Paris est organisé par le bureau des affa",
"",
"",
array(
),
array(	"Le stage de la Ruche Culturelle Chinoise 2013 de Paris est organisé par le bureau des affaires des Chinois d’outre-mer, assisté par le bureau des affaires des Chinois d’outre-mer de la province du Zhejiang , l’Association pour la Promotion de l’Éducation de la Langue chinoise en France et l’Association d’ALCIE. Ce stage a lieu à Paris du 23 décembre 2013 au 4 janvier 2014. Plus de 10 cours (les vertues chinoises, la culture chinoise, la lecture classique de la poésie, l’histoire et la géographie chinoises, les arts martiaux, la musique et la danse folklorique, la calligraphie, la peinture, les arts et métiers traditionnels) sont proposés aux enfants. Ce stage a offert un moment idéal pour les enfants lors des vacances de Noël pour non seulement s’amuser, mais aussi pour pouvoir développer leur connaissance de la culture chinoise.",
	""),
)
);
?>