<?php
 $JY_NEWS1 = array(
"少儿健美舞开班啦",
"少儿舞蹈训练，在教学上用童心追求童趣，不仅培养学生健美的体魄，发展其灵活性，",
"",
"2014年1月20日",
array(
),
array(	"少儿舞蹈训练，在教学上用童心追求童趣，不仅培养学生健美的体魄，发展其灵活性，柔韧性和协调性。而且在潜移默化中培养美的情操，引导学生对舞蹈表现形式和情感内涵的整体把握。",
	"<IMG SRC='".$PHOTO_PATH."school/chaiyipeixun.jpg' width=500>",
	"本期少儿健美舞班为期三个半月，2014年3月5日开学，至6月18日结束。",
	"上课时间：星期三 14:00 - 15:30，15:45 - 16:15",
	"报名电话：01 41 24 41 40（王老师）",
	""),
array(
"Deux nouvelles classe d’aérobic pour les enfants sont ouvertes",
"",
"",
"",
array(
),
array(	"Dans le but de favoriser chez les enfants une bonne constitution physique qui allie tonus, coordination et souplesse, nous avons cherché à nous appuyer sur leur spontanéité pour leur enseigner la danse, qui puisse leur permettre de développer une sensibilité et une émotion artistiques.",
	"<IMG SRC='\&quot;.$PHOTO_PATH.school/chaiyipeixun\&quot;.jpg' width=500>",
	"Le cours d’aérobic va durer trois mois et demi, du 5 mars 2014 au 18 juin 2014. ",
	"<b>Horaires :  </b> mercredi 14h00 - 15h30 ; 15h45 - 16h15. ",
	"<b>Contact : </b> 01 41 24 41 40 (Madame Wang) "),
)
);
?>