<?php
 $JY_NEWS2 = array(
"欧洲时报中文学校、欧洲时报孔子课堂喜迁新址",
"欧洲时报文化中心于2013年12月初搬入位于Gentilly的新址，",
"",
"2013年12月10日",
array(
),
array(	"欧洲时报文化中心于2013年12月初搬入位于Gentilly的新址，欧洲时报中文学校、欧洲时报孔子课堂也同时迁入。",
	"新址位于巴黎南部近郊的Gentilly市，紧邻巴黎著名的大学城。整体设计雅致大方，既尊重法国建筑传统，又暗合中国传统的天人合一理念，体现人文思想，并处处考虑到中文学校学生的安全和方便。",
	"为了配合多媒体教学的发展趋势，全新的教室整洁明亮，还配置了大屏幕以及齐全的接口。",
	"舞蹈和武术教室硬件一流，不但有整面墙的镜子、适合不同年龄度的把杆，还有独特的竹地板。",
	"<IMG SRC='".$PHOTO_PATH."school/childrenroom.jpg' width=500>",
	"幼儿教室中，专门为孩子们选配的颜色鲜艳的方块坐墩，深受孩子们的喜爱。",
	"<IMG SRC='".$PHOTO_PATH."school/pianoroom.jpg' width=500>",
	"新址还设有钢琴教室、多媒体教室、书画教室以及图书馆等。",
	""),
array(
"L’école de chinois et la Classe Confucius de Nouvelles d’Europe déménagent à Gentilly",
"L’école de chinois et la Classe Confucius de Nouvelles d’Europe déménagent à Gentilly",
"",
"",
array(
),
array(	"Les Amis de Nouvelles d’Europe (Association, école de chinois et Classe Confucius) s’installent au 48-50 rue Benoît-Malon à Gentilly à partir de décembre 2013.",
	"<IMG SRC='".$PHOTO_PATH."school/school.jpg' width=500>",
	"Le nouveau local est situé au sud de Paris, tout à côté de la Cité Universitaire. Ce nouveau, beau et grand édifice est caractéristique de l’architecture traditionnelle française tout en respectant la conception chinoise d’équilibre entre l’homme et la nature. Toutes les infrastructures sont conçues pour la convenance et la sécurité des élèves.",
	"<IMG SRC='".$PHOTO_PATH."school/school2.jpg' width=500>",
	"Les équipements multimédias sont installés dans de lumineuses salles de formation.",
	"<IMG SRC='".$PHOTO_PATH."school/danceroom.jpg' width=500>",
	"Le mur de miroirs et le parquet en bambou nous permettent de suivre plus facilement les cours de danse ou d’arts martiaux.",
	"<IMG SRC='".$PHOTO_PATH."school/childrenroom.jpg' width=500>",
	"Les poufs aux couleurs vives ont été choisis particulièrement pour les enfants d’âge préscolaire.",
	"<IMG SRC='".$PHOTO_PATH."school/pianoroom.jpg' width=500>",
	"Le nouveau site dispose également d’une salle de piano, d’une salle informatique, d’une salle de calligraphie et peinture, et d’une bibliothèque.",
	""),
)
);
?>