<?php
 $JY_NEWS20 = array(
"圣诞快乐",
"圣诞快乐",
"",
"2014年12月24日",
array(
),
array(	"<div class='note_title'><h1>  <b>圣诞快乐！</b> </h1></div> ",
	"<IMG src='".$PHOTO_PATH."jiaoyunews/noel.jpg' width=500>",
	""),
array(
"Joyeux Noël",
"Joyeux Noël",
"",
"le 24 décembre 2015",
array(
),
array(	"<div class='note_title'><h1>  <b>Joyeux Noël！</b> </h1></div> ",
	"<IMG src='".$PHOTO_PATH."jiaoyunews/noel.jpg' width=500>",
	""),
)
);
?>