<?php
include ("jy_news23.inc");
include ("jy_news22.inc");
include ("jy_news21.inc");
include ("jy_news20.inc");

include ("jy_news1.inc");
include ("jy_news2.inc");
include ("jy_news3.inc");
include ("jy_news4.inc");
include ("jy_news5.inc");
include ("jy_news6.inc");
include ("jy_news7.inc");
include ("jy_news8.inc");
include ("jy_news9.inc");
include ("jy_news10.inc");
include ("jy_news11.inc");
include ("jy_news12.inc");
include ("jy_news13.inc");
include ("jy_news14.inc");
include ("jy_news15.inc");
include ("jy_news16.inc");
include ("jy_news17.inc");
include ("jy_news18.inc");
include ("jy_news19.inc");













$JY_NEWS = array($JY_NEWS1, $JY_NEWS2, $JY_NEWS3, $JY_NEWS4, $JY_NEWS5, $JY_NEWS6, $JY_NEWS7, $JY_NEWS8, $JY_NEWS9, $JY_NEWS10, $JY_NEWS11, $JY_NEWS12, $JY_NEWS13, $JY_NEWS14, $JY_NEWS15, $JY_NEWS16, $JY_NEWS17, $JY_NEWS18, $JY_NEWS19, $JY_NEWS20, $JY_NEWS21, $JY_NEWS22, $JY_NEWS23);?>

