CREATE TABLE IF NOT EXISTS REG_TABLE(
IDS INTEGER  NOT NULL AUTO_INCREMENT, 
CIVIL 		CHAR(1), 
CNAME 		VARCHAR(64), 
FNAME 		VARCHAR(64), 
BIRTHDAY 	VARCHAR(64), 
PHONE 		VARCHAR(32), 
MOBILE 		VARCHAR(32), 
FAX  		VARCHAR(32), 
EMAIL 		VARCHAR(128), 
STREET 		VARCHAR(128),  
CITY 		VARCHAR(64), 
POSTCODE 	VARCHAR(64),
DEPARTEMENT VARCHAR(64), 
COUNTRY 	VARCHAR(32), 
CLASSES 	VARCHAR(32), 
TIMES 		VARCHAR(32), 
PAYEMENT 	VARCHAR(32), 
REGISTDATE 	VARCHAR(32), 
LASTMODIFY 	VARCHAR(32), 
CHINESE 	VARCHAR(32), 
PARENTS 	VARCHAR(32), 
HDINDEX 	VARCHAR(32), 
COMMENTS 	VARCHAR(512), 
VALIDED 	CHAR(1), 
DELETED 	CHAR(1), 
PRIMARY KEY (IDS)
)ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci AUTO_INCREMENT=1;
 
CREATE TABLE IF NOT EXISTS ALBUMS(
IDS INTEGER  NOT NULL AUTO_INCREMENT, 
TITLE 		VARCHAR(256), 
FTITLE 		VARCHAR(256), 
ANNEE 		INTEGER, 
DATES 		VARCHAR(32), 
PATH 		VARCHAR(256), 
FILES 		VARCHAR(256), 
REMARKS  	VARCHAR(256), 
GROUPS  	VARCHAR(32), 
DELETED 	CHAR(1), 
PRIMARY KEY (IDS)
)ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci AUTO_INCREMENT=1;
 
CREATE TABLE IF NOT EXISTS OUSHINEWS (
IDS INTEGER  NOT NULL AUTO_INCREMENT, 
TITLE 		VARCHAR(512), 
FTITLE 		VARCHAR(512), 
PUBLIE 		VARCHAR(32), 
STITLE 		VARCHAR(512), 
FSTITLE 	VARCHAR(512), 
RESUME		VARCHAR(512), 
FRESUME		VARCHAR(512), 
CONTENTS	TEXT, 
FCONTENTS	TEXT, 
MAINNEWS	INTEGER, 
STARS		INTEGER, 
KONGZI		INTEGER, 
POSITION	INTEGER, 
LASTMODIF	VARCHAR(32),
NEWSTYPE	INTEGER,
TOP5 		INTEGER,
TOPPHOTOC	VARCHAR(128),
TOPPHOTOF	VARCHAR(128),
LINKC	VARCHAR(128),
LINKF	VARCHAR(128),
DELETED 	CHAR(1), 
PRIMARY KEY (IDS)
)ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS OUSHIADMINUSER (
IDS INTEGER  NOT NULL AUTO_INCREMENT, 
NAMES 		VARCHAR(32), 
USER 		VARCHAR(32), 
PASSWD 		VARCHAR(16), 
LEVEL 		INTEGER, 
PHONE 		VARCHAR(32), 
MOBILE		VARCHAR(32), 
EMAIL		VARCHAR(32), 
ADDRIP		VARCHAR(64),  
LASTLOGIN	VARCHAR(32),
LASTMODIF	VARCHAR(32),
DELETED 	CHAR(1), 
PRIMARY KEY (IDS)
)ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci AUTO_INCREMENT=1;
 
CREATE TABLE IF NOT EXISTS OUSHITEACHER (
IDS INTEGER  NOT NULL AUTO_INCREMENT, 
NAMES 		VARCHAR(32), 
TEACHERID	INTEGER, 
TITLE 		VARCHAR(64), 
JIAOCAI 	VARCHAR(64), 
TYPES 		VARCHAR(64), 
DATES		VARCHAR(32), 
CONTENT		VARCHAR(1024), 
FILES		VARCHAR(128),  
LASTMODIF	VARCHAR(32),
REMARKES	VARCHAR(1024),
DELETED 	CHAR(1), 
PRIMARY KEY (IDS)
)ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci AUTO_INCREMENT=1;
 
CREATE TABLE IF NOT EXISTS jlpage (
IDS INTEGER  NOT NULL AUTO_INCREMENT, 
TITLE 		VARCHAR(512), 
FTITLE 		VARCHAR(512),  
STITLE 		VARCHAR(512), 
FSTITLE 	VARCHAR(512), 
CONTENTS	TEXT, 
FCONTENTS	TEXT, 
LASTMODIF	VARCHAR(32),
TYPES		INTEGER,
PHOTOC		VARCHAR(128),
PHOTOF		VARCHAR(128),
POSITION	INTEGER, 
PHOTOS		VARCHAR(1024),
SPHOTOS		VARCHAR(1024),
REMARKC		VARCHAR(1024),
REMARKF		VARCHAR(1024),
DELETED 	CHAR(1), 
PRIMARY KEY (IDS)
)ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS starticles (
IDS INTEGER NOT NULL AUTO_INCREMENT,
TITLE 		VARCHAR(512), 
FTITLE 		VARCHAR(512), 
STUDENT 	VARCHAR(64), 
CLASSES		VARCHAR(64), 
STITLE		VARCHAR(512), 
FSTITLE		VARCHAR(512), 
DATES		VARCHAR(32),
CONTENTS	TEXT,
FCONTENTS	TEXT,
TYPES		CHAR(1), 
LASTMODIF	VARCHAR(32),
DELETED 	CHAR(1), 
PRIMARY KEY (IDS)
)ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci AUTO_INCREMENT=1;


