<?php
$HGNEWS1 = array(
"2013孔子学院网络春晚", 
array("huigu/huigu.jpg", "2013孔子学院网络春晚", "youtube", "2014年2月10日"),
array(
		"癸巳蛇年2013“孔子学院网络春晚”由国家汉办/孔子学院总部主办、网络孔子学院承办。这次网络春晚是孔子学院举办的第二届，从2012年11月起面向全球的孔子学院和孔子课堂征集节目，共收到了来自46个国家、112所孔子学院或课堂的500多个节目。", 
		"", 
		"欧洲时报孔子课堂学生表演的舞蹈《蝶舞》和《小龙人》获优秀节目奖。同时，欧洲时报孔子课堂在全球众多竞争者中脱颖而出，获得最佳组织奖。", 
		""),
array(
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：儿歌《新年好》", "《新年好》", "", "zuZgU-T9sA4", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：儿歌《两只老虎》 ", "《两只老虎》", " ", "pgFTIs6gO-g", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：儿歌《我爱我的家》 ", "《我爱我的家》", " ", "sGZJGi_DxYo", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：儿歌《咏鹅》 ", "《咏鹅》", " ", "Gs6ry2Vlxtg", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：儿歌《春晓》 ", "《春晓》", " ", "Y-SfyLBoeGA", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：武术《长穗剑》 ", "《长穗剑》", " ", "A9nSHTIPAAM", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：武术《单扇》 ", "《单扇》", " ", "j07OL9WXhBA", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：武术《木兰剑》 ", "《木兰剑》", " ", "irJgKY-J-Ik", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：舞蹈《蝶舞》", "《蝶舞》", " ", "TD6BVq_ZLC0", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：舞蹈《水果歌》 ", "《水果歌》", " ", "jtdP2pjlpjk", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：舞蹈《在树上唱歌》 ", "《在树上唱歌》", " ", "i-rMvoQQLn8", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：舞蹈《种太阳》 ", "《种太阳》", " ", "UY_AWqcnv68", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：舞蹈《木兰辞》", "《木兰辞》", " ", "2y36N72ZMbc", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：舞蹈《小龙人》 ", "《小龙人》", " ", "JKoRaq6RxxI", ""),
),

// version francais
array(
"Gala de la Fête du Printemps 2013", 
array("huigu/huigu.jpg", "Gala de la Fête du Printemps 2013", "youtube", "10/02/2014"),
array(
		"Le Gala de Printemps en ligne des Instituts Confucius 2013 est le deuxième évènement de ce type organisé par Hanban/Siège de l’Institut Confucius. Plus de 500 vidéos des 112 Instituts/Classes Confucius de 46 pays ont été collectées. Parmi elles, &quot;Danse de Papillon&quot; et &quot;Petit Dragon&quot; de notre Classe Confucius ont gagné le Prix de la Meilleure Interprétation. Nous avons également obtenu le Prix de l'Organisation.", 
		""),
array(
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：儿歌《新年好》", "《新年好》", "", "zuZgU-T9sA4", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：儿歌《两只老虎》 ", "《两只老虎》", " ", "pgFTIs6gO-g", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：儿歌《我爱我的家》 ", "《我爱我的家》", " ", "sGZJGi_DxYo", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：儿歌《咏鹅》 ", "《咏鹅》", " ", "Gs6ry2Vlxtg", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：儿歌《春晓》 ", "《春晓》", " ", "Y-SfyLBoeGA", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：武术《长穗剑》 ", "《长穗剑》", " ", "A9nSHTIPAAM", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：武术《单扇》 ", "《单扇》", " ", "j07OL9WXhBA", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：武术《木兰剑》 ", "《木兰剑》", " ", "irJgKY-J-Ik", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：舞蹈《蝶舞》", "《蝶舞》", " ", "TD6BVq_ZLC0", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：舞蹈《水果歌》 ", "《水果歌》", " ", "jtdP2pjlpjk", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：舞蹈《在树上唱歌》 ", "《在树上唱歌》", " ", "i-rMvoQQLn8", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：舞蹈《种太阳》 ", "《种太阳》", " ", "UY_AWqcnv68", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：舞蹈《木兰辞》", "《木兰辞》", " ", "2y36N72ZMbc", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：舞蹈《小龙人》 ", "《小龙人》", " ", "JKoRaq6RxxI", ""),
),
),
1
);

?>
