<?php
$HGNEWS2 = array(
"2017金鸡迎春嘉年华", 
array("huigu/LED.jpg", "", "", ""),
array(
		"欧洲时报文化中心再度联手欧洲时报旗下法语网站Chine-info，于2017年1月21、22日为中法朋友献上一场喜气洋洋的新春活动 —— 2017年“金鸡迎春嘉年华”。", 
		"", 
		"", 
		"在欧洲时报文化中心，过精彩纷呈、开心愉悦的中国年！", 
		""),
array(
	array("儿歌《新年好》", "《新年好》", "", "zuZgU-T9sA4", ""),
),

// version francais
array(
"La Fête du Printemps - Nouvel An chinois ", 
array("huigu/LED.jpg", "La Fête du Printemps - Nouvel An chinois ", "", ""),
array(
		"Suite au succès de l'édition de 2016, le Centre Culturel les Amis de Nouvelles d'Europe organise de nouveau, en partenariat avec Chine-info.com, la Fête du Printemps le week-end du 21 et 22 janvier 2017, à l'occasion du Nouvel an chinois qui débutera le 28 janvier, accueillant l'année du Coq de feu.", 
		"", 
		"Un week-end riche en activités ! ", 
		""),
array(
	array("儿歌《新年好》", "《新年好》", "", "zuZgU-T9sA4", ""),
),
),
1
);

?>
