<?php
 $JL_NEWS5 = array(
"中欧华文传媒高峰对话在欧洲时报文化中心新址举行",
"2013年12月15日，由欧洲华文传媒协会主办、欧洲时报承办的“中欧华文传媒高峰对话”",
"",
"2013年12月15日",
array(
),
array(	"2013年12月15日，由欧洲华文传媒协会主办、欧洲时报承办的“中欧华文传媒高峰对话”在法国巴黎欧洲时报文化中心新址隆重开幕。来自法国、英国、德国、西班牙、葡萄牙，以及匈牙利等欧洲十多家华文媒体的社长、总编及中国驻法主要媒体负责人齐聚一堂，与到访法国的中国国务院侨务办公室何亚非副主任进行了对话与交流。",
	"何亚非副主任与大家探讨了在十八届三中全会以后海外华文媒体如何提高水平，希望华文媒体强调扩大对外文化交流，加强国际传播能力和对外话语体系建设，讲好“中国故事”，推动中华文化走向世界。",
	"出席高峰对话的法国历史学家及政治专家分别就自己关心的方面提出了问题，何亚非副主任在回答问题的同时，也给法国友人深入准确地解读了国家相关政策。",
	""),
array(
"L’inauguration du symposium en média entre la Chine et l’UE",
"",
"",
"",
array(
),
array(	"<IMG SRC='".$PHOTO_PATH."meeting/meeting.jpg' width=500>",
	"Le symposium en média entre la Chine et l’UE, organisé par l’Association des Médias chinois d’outre-mer en Europe, entrepris par GUANG HUA MEDIA, a été inauguré le 15 décembre 2013. Les directeurs et les chefs de rédactions des entreprises de presse en langue chinoise éditant en Europe (la France, la Grande-Bretagne, l’Allemagne, l’Espagne, le Portugal, la Hongrie…) se sont réunis au le Centre culturel de Nouvelles d’Europe et ils ont eu un dialogue chaleureux avec Monsieur HE Yafei, le directeur adjoint du bureau des affaires des Chinois d’outre-mer.",
	"<IMG SRC='".$PHOTO_PATH."meeting/meeting2.jpg' width=500>",
	"Monsieur HE Yafei et tous les participants ont étudié les moyens d’améliorer la presse en chinois à l’étranger après la troisième session plénière du 18ème comité central du Parti Communiste chinois.",
	"<IMG SRC='".$PHOTO_PATH."meeting/meeting3.jpg' width=500>",
	"En répondant aux questions posées par des historiens et des experts français en politique, Monsieur HE a donné ders précisions pertinentes sur la politique chinoise."),
)
);
?>