<?php
 $JL_NEWS1 = array(
"国侨办马儒沛副主任来访 ",
"由中国国务院侨办副主任马儒沛率领的侨务考察团2月9日上午走访了刚刚投入使用不久的欧洲时报文化中心。",
"",
"2014年2月10日",
array(
),
array(	"由中国国务院侨办副主任马儒沛率领的侨务考察团2月9日上午走访了刚刚投入使用不久的欧洲时报文化中心。",
	"当天，马儒沛副主任一行在欧洲时报社长张晓贝，常务副社长钟诚，副社长、文化中心主任陈晓燕，中国驻法使馆领事部一秘李京生的陪同下参观了欧洲时报文化中心的设施，详细了解了其性能、功用以及开展的活动。马儒沛副主任对文化中心的设施十分赞赏。他指出，文化中心对于促进两国文化交流、传承中华文化作用非常大，要把它办好，利用好。",
	"<IMG SRC='".$PHOTO_PATH."top/topma2.jpg' width=500>",
	"陈晓燕副社长向侨务考察团介绍了欧洲时报中文学校学员的情况以及法国华文教育协会的运行情况。马儒沛副主任充分肯定了旅法侨胞为开展华文教育做出了不可磨灭的贡献，并指出华文教育是文化传承的最重要的形式，在为侨胞“固根、壮魂、圆梦”方面的作用功不可没，要积极创造条件推动华文教育的开展。",
	"马儒沛副主任希望文化中心在开展活动，增强侨胞的文化归属感和自豪感的同时，也通过展览、座谈会、讲座等多形式、多层次的活动，让法国观众更真切了解到中国博大精深、源远流长的文化传承，了解中国当下的发展变化、中国人的精神风貌，为法国多元文化发展做出贡献。他相信，随着中法两国关系的不断加强，文化中心的功能和作用也会不断加强。",
	"",
	"<b>相关视频 ：</b> <a href=http://video.oushinet.com/html/channel2/201402/1669.html target=_blank>马儒沛先生谈欧洲时报文化中心</a>",
	""),
array(
"La visite de M. MA Rupei, le directeur adjoint du bureau des affaires des Chinois d’outre-mer.",
"",
"",
"",
array(
),
array(	"Le 9 février au matin, un groupe d’investigation, dirigé par Monsieur MA Rupei, directeur adjoint du bureau des affaires des Chinois d’outre-mer, a visité le nouveau Centre culturel de Nouvelles d’Europe.",
	"<IMG SRC='".$PHOTO_PATH."top/topma2.jpg' width=500>",
	"Monsieur MA Rupei et son groupe ont visité le bâtiment et regardé la présentation des activités proposées par l’Association des Amis de Nouvelles d’Europe. Monsieur MA Rupei a apprécié les nouvelles installations et il a souligné que le Centre culturel joue un rôle très important dans la promotion des échanges culturels chinois. ",
	""),
)
);
?>