<?php
 $JL_NEWS17 = array(
"中国《汉字》国际巡展将在法国巴黎开幕",
"中国《汉字》国际巡展法国巴黎展在欧洲时报文化中心隆重开幕。",
"",
"2014年6月13日",
array(
),
array(	"中国《汉字》国际巡展法国巴黎展将于2014年6月21日16点30分在欧洲时报文化中心隆重开幕。",
	"<IMG src='".$PHOTO_PATH."jiaoliunews/wenzi600x450.jpg' width=500>",
	"汉字是世界文明史上的一个伟大创举，也是全人类的宝贵财富。这次《汉字》国际巡展巴黎展以图片形式进行。主要介绍汉字的起源与发展，汉字的研究与传播以及艺术与意趣。 《汉字》国际巡展以中国文字发展史为主线，生动全面地展示汉字的起源、发展、演变历程以及与汉字相关的各种艺术形式。",
	"欢迎大家前来参观，以便进一步了解中国汉字，了解中华文明。",
	"",
	"<b>展览时间： </b> 2014年6月20日14点 - 6月22日17点",
	"<b>开放时间: </b> 10:00 - 12:30 ; 13:30 - 17:30",
	"<b>地点： </b> 48-50 Rue Benoît Malon，94250 Gentilly",
	""),
array(
"Exposition de l’Ecriture chinoise France",
"l'exposition «Écriture chinoise» aura lieu le 21 juin 2014",
"",
"13 juin 2014",
array(
),
array(	"<IMG src='".$PHOTO_PATH."jiaoliunews/wenzi600x450.jpg' width=500>",
	"Pour célébrer le 50è anniversaire de l’établissement des relations diplomatiques entre la France et la République populaire de Chine, nous avons le plaisir de vous inviter au vernissage de l'exposition «Écriture chinoise» qui aura lieu le 21 juin 2014 à 16h30 au siège de l'Association des Amis de Nouvelles d'Europe.  ",
	"Pour l’humanité, la naissance de l’écriture marque le passage de la barbarie à la civilisation. L’écriture chinoise cristallise le génie créatif de la Chine : par l’originalité de sa forme carrée ; par sa capacité à exprimer à la fois le son, la forme et le sens ; par la puissance de sa diffusion à travers le temps et l’espace. L’écriture est la matrice de la civilisation chinoise, le vecteur de sa culture ; elle est le ciment de la nation, le messager qui promeut l’amitié de la Chine avec le monde. De nos jours, comptant le plus d’utilisateurs au monde, elle est adoptée par l’O.N.U. en tant que l’une de ses six langues de travail.",
	"",
	"<b>Organisateurs: </b>Association du Peuple chinois pour l'Amitié avec l'Étranger Musée national de l'écriture chinoise ; Association Franco-chinoise d’Echanges Economiques Culturels et Educatifs ",
	"<b>Lieu de l'exposition: </b>Siège de l'Association des Amis de Nouvelles d'Europe ",
	"<span class='spanarticle'>48-50 rue Benoît Malon 94250 GENTILLY</span>",
	"",
	"<div class='note_title'><h1>Venez nombreux!</h1></div>",
	""),
)
);
?>