<?php
 $JL_NEWS18 = array(
"开平碉楼图片展",
"开平碉楼已被列入《世界遗产名录》，成为我国的又一处世界遗产。",
"",
"2014年6月15日",
array(
),
array(	"广东省开平市是著名的侨乡，侨胞在家乡建筑的楼群像碉堡一样坚固。开平碉楼最迟于明代后期（16世纪）已经产生，到19世纪末20世纪初发展成为表现华侨历史与文化传统的一种独具特色的群体建筑形象。这些建筑群造型别致，种类繁多，具有中西合璧的民居特色，以古希腊、古罗马及伊斯兰等多种建筑风格为主要表现形式, 融合了中国传统乡村建筑文化与西北方建筑文化的独特建筑艺术。",
	"<IMG width=500 src='".$PHOTO_PATH."jiaoliunews/diaolou600x450.jpg'>",
	"开平碉楼已被列入《世界遗产名录》，成为我国的又一处世界遗产。",
	"<IMG width=500 src='".$PHOTO_PATH."jiaoliunews/diaolou600x450x2.jpg'>",
	"此次开平碉楼图片展于2014年6月14日到6月19日在欧洲时报文化中心举办，欢迎各界朋友前来观赏。",
	"",
	"<b>展览时间： </b> 2014年6月14日 - 6月19日",
	"<b>开放时间: </b>  10:00 - 12:30 ; 13:30 - 17:30",
	"<b>地点： </b> 48-50 Rue Benoît Malon，94250 Gentilly",
	""),
array(
"Exposition des bâtiments de Kaiping",
"les grands bâtiments ont été inscrits sur la liste du patrimoine mondial de l'UNESCO",
"",
"15 juin 2014",
array(
),
array(	"Dans le comté de Kaiping (province du Guangdong) les grands bâtiments à plusieurs étages ont été inscrits sur la liste du patrimoine mondial de l'UNESCO en 2007 et se classent trente-cinquième site du patrimoine mondial pour la Chine. Ces anciens bâtiments ont été construits principalement à la fin de l'empire des Qing et au début du 20ème siècle.",
	"<IMG width=500 src='".$PHOTO_PATH."jiaoliunews/diaolou600x450.jpg'>",
	"Kaiping étant un secteur d'émigration vers l'étranger, beaucoup de membres de la diaspora chinoise y ont leurs racines ; ils ont influencé l'architecture de la région, dont les diaolou, en y ajoutant des détails étrangers.",
	"<IMG width=500 src='".$PHOTO_PATH."jiaoliunews/diaolou600x450x2.jpg'>",
	"Venez découvrir des bâtiments de Kaiping grâce à l’Exposition des photos au Centre culturel de Nouvelles d’Europe. ",
	"",
	"<b>Date ： </b> du samedi 14 au jeudi 19 juin 2014",
	"<b>Lieu ： </b>Centre culturel de Nouvelles d’Europe, 50 Rue Benoit Malon 94250 GENTILLY",
	"<b>Transport ： </b> RER B GENTILLY",
	""),
)
);
?>