<?php
 $JL_NEWS4 = array(
"欧洲时报文化中心新址举行揭牌仪式",
"2013年12月15日上午，位于 Gentilly 市全新的欧洲时报文化中心打开了大门，",
"",
"2013年12月16日",
array(
),
array(	"2013年12月15日上午，位于Gentilly市全新的欧洲时报文化中心打开了大门，举行了揭牌仪式，迎来了第一批嘉宾。中国国务院侨办何亚非副主任，中国驻法使馆邓励临时代办，Gentilly市市长TORDJMAN Patricia，欧洲时报传媒集团总裁张晓贝为中心揭牌。",
	"揭牌仪式由欧洲时报常务副社长钟诚主持。张晓贝社长在致辞中回顾了文化中心的发展，并为大家描绘了新址新气象，展望了美好的未来。邓励代办代表中国驻法使馆祝贺欧洲时报文化中心新址落成启用，Gentilly 市市长 TORDJMAN 女士代表市政府欢迎欧洲时报文化新址落户该市。揭牌仪式上，国务院侨办宣传司司长郭锦玲代表国侨办向欧洲时报文化中心赠送了纪念品。欧洲时报副社长、文化中心主任陈晓燕，前总编辑梁源法代表中心接收了来自祖国的美好祝愿。",
	"何亚非副主任对欧洲时报文化中心寄予了厚望。他希望文化中心在今后不但打开中法文化交流的新窗口，更为法中文化交流和促进两国人民之间的友谊贡献更大的力量。",
	"揭牌仪式后，何亚非副主任在张晓贝总裁、陈晓燕副社长陪同下，参观了中心，与中文课的师生进行了交流，并观看了欧洲时报丝绸之路合唱团的排练，亲切与合唱团成员交谈。",
	""),
array(
"L’inauguration du Centre culturel de Nouvelles d’Europe sur le nouveau site",
"",
"",
"",
array(
),
array(	"<IMG src='".$PHOTO_PATH."school/top_newschool.jpg' width=500>",
	"L’inauguration du Centre culturel de Nouvelles d’Europe sur le nouveau site à Gentilly a eu lieu le 15 décembre au matin. Monsieur HE Yafei (le directeur adjoint du bureau des affaires des Chinois d’outre-mer), Monsieur DENG Li (le délégué de l’ambassade chinoise), Madame TORDJMAN Patricia (la maire de Gentilly), et Monsieur ZHANG Xiaobei (le président de GUANG HUA MEDIA) ont dévoilé la plaque du Centre et en ont annoncé l’ouverture.",
	"<IMG src='".$PHOTO_PATH."school/top_deng.jpg' width=500>",
	"<IMG src='".$PHOTO_PATH."school/top_zhang.jpg' width=500> ",
	"<IMG src='".$PHOTO_PATH."school/top_maire.jpg' width=500>"),
)
);
?>