<?php
 $JL_NEWS29 = array(
"迎羊年华法联欢会",
"迎羊年华法联欢会",
"",
"2015年1月24日",
array(
),
array(	"中国春节悄悄地走近了。",
	"春节是中国人最隆重的传统佳节。每年春节期间，欧洲时报文化中心都会组织一场华法联欢会，旅法的华人与法国友人一起共度新春佳节。今年，文化中心还如往年一样，敞开大门，欢迎Gentilly的市民来到中心共享中国年。",
	"春节联欢将于2015年2月15日下午2点开始，具体日程安排敬请期待。",
	"<IMG src='".$PHOTO_PATH."jiaoliunews/yangnian.jpg' width=500> ",
	""),
array(
"Préparation du Gala du Nouvel An chinois 2015",
"Le gala du Nouvel An chinois 2015",
"",
"le 24 Jan. 2015",
array(
),
array(	"Le Nouvel An chinois s’approche à grands pas.",
	"La fête du printemps est la fête traditionnelle la plus importante pour tous les Chinois. L’Association des Amis de Nouvelles d’Europe organise régulièrement un gala pour la célébrer. Cette année, ce gala aura lieu le 15 février 2015 après midi vers 2 heures au site à Gentilly pour fêter le Nouvel An chinois de la Chèvre. Les habitants de Gentilly seront tous conviés chaleureusement à partager nos réjouissances.Pour plus d'informations, nous vous remercions de suivre les prochains messages.",
	"<IMG src='".$PHOTO_PATH."jiaoliunews/yangnian.jpg' width=500> ",
	""),
)
);
?>