<?php
 $JL_NEWS2 = array(
"欧洲时报文化中心筹备迎马年华法联欢会 ",
"新年的钟声还在耳边回荡，空气中仍然洋溢着圣诞节的气息，中国春节悄悄地走近了。",
"",
"2014年1月6日",
array(
),
array(	"新年的钟声还在耳边回荡，空气中仍然洋溢着圣诞节的气息，中国春节悄悄地走近了。",
	"春节是中国人最隆重的传统佳节。每年春节期间，欧洲时报文化中心都会组织一场华法联欢会，旅法的华人与法国友人一起共度新春佳节。今年，刚刚乔迁新址的文化中心敞开大门，欢迎Gentilly的市民来到中心共享中国年，为Gentilly添上一股浓浓的中国年味。",
	"为了这次迎马年华法联欢会，文化中心中文学校和各群众活动班级都做了精心准备。届时不但会有少儿的舞蹈和武术，合唱团、形体塑身班、木兰拳班等都将呈上精彩节目。文化中心的老朋友，法国退休教师协会中文班的学员们也会在联欢会上一显身手。",
	"<IMG SRC='".$PHOTO_PATH."top/programmeweb.jpg' width=500>",
	"佳节之际，佳肴自然是不可或缺。文化中心各群众活动班级的师生将带来家乡风味，准备一场多元化的国际美食盛筵。同时，在文化中心的展厅里将举办摄影展，下午的舞会将把此次联欢活动推向高潮。",
	""),
array(
"Préparation du gala pour la nouvelle année du Cheval",
"",
"",
"",
array(
),
array(	"Le Nouvel An chinois s’approche à grands pas alors que l’ambiance de Noël n’est pas encore partie.",
	"La fête du printemps est la fête traditionnelle la plus importante pour tous les Chinois. L’Association des Amis de Nouvelles d’Europe organise régulièrement un gala pour la célébrer. Cette année, ce gala aura lieu dans les nouveaux locaux. Les habitants de Gentilly seront tous conviés chaleureusement à partager nos réjouissances. ",
	"<IMG SRC='".$PHOTO_PATH."top/programmeweb.jpg' width=500>",
	"Le gala inclura un spectacle (danses et kung-fu d’enfants, mulan, chants et danses chinoises), un buffet de spécialités chinoises et asiatiques, une exposition de photos et un bal. L’Association est prête pour fêter la nouvelle année avec les nouveaux voisins et les anciens amis.",
	""),
)
);
?>