<?php
 $JL_NEWS9 = array(
"《心中的上海——上海名家水墨画展》",
"为庆祝中法建交50周年，同时为了配合2014年巴黎图书沙龙上海担任主宾城市活动",
"",
"2014年3月20日",
array(
),
array(	"<IMG src='".$PHOTO_PATH."jiaoliunews/vernissage600-480.jpg' width=500>",
	"<IMG src='".$PHOTO_PATH."jiaoliunews/exposhanghai.jpg' width=500>",
	"为庆祝中法建交50周年，同时为了配合2014年巴黎图书沙龙上海担任主宾城市活动，上海市新闻出版局将在欧洲时报文化中心举行《心中的上海——上海名家水墨画展》。",
	"参展的52件作品出自于43位不同画家之手，质量高、作品优质、主题鲜明，代表了上海水墨画的最高水平，可观赏性极高。非常欢迎对中国文化，尤其是对中国画感兴趣的中法朋友前来观展。",
	"<IMG src='".$PHOTO_PATH."jiaoliunews/exposhanghai600-480.jpg' width=500>",
	""),
array(
"«Shanghai dans mon cœur» – exposition de peintures",
" ",
"",
"20 mars 2014",
array(
),
array(	"«Shanghai dans mon cœur» – exposition de peintures à l’encre de Chine réalisées par les artistes réputés de Shanghai",
	"<IMG src='".$PHOTO_PATH."jiaoliunews/vernissage600-480.jpg' width=500>",
	"<IMG src='".$PHOTO_PATH."jiaoliunews/exposhanghai.jpg' width=500>",
	"Une exposition de peintures à l’encre de Chine sur le thème «Shanghai dans mon cœur» a lieu au site de l’Association des Amis de Nouvelles d’Europe à Gentilly. Cette exposition est organisée par le bureau de la presse et de l’édition de Shanghai, dans le but de célébrer le 50ème anniversaire de l’établissement des relations diplomatiques sino-françaises, et répondant ainsi à l’honneur fait à Shanghai d’être invité comme la ville d’honneur de la 34ème édition du Salon du Livre.  ",
	"52 œuvres de qualité réalisées par 43 artistes différents qui représentent le plus haut niveau de peinture à l’encre de Chine de Shanghai. Tous les amis qui sont intéressés par la culture chinoise, particulièrement la peinture, sont conviés à venir à l’exposition. ",
	""),
)
);
?>