<?php
 $JL_NEWS7 = array(
"《活佛父子镜头下的西藏今昔》摄影图片展开展",
"2月16日下午，《活佛父子镜头下的西藏今昔》摄影图片展在欧洲时报文化中心展出。",
"",
"2014年2月20日",
array(
),
array(	"<IMG src='".$PHOTO_PATH."jiaoliunews/expo600-480.jpg' width=500>",
	"2月16日下午，《活佛父子镜头下的西藏今昔》摄影图片展在欧洲时报文化中心展出。",
	"这次《活佛父子镜头下的西藏今昔》摄影图片展所展出的图片均来自于西藏第一位摄影家活佛十世德木•丹增加措及其子——西藏摄影家协会主席德木•旺久多吉，向观展的人们讲述着新旧西藏社会变迁的故事。十世德木活佛是清王朝册封的西藏四大活佛之一，也堪称西藏第一位摄影家。他于青年时因缘际会接触到相机，遂拍下数十万张底片，以细腻的触感记录下旧西藏社会的点滴。父子两代以影像衔接记录了20世纪乃至21世纪的西藏。摄影展展出作品前后跨度80多年，透过父子俩的镜头，让人们更能认识西藏的历史、现实与变化。",
	"<IMG src='".$PHOTO_PATH."jiaoliunews/expo2.600-480.jpg' width=500>",
	"应邀前来参加文化中心迎马年法华联欢会的Gentilly市政府副市长Michèle Cosnard女士，在欧洲时报副社长、文化中心主任陈晓燕女士的陪同下，观看了摄影图片展。Cosnard副市长表示，图片展展出的这些珍贵图片，是当地人民了解西藏的一个窗口，有助于加深Gentilly市市民对中国，特别是对西藏的深入了解，为推动两国民间交往有着积极的作用。",
	"<IMG src='".$PHOTO_PATH."jiaoliunews/expo1.600-480.jpg' width=500>",
	"摄影图片展将展出至3月10日，欢迎大家前往观看。",
	"<div align=right>（本页图片友情提供：杨宁生）        </div>",
	""),
array(
"Le présent et le passé du Tibet sous la caméra de Bouddha Vivant et son fils",
" ",
"",
"20 février 2014",
array(
),
array(	"<IMG src='".$PHOTO_PATH."jiaoliunews/expo600-480.jpg' width=500>",
	"L’exposition des photos ‘Le présent et le passé du Tibet sous la caméra de Bouddha Vivant et son fils’ est ouverte le 16 février après midi. ",
	"Toutes les photos exposées sont les travaux du premier photographe tibétain – Bouddha Vivant Demu X – et de son fils, le président de l’Association des Photographes Tibétains. Par leurs photos, ils ont raconté plus de 80 ans de l’histoire du Tibet du 20ème au 21ème siècle.",
	"<IMG src='".$PHOTO_PATH."jiaoliunews/expo2.600-480.jpg' width=500>",
	"Conviée pour le gala du Nouvel An chinois, Mme Michèle COSNARD, maire adjointe de Gentilly, déclare que l’exposition de ces images précieuses ouvre, pour le visiteur, une fenêtre à la compréhension de la vie locale tibétaine. Cette exposition permet aux résidents de Gentilly de mieux connaître la Chine, et particulièrement le Tibet. ",
	"<IMG src='".$PHOTO_PATH."jiaoliunews/expo1.600-480.jpg' width=500>",
	"Les photos seront exposées jusqu’au 10 mars. Entrée libre.",
	""),
)
);
?>