<?php
 $JL_NEWS3 = array(
"《两岸四地摄影家合拍中国大地24小时十年回顾》摄影展",
"欧洲时报文化中心新址开张好戏连台！揭牌仪式当天，全新的展厅迎来了处女秀 ",
"",
"2013年12月15日",
array(
),
array(	"欧洲时报文化中心新址开张好戏连台！揭牌仪式当天，全新的展厅迎来了处女秀：《两岸四地摄影家合拍中国大地24小时十年回顾》摄影展。",
	"自2002年6月起，两岸四地的摄影家们就开始携手在中华大地上展开合拍活动。首站选在了正式开放民间交流刚刚五年的台湾，摄影家们用镜头随机捕捉台湾人民寻常生活的一天。随后，两岸摄影家们扬起了“合拍中国大地24小时的旗帜”，相继辗转北京、贵州、澳门、西藏、山东、浙江、上海、吉林、云南、青海和新疆等十多个省份，参加的摄影家超过百人。",
	"十年来，他们通过两岸镜头的真诚对话，不仅饱览中华大地的壮丽河山，捕捉大江南北灿烂民族文化的闪光点，而且将目光聚集到大街小巷寻常百姓家的男女老幼，呼吸到城市乡村真实的生活气息，坚持表现中国人寻常生活一天的初衷。",
	"合拍活动，让两岸摄影家共同见证了历史，记录了隐藏在光影色彩之中的美好画面。从某种意义上说，他们一起创造了美。",
	""),
array(
"Exposition de 10 années de photos sur le thème, «Une journée en Chine»",
"",
"",
"",
array(
),
array(	"Exposition de 10 années de photos sur le thème, «Une journée en Chine» (travaux réalisés par des photographes de la Chine continentale, de Taiwan, de Macao et de Hongkong)",
	"<IMG src='".$PHOTO_PATH."expo/expo1.jpg' width=500>",
	"Le jour même de l’inauguration du Centre culturel de Nouvelles d’Europe, la première exposition dans la galerie a été ouvert au public.",
	"<IMG src='".$PHOTO_PATH."expo/expo2.jpg' width=500>",
	"Depuis juin 2002, des photographes de la Chine continentale, de Taiwan, de Macao et de Hongkong ont commencé à travailler ensemble dans le but de collecter des images de la Chine. Le premier lieu choisi a été Taiwan, qui avait ouvert les échanges non gouvernementaux avec la Chine continentale à peine cinq ans auparavant. Les photographes ont saisi des Taïwanais dans leur vie quotidienne. Par la suite, une centaine de photographes se sont rendus dans plus d’une douzaine de provinces, dont Beijing, Guizhou, le Tibet, Shandong, Zhejiang, Shanghai, Macao, Jilin, Yunnan, Qingdao, Xinjiang",
	"<IMG src='".$PHOTO_PATH."expo/expo3.jpg' width=500>",
	"<IMG src='".$PHOTO_PATH."expo/expo4.jpg' width=500>",
	"À travers leurs objectifs, les photographes donnent à voir non seulement les paysages majestueux, la culture spectaculaire, mais aussi la vie quotidienne des gens ordinaires.",
	"<IMG src='".$PHOTO_PATH."expo/expo5.jpg' width=500>"),
)
);
?>