<?php
 $JL_NEWS15 = array(
"铭记历史 拥抱和平",
"欧洲时报文化中心将举行反法西斯战争胜利纪念活动。",
"",
"2014年5月31日",
array(
),
array(	"<IMG src='".$PHOTO_PATH."wenyunews/plaque600.jpg' width=500>",
	"2014年6月1日，值全法隆重纪念盟军诺曼底登陆70周年之际，欧洲时报文化中心将举行反法西斯战争胜利纪念活动。活动中将举行揭牌仪式，纪念二战期间9位被捕投入纳粹死亡营的死难者。他们当年工作的桑德斯工厂旧址即是今日的欧洲时报文化中心。一块用中法文撰写的铭牌将安置在欧洲时报文化中心内，一方面表达对逝者的敬意，另一方面，也希望下一代记住战争的苦难，希望悲剧再也不要重演。",
	"Gentilly市市长Mme Tordjman 和欧洲时报张晓贝社长将致辞，死难者后代和当地有关活动的负责人也将出席活动。欧洲时报中文学校的学生将向纪念牌鲜花。",
	""),
array(
"Une Cérémonie Commémorative",
"Centre culturel de Nouvelles d’Europe va organiser une cérémonie commémorative",
"",
"31 mai 2014",
array(
),
array(	"<IMG src='".$PHOTO_PATH."wenyunews/plaque600.jpg' width=500>",
	"Le 1er juin 2014, pour le 70e anniversaire du Débarquement, le Centre culturel de Nouvelles d’Europe va organiser une cérémonie commémorative pour poser une plaque bilingue en français et en chinois à l’intérieur du Centre culturel en hommage aux martyrs de l’usine Sanders déportés en 1942. Le Centre culturel occupe aujourd’hui les locaux de l’ancienne usine Sanders, qui fabriquait des caisses enregistreuses sous licence américaine.",
	"Cette cérémonie se fera en présence du maire, Mme Patricia Tordjman, de deux descendants des déportés et de représentant de l’Association Mémoire vive des convois des 45 000 et 31 000 d’Auschwitz-Birkenau. Des fleurs seront déposées en hommage par des élèves de l’Ecole chinoise de Nouvelles d’Europe.",
	""),
)
);
?>