<?php
 $JL_NEWS13 = array(
"文化中国•名家讲坛",
"湖南省外事侨务办公室承办的“文化中国*名家讲坛”团将于5月27日在欧洲时报文化中心举办讲座。",
"",
"2014年5月17日",
array(
),
array(	"受国务院侨务办公室委托，湖南省外事侨务办公室承办的“文化中国*名家讲坛”团将于5月27日下午14点半在欧洲时报文化中心举办讲座。",
	"<IMG SRC='".$PHOTO_PATH."jiaoliunews/jiangtan600x450.jpg' width=500>",
	"本次名家讲坛由湖南省委宣传部原副部长、第六届省社科联主席、电视剧《雍正王朝》总监制郑佳明和省作家协会主席、《曾国藩》作者唐浩明两位专家担任讲坛主讲嘉宾。郑佳明教授的讲座主题为：戏里戏外说雍正，唐浩明教授将就曾国藩的家庭教育与观众进行探讨。",
	"欢迎华人华侨同胞前来参加讲座。",
	""),
array(
"Culture chinoise • Conférence d’Experts",
"La conférence comportera deux thèmes: «Dynastie Yongzheng» et l’éducation familiale de Zeng Guofan",
"",
"17 mai 2014",
array(
),
array(	"<IMG SRC='".$PHOTO_PATH."jiaoliunews/jiangtan600x450.jpg' width=500>",
	"La conférence comportera deux thèmes :",
	" — un thème sur la «Dynastie Yongzheng», célèbre série télévisée de l’année 1998, animée par le Directeur de la série M. ZHENG Jiaming",
	" — un thème sur l’éducation familiale de ZENG Guofan, par le Professeur TANG Haoming. ",
	"Conférence en Chinois",
	"<b>Conférencier : </b>M. ZHENG Jiaming et M. TANG Haoming",
	"<b>Date : </b>Mardi 27 mai 2014  14h-17h",
	"<b>Lieu : </b>Centre Culturel de Nouvelles d’Europe: 48-50，Rue Benoît Malon, 94250 Gentilly",
	"<div class=note_title><h1>Venez nombreux !</h1></div>",
	"",
	""),
)
);
?>