<?php
 $JL_NEWS14 = array(
"«行走大巴黎»新书推介兼9年森林徒步活动投映座谈会",
"由旅法文化人张汉钧、旅法作家钟敏合著，重庆大学出版社出版的«行走大巴黎»已在中国面市。",
"",
"2014年5月17日",
array(
),
array(	"由旅法文化人张汉钧、旅法作家钟敏合著，重庆大学出版社出版的«行走大巴黎»已在中国面市。此书全彩印刷，图片精美，文字优雅，人文与自然知识丰富，趣味横生。有国内外学者评称“这是一本能提高心智、增进健康的好书。”更有网上介绍“是一本底蕴深厚的海外旅游图书。”",
	"<IMG SRC='".$PHOTO_PATH."jiaoliunews/rando600x450.jpg' width=500>",
	"<b>座谈会时间： </b>2014年5月25日星期日16时—18时,  期间有少量样书惠售。",
	"<b>地点： </b> 欧洲时报文化中心, 48-50，Rue Benoît Malon, 94250 Gentilly",
	"座谈会由本书两位作者共同主持，并可即时签书。",
	"<div class=note_title><h1>欢迎光临，共议徒步佳话！</h1></div>",
	""),
array(
"La promotion du livre «La marche dans le Grand Paris», ",
"Table ronde pour la promotion du livre «La marche dans le Grand Paris», ",
"",
"17 mai 2014",
array(
),
array(	"Lors de la table ronde pour la promotion du livre «La marche dans le Grand Paris», et de la projection sur 9 années de randonnées, les deux auteurs Messieurs ZHANG Hanjun et ZHONG Min présenteront leur livre «La marche dans le Grand Paris». Dans ce livre, illustré en couleur avec beaucoup de belles photos, et aux textes élégants et amusants, les auteurs apporteront leurs expériences de randonnées culturelles et naturelles. ",
	"<IMG SRC='".$PHOTO_PATH."jiaoliunews/rando600x450.jpg' width=500>",
	"<b>Date ： </b>Dimanche 25 mai 2014, 16h-18h",
	"<b>Lieu ： </b> Centre Culturel de Nouvelles d’Europe: 48-50 Rue Benoît Malon, 94250 Gentilly",
	"<div class=note_title><h1>Venez nombreux !</h1></div>",
	"",
	""),
)
);
?>