<?php
 $JL_NEWS6 = array(
"开门迎街坊，香槟待朋友",
"2013年12月15日上午，欧洲时报文化中心举行了新址揭牌仪式，",
"",
"2013年12月15日",
array(
),
array(	"2013年12月15日上午，欧洲时报文化中心举行了新址揭牌仪式，下午举办了香槟酒会招待新朋旧友。",
	"欧洲时报文化中心新址位于GENTILLY市，所处的位置是该市极具文化和历史意义的地点。很多久居GENTILLY市的居民都对这个地方充满着深厚的感情，也对新落户的欧洲时报文化中心充满着好奇。",
	"中心热情地邀请了广大街坊前来参观设计雅致大方的新馆。不但有香槟美食相伴，更用丰富的图片向大家介绍了文化中心举办的各种群众文化活动，希望能够为本地的文化生活增添中国色彩。",
	"许多欧洲时报文化中心的老朋友也收到了邀请，大家欣喜地欢聚一堂。其中不少人都见证了欧洲时报文化中心的发展，从只有几张简陋的折叠课桌的读者之家，发展到如今一个包括画廊、学校、图书馆在内的综合活动中心。大家频频举杯，共祝美好未来！",
	""),
array(
"Pendaison de crémaillère de l’Association des amis de Nouvelles d’Europe",
"",
"",
"",
array(
),
array(	"<IMG src='".$PHOTO_PATH."meeting/openparty.jpg' width=500>",
	"Après l’inauguration du nouveau Centre culturel dans la matinée du 15 décembre 2013, l’Association des Amis de Nouvelles d’Europe a organisé l’après-midi un cocktail d’ouverture pour pendre la crémaillère.",
	"<IMG src='".$PHOTO_PATH."meeting/party2.jpg' width=500>",
	"Le nouveau site se trouve dans un endroit culturel et historique de Gentilly. De nombreux voisins et les anciens amis de l’Association ont été chaleureusement invités à visiter le nouveau bâtiment.",
	"<IMG src='".$PHOTO_PATH."meeting/party.png' width=500>",
	"En même temps qu’ils pouvaient déguster le champagne, les invités ont eu un aperçu général de toutes les activités culturelles grâce aux photos exposées. Ils ont porté des toasts pour souhaiter un bel avenir au nouveau Centre culturel.",
	""),
)
);
?>