<?php
include ("jl_news29.inc");
include ("jl_news28.inc");
include ("jl_news27.inc");

include ("jl_news1.inc");
include ("jl_news2.inc");
include ("jl_news3.inc");
include ("jl_news4.inc");
include ("jl_news5.inc");
include ("jl_news6.inc");
include ("jl_news7.inc");
include ("jl_news8.inc");
include ("jl_news9.inc");
include ("jl_news10.inc");
include ("jl_news11.inc");
include ("jl_news12.inc");
include ("jl_news13.inc");
include ("jl_news14.inc");
include ("jl_news15.inc");
include ("jl_news16.inc");
include ("jl_news17.inc");
include ("jl_news18.inc");
include ("jl_news19.inc");
include ("jl_news20.inc");
include ("jl_news21.inc");
include ("jl_news22.inc");
include ("jl_news23.inc");
include ("jl_news24.inc");
include ("jl_news25.inc");
include ("jl_news26.inc");





$JL_NEWS = array($JL_NEWS1, $JL_NEWS2, $JL_NEWS3, $JL_NEWS4, $JL_NEWS5, $JL_NEWS6, $JL_NEWS7, $JL_NEWS8, $JL_NEWS9, $JL_NEWS10, $JL_NEWS11, $JL_NEWS12, $JL_NEWS13, $JL_NEWS14, $JL_NEWS15, $JL_NEWS16, $JL_NEWS17, $JL_NEWS18, $JL_NEWS19, $JL_NEWS20, $JL_NEWS21, $JL_NEWS22, $JL_NEWS23, $JL_NEWS24, $JL_NEWS25, $JL_NEWS26, $JL_NEWS27, $JL_NEWS28, $JL_NEWS29);?>

