<?php
 $WY_NEWS16 = array(
"气功讲座（法语）",
"气功是中国流传千年之久的一种健身术，当下也很流行。",
"",
"2014年9月15日",
array(
),
array("<IMG src='".$PHOTO_PATH."wenyunews/conference qigong.jpg' width=500>", "气功是中国流传千年之久的一种健身术，当下也很流行。从历史角度看气功，是通过调神的自我锻炼，使自身气机变得协调的锻炼方法；从现代的角度看，气功锻炼是对一种有利于心身健康的良性行为。", " ", "我们还将讨论构成人体生命活动的主要物质，通常称为三宝（“精”、“气”、“神”）， 通过练精、气、神，疏通经络达到强体健身的目的。 ", "", "练气功要配合一些动作，您可以在周四的课程中亲身体验。", "", "讲座时间：9月21日 15H00 – 16H00", "", "", "欢迎参加！", "", "", ""),
array(
"Conférence(en français) : Qu'est-ce que le « Qi Gong » et pourquoi le pratiquer",
"Au delà d'un phénomène de mode actuel, le Qi Gong est un art de santé plusieurs fois millénaires.",
"",
"le 15 septembre 2014",
array(
),
array("<IMG src='".$PHOTO_PATH."wenyunews/conference qigong.jpg' width=500>", "Au delà d'un phénomène de mode actuel, le Qi Gong est un art de santé plusieurs fois millénaires. A travers la compréhension de son histoire, vous comprendrez les différentes influences qui ont fait évoluer le Qi Gong vers les formes modernes que nous pratiquerons cette année.", "Durant cette conférence nous aborderons également les concepts de base de cette discipline, les trois trésors (le Jing, le Qi et le Shen), les centres énergétiques du corps, Le Yin et le Yang ou la stimulation de la circulation énergétique dans les méridiens et les organes.", "Nous pratiquerons surtout quelques mouvements pour vous donnez un avant goût des exercices qui vous seront proposés dans les cours du jeudi.", "Bienvenue ！", "", "Conférence en français", "Date : 18 septembre 2014", "Horaire : 15h00 – 16h00", "", "", ""),
)
);
?>