<?php
 $WY_NEWS2 = array(
"木兰拳班学员拍摄比赛录像",
"对于全世界的木兰拳爱好者和练习者来说，2013年中国木兰拳跨年度（碟片）国际挑战评奖大赛",
"",
"2014年1月15日",
array(
),
array(	"<IMG SRC='".$PHOTO_PATH."mulan.jpg' width=500>",
	"对于全世界的木兰拳爱好者和练习者来说，2013年中国木兰拳跨年度（碟片）国际挑战评奖大赛是一个展示及检验自己水平的好机会。",
	"在80多岁高龄的王贤琴老师的指导下，欧洲时报文化中心木兰拳班的学员们勤学苦练，认真备赛。为了保证良好的效果，学员们专门邀请了专业人士执镜，为大家拍摄比赛录像。这次比赛，学员们一共选送了9个个人项目和一个团体项目，内容既有较常见的徒手、扇、剑，还包括有花刀、圈等。所有参赛碟片均已寄出，参赛者们正在兴奋而紧张地等待捷报传来。",
	""),
array(
"Les élèves de la classe de Moulan Quan sont en train de faire la vidéo du concours",
" ",
"",
"le 15 janvier 2014",
array(
),
array(	"<IMG SRC='".$PHOTO_PATH."mulan.jpg' width=500>",
	"Le concours international de Mulan Quan de 2013 est un grand challenge et une opportunité de tester son niveau pour tous les amateurs et praticiens de Mulan Quan. ",
	"Dirigés par un professeur de plus de 80 ans, les élèves de la classe de Mulan Quan de l’Association des amis de Nouvelles d’Europe s’entraînent avec assiduité pour ce concours. Les photographes professionnels sont invités à les filmer afin d’avoir une bonne qualité de vidéo. Neuf performances individuelles et une performance collective ont été sélectionnées pour ce concours. Elles concernent des démonstrations avec ou sans armes, comme l’éventail, l’épée, le couteau ou le cercle. Les vidéos ont été déjà envoyées. Les participants sont impatients dans l’attente des résultats.",
	""),
)
);
?>