<?php
 $WY_NEWS4 = array(
"合唱团精心准备春节演出",
"今年春节期间，合唱团的成员将应邀参加巴黎十三区市政府的团拜会",
"",
"2014年1月8日",
array(
),
array(	"<IMG SRC='".$PHOTO_PATH."school/hechangtuan.jpg' width=500>",
	"每到新年及重大节日期间，欧洲时报丝绸之路合唱团成员总会特别忙碌。今年春节期间，合唱团的成员将应邀参加巴黎十三区市政府的团拜会，并将在文化中心迎马年，华法联欢会上一展歌喉。",
	"合唱团多次参加各种规模的演出，早已成为活跃在法国侨界一道独特的风景线，可以说是身经百战，盛名在外。可每次接到演出任务的他们，总是高度重视。一方面，大家集思广益挑选合适的合唱曲目，另一方面，在老师的指导下，他们认真排练，争取为大家呈现最佳的表演。",
	"<IMG SRC='".$PHOTO_PATH."school/hechangtuan2.jpg' width=500>",
	"欧洲时报丝绸之路合唱团成员多为旅居海外多年的东南亚华侨，每逢佳节倍思亲正是他们最真实的写照，他们的歌声也因此饱含了对祖（籍）国的深情想念与浓情祝福。让我们一起期待他们的精彩演出。",
	""),
array(
"Préparation assidue de la chorale pour la fête du printemps chinois",
" ",
"",
"8 janvier 2014",
array(
),
array(	"<IMG SRC='".$PHOTO_PATH."school/hechangtuan.jpg' width=500>",
	"Les chorales sont toujours très chargées à chaque occasion d’événement important comme le Nouvel An chinois. Elles sont invitées à participer à la messe de salutation organisée par la mairie du 13e arrondissement. Ils vont également chanter pour le gala du nouvel an chinois du cheval. ",
	"Les chorales sont très actives dans la communauté chinoise et elles ont déjà participé à de nombreux spectacles. Malgré leur expérience, elles s’entraînent consciencieusement pour chaque événement proposé. Elles sélectionnent les chansons et font la répétition attentivement afin de montrer les meilleures performances. ",
	"<IMG SRC='".$PHOTO_PATH."school/hechangtuan2.jpg' width=500>",
	"Beaucoup de membres de la chorale sont venus de l’Asie du Sud-Est, et ils sont en France depuis de nombreuses années. Grâce à leur passion de la musique et leur sentiment profond pour leur pays natal, ils se réunissent chaque dimanche. Ils participent à de nombreux spectacles et sont devenus des représentants de la communauté chinoise à Paris. La fête comme celle du Nouvel An chinois nous fait toujours penser à la famille absente. Les choristes expriment leurs bénédictions à leur famille et leurs meilleurs vœux pour la Chine à travers leur voix. ",
	""),
)
);
?>