<?php
 $WY_NEWS11 = array(
"木兰拳走进法国养老院 中国武术风采再现",
"欧洲时报文化中心木兰拳班的学员们开展“木兰拳走进法国养老院”的活动",
"",
"2014年6月13日",
array(
),
array(	"自从2013年6月欧洲时报文化中心木兰拳班的学员们开展“木兰拳走进法国养老院”的活动以来，不少学员就经常参加这类公益活动。今年6月4日欧洲时报文化中心和巴黎木兰拳研究中心的学员们再次来到巴黎北郊路易•穆利耶医院(Hopital Louis Mourier)的养老院参加献爱心活动。",
	"",
	"<IMG SRC='".$PHOTO_PATH."wenyunews/mulan_retraite600.jpg' width=500>",
	"",
	"这次学员们在王贤琴老师的带领下，精心排练了五个套路：双圈“哪吒探海”、 单武扇“桃花幽香”、健身扇“彩蝶纷飞”、“精品拂尘”和“芙蓉出水”，再加上长绸扇，构成了一台精美的演出。",
	"",
	"为了熟悉演出场地，学员们冒着暴雨提前到达养老院进行准备。其他的团体因天气原因未能前去参加，木兰拳团队成了唯一的表演团队。由于暴雨不断，原定的露天活动也临时改成了室内。虽然场地小了，表演受到了一定的限制，但是学员们还是完美地呈现了她们的专场演出。",
	"",
	"养老院里大多数老年人生活不能自理，也很少与外界接触，这次观看演出的老人们坐满了大厅，他们对学员们带来的每个表演都报以热烈的掌声，中国武术的魅力深深地吸引和打动了他们。木兰拳班的中外学员们也为能传播中国武术的风采而感到开心和自豪。",
	"",
	"演出结束后大家也一起参加了院方举办的义卖活动，所有款项全部捐献给养老院。",
	"",
	"爱心无国界，学员们真诚地祝愿法国老年朋友们健康长寿！",
	""),
array(
"Une démonstration de Mulan Quan dans la maison de long séjour",
"un spectacle pour les personnes âgées de la maison de long séjour",
"",
"11 juin 2014",
array(
),
array(	"Les élèves du Mulan de l’Association des Amis de Nouvelles d’Europe ont donné un spectacle pour les personnes âgées de la maison de long séjour de l’ Hôpital Louis Mourier à Colombe, au nord de Paris. ",
	"<IMG SRC='".$PHOTO_PATH."wenyunews/mulan_retraite600.jpg' width=500>",
	"Avec leur professeur Madame WANG Xianqin, ils ont préparé un programme riche et varié : «Les papillons multicolores tourbillonnement », deux cerceaux « Nezha sonde la mer », l’éventail armé « Le parfum des fleurs de pêches », l’éventail fortifié « La santé de Mulan », l’éventail de « Os de dragon », « Parfum de Mulan» et l’éventail en soierie longue. Les personnes âgées ont beaucoup applaudi et apprécié cette démonstration de l’art martial chinois.",
	" L’amour est sans frontière, et les élèves souhaitent sincèrement aux personnes âgées des vœux de bonne santé et de longévité.",
	""),
)
);
?>