<?php
 $WY_NEWS12 = array(
"第三届巴黎中国曲艺节即将开幕",
"第三届巴黎中国曲艺节将于2014年6月30日在巴黎皮尔卡丹剧场开幕。",
"",
"2014年6月15日",
array(
),
array(	"<IMG width=500 src='".$PHOTO_PATH."wenyunews/quyi600.jpg'>",
	"为庆祝中法建交五十周年,第三届巴黎中国曲艺节将于2014年6月30日19点30在巴黎皮尔卡丹剧场(Espace Pierre Cardin, 1-3 avenue Gabriel 75008 Paris)开幕。",
	"由中国曲艺家协会、巴黎中国文化中心主办,欧洲时报传媒以及法国法国华商会承办的第三届巴黎中国曲艺节,荟萃了来自中国各地优秀的曲艺表演艺术家,其中有著名相声艺术家姜昆、戴志诚,以及著名小品演员郭达等。敬请期待中国艺术家们精彩的表演。",
	"",
	"<b>票务咨询： </b> 01 53 82 78 94",
	""),
array(
"Festival de Quyi de Chine à Paris",
"le 3ème Festival des arts chinois du divertissement à Paris débutera le 30 juin",
"",
"15 juin 2014",
array(
),
array(	"<IMG width=500 src='".$PHOTO_PATH."wenyunews/quyi600.jpg'>",
	"A l’occasion du 50ème anniversaire de l’établissement des relations diplomatiques entre la France et la République populaire de Chine, le 3ème Festival des arts chinois du divertissement à Paris débutera le 30 juin à l’Espace Pierre Cardin (1-3, avenue Gabriel 75008 PARIS). ",
	"",
	"<b>Organisateurs : </b> Association des Artistes de Quyi de Chine; le Centre culturel de Chine à Paris",
	"<b>Co-organisateurs : </b> Journal de Nouvelles d’Europe; Association des Commercants Chinois en France",
	"<b>Date du spectacle : </b>lundi 30 juin 2014 ",
	"<b>Lieu du spectacle : </b>Espace Pierre Cardin, 1-3, avenue Gabriel 75008 PARIS",
	"",
	"<b>Vente des billets au bureau commercial de Nouvelles d’Europe</b>",
	"<b>Adresse： </b>90 -92 avenue de Choisy 75013 PARIS",
	"<b>Information： </b> 01 53 82 78 94",
	""),
)
);
?>