<?php
 $WY_NEWS19 = array(
"新增气功八段锦班",
"气功是一种以呼吸的调整、身体活动的调整和意识的调整为手段，以强身健体、防病治病、健身延年、开发潜能为目的的一种",
"",
"2014年12月16日",
array(
),
array(	"<IMG src='".$PHOTO_PATH."wenyunews/qigong.PNG' width=500>    ",
	"气功是一种以呼吸的调整、身体活动的调整和意识的调整为手段，以强身健体、防病治病、健身延年、开发潜能为目的的一种身心锻炼方法。",
	"八段锦做为优秀的中国传统保健气功，流传甚广。八段锦动作简单易行，功效显著。通过练习可以达到拉伸经筋、调理内脏、运动血脉的作用，增加肌肉力量，对预防疾病和改善健康产生真正的影响，进而达到延年益寿的效果。",
	"",
	"开班日期：2015年1月10日至2015年6月26日",
	"上课时间: 星期五  12h30 – 13h30（法国学生假期及法定节假日除外）",
	"",
	"授课老师: Chrystel",
	"",
	"联系电话：01 41 24 41 41（徐老师）/ 06 81 23 99 78 (Chrystel法语)",
	"",
	"<a href='http://www.freres-d-ames.fr' target='_blank'>相关网站</A> ",
	""),
array(
"Cours de Qi Gong-Ba Duan Ji",
"Le Qi Gong est une discipline où s'harmonise le corps, la respiration et l'esprit pour une",
"",
"Le 16 décembre 2014",
array(
),
array(	"<IMG src='".$PHOTO_PATH."wenyunews/qigong.PNG' width=500>   ",
	"Le Qi Gong est une discipline où s'harmonise le corps, la respiration et l'esprit pour une meilleure gestion de votre vitalité quotidienne.",
	"Le &quot;Ba Duan Jin&quot; est un des plus anciens et des plus traditionnels enchaînements de Qi Gong. Il est pratiqué en Chine depuis des siècles.",
	"Dans ce cours, vous pratiquerez principalement un enchaînement traditionnel : « Les huit pièces de brocard » (Ba Duan Jin) tel que le transmettent les experts de « l'Association chinoise du Qi Gong pour la santé ». ",
	"Cet enchaînement de huit mouvements a pour avantage d'être simple et facile à pratiquer. Il est prouvé que sa pratique permet d'améliorer les fonctions du système neuro-hormonal, de favoriser la circulation de l'énergie et du sang, d'augmenter la force des muscles, et de masser profondément les organes internes. Il exerce donc une réelle influence sur la prévention des maladies et l'amélioration de la santé.",
	"Date : du 10 janvier 2015 à fin juin 2015",
	"Horaire : Vendredi   12h30 – 13h30",
	"Professeur : Chrystel",
	"Contactez ：06 81 23 99 78（Chrystel）/ 01 41 24 41 41	（Mme XU）		",
	"<a href='http://www.freres-d-ames.fr' target='_blank'>Lien utile</A> ",
	""),
)
);
?>