<?php
 $WY_NEWS17 = array(
"周六交谊舞班带你领略舞蹈之美",
"周六交谊舞分为几部分",
"",
"",
array(
),
array(	"<IMG src='".$PHOTO_PATH."wenyunews/dansesamedi.jpg' width=500>",
	"周六交谊舞班分为以下几部分：",
	"",
	"14H—15H : 初级，排排舞、双人集体舞 ",
	"15H—16H : 中级，排排舞、双人集体舞 ",
	"16H—17H : 交谊舞（伦巴, 吉鲁巴，牛仔，华尔兹)",
	"17H—18H : 交谊舞（巴恰塔，探戈，快华尔兹)、实践练习",
	"",
	"老师耐心讲解、循序渐进，带你领略舞蹈之美！",
	"联系电话：06 29 46 50 91 (林老师)、06 99 68 98 25 (林太)",
	"文化中心：01 41 24 41 42/44（陈老师）",
	""),
array(
"Danse à Samedi",
"Danse de salon,plusieurs niveaux à vous proposer par les professeurs Monsieur et Madame Lin",
"",
"le 16 septembre 2014",
array(
),
array(	"<IMG src='".$PHOTO_PATH."wenyunews/dansesamedi.jpg' width=500>",
	"Danse de salon,plusieurs niveaux à vous proposer par les professeurs Monsieur et Madame Lim.",
	"",
	"14H—15H : Débutant, Country et Duo Danse",
	"15H—16H : Intermédiaire， Country et Duo Danse",
	"16H—17H : Danse de salon (Rumba, Jitterbug，Rock，Valse)",
	"17H—18H : Danse de salon（Bachata，Tango，Valse-Viennoise)，& Danse Pratique",
	"",
	"Contact：06 29 46 50 91 (M. LIM)/06 99 68 98 25 (Mme LIM)、",
	"Centre culture: 01 41 24 41 42/44（Mme Chen）",
	""),
)
);
?>