<?php
 $WY_NEWS3 = array(
"二月新班注册",
"中国书法和绘画经过几千年的历史沉淀，已经成为中国的国粹。",
"",
"2014年1月14日",
array(
),
array(	"<h3>书画班</h3>",
	"中国书法和绘画经过几千年的历史沉淀，已经成为中国的国粹。练习书画不仅能陶冶人的情操，培养高雅的业余爱好和文明的风度，还能给人以愉悦，激发人的感情，宁神健魄。教学中，教师注重因材施教，针对个人的水平和特色做个性化的辅导。",
	"<IMG SRC='".$PHOTO_PATH."school/shufa-600.jpg' width=500>",
	"第11期书画班为期四个半月，2014年2月9日开学，至6月22日结束。",
	"上课时间：星期日10:30 - 12:00（在此时间段内学山水画者自选1小时，学书法者自选1个半小时）",
	"任教老师：马剑虹（著名旅法书法、山水画家，法国书画家协会会长）",
	"报名电话：01 41 24 41 42（陈老师）／01 41 24 41 40",
	""),
array(
"L'inscriptions pour les nouvelles classes à partir de février",
" ",
"",
"le 14 janvier 2014",
array(
),
array(	"<h3>La classe de la calligraphie et de la peinture chinoise</h3>",
	"La calligraphie et la peinture chinoises ont une histoire commune vieille de milliers d'années, et représentent la quintessence profonde de la Chine. Pratiquer l’art de la calligraphie c’est non seulement se cultiver, mais c’est aussi le plaisir d'acquérir de l'élégance et la paix de l’âme. L'enseignement est très personnalisé.",
	"<IMG SRC='".$PHOTO_PATH."school/shufa-600.jpg' width=500>",
	"La classe commencera le 9 février 2014 et finira le 22 juin 2014, pour une durée de 4 mois et demi.  ",
	"<b>Horaires : </b> dimanche 10h30 - 12h00",
	"<b>Professeur ：</b> M. Jianhong MA, calligraphe chinois connu, habitant en France, président de l'Association le Pinceau d’Or. ",
	"<b>Contact  ：</b> 01 41 24 41 42 ou 01 41 24 41 40 (Madame Chen)",
	""),
)
);
?>