<?php
include ("wy_news16.inc");
include ("wy_news1.inc");
include ("wy_news2.inc");
include ("wy_news3.inc");
include ("wy_news4.inc");
include ("wy_news5.inc");
include ("wy_news6.inc");
include ("wy_news7.inc");
include ("wy_news8.inc");
include ("wy_news9.inc");
include ("wy_news10.inc");
include ("wy_news11.inc");
include ("wy_news12.inc");
include ("wy_news13.inc");
include ("wy_news14.inc");
include ("wy_news15.inc");
include ("wy_news17.inc");
include ("wy_news18.inc");
include ("wy_news19.inc");








$WY_NEWS = array($WY_NEWS1, $WY_NEWS2, $WY_NEWS3, $WY_NEWS4, $WY_NEWS5, $WY_NEWS6, $WY_NEWS7, $WY_NEWS8, $WY_NEWS9, $WY_NEWS10, $WY_NEWS11, $WY_NEWS12, $WY_NEWS13, $WY_NEWS14, $WY_NEWS15, 0, $WY_NEWS17, $WY_NEWS18, $WY_NEWS19);?>

