<?php

include ("wy_news1.inc");
include ("wy_news2.inc");
include ("wy_news3.inc");
include ("wy_news4.inc");
include ("wy_news5.inc");
include ("wy_news6.inc");
include ("wy_news7.inc");
include ("wy_news8.inc");
include ("wy_news9.inc");
include ("wy_news10.inc");
include ("wy_news11.inc");
include ("wy_news12.inc");
include ("wy_news13.inc");
include ("wy_news14.inc");
include ("wy_news15.inc");
include ("wy_news16.inc");
include ("wy_news17.inc");
include ("wy_news18.inc");
include ("wy_news19.inc");
?>

