<?php
 $WY_NEWS8 = array(
"2014年华裔青少年夏令营招生",
"近二十年来，除遇特大自然灾害，学校年年都组织学生赴中国进行三周至一个月的夏令营活动。",
"",
"2014年4月11日",
array(
),
array("青少年夏令营是欧洲时报中文学校的名牌项目。近二十年来，除遇特大自然灾害，学校年年都组织学生赴中国进行三周至一个月的夏令营活动。", "夏令营期间，学生们在中国学习汉语知识、体验中国文化、参观名胜古迹，并结交了不少新朋友。除了传统的北京寻根夏令营，欧洲时报中文学校与中国宋庆龄基金会合作，参加了由基金会组织的国际青少年交流营（即北京—内蒙古团），深受学生的喜爱。", "<h5>北京团</h5>", "<IMG SRC='../photos/huodong/greatwall600-480.jpg' width=500>", "<ol class=listarticle>
<li><b>时间：  </b> 7月7日-8月2日，为期26天。</li>
<li><b>团员要求： </b> 12岁-17岁，身体健康。</li>
<li><b>学习内容： </b> 中文学习，书法、绘画、手工、舞蹈以及武术、羽毛球等：</li>
<li><b>参观游览： </b> 长城、故宫、天安门、颐和园、天坛、国家博物馆、北海公园、动物园,以及品尝美食、观看文艺演出等。</li>
<li><b>住宿单位： </b> 北京华文学院。北京华文学院网址: <a href=http://www.bjhwxy.com/>http://www.bjhwxy.com/</a></li>
<li><b>费用： </b> 2100 欧元。签证自理。</li></ol>", "<h5>北京-内蒙古团</h5>", "<IMG SRC='../photos/huodong/V1mongolie600-480.jpg' width=500>", "<ol class=listarticle>
<li><b>时间：  </b> 7月7日-8月2日，为期26天。</li>
<li><b>团员要求： </b> 12岁-17岁，身体健康。</li>
<li><b>学习内容： </b> 中文学习，书法、绘画、手工、舞蹈以及武术、羽毛球等：</li>
<li><b>参观游览： </b> 长城、故宫、天安门、颐和园、天坛、国家博物馆、北海公园、动物园, 以及品尝美食、观看文艺演出等。<br>去内蒙古观赏草原风情、欣赏那达慕的骑马和摔跤表演、参加草原运动会等。</li>
<li><b>住宿单位：  </b> <br>
<b>北京期间：</b> 北京华文学院。 北京华文学院网址: <a href=http://www.bjhwxy.com/>http://www.bjhwxy.com/</a><br><b>交流营期间：</b> 星级宾馆或青少年国际交流营活动基地</li>
<li><b>费用：   </b> 2300 欧元。签证自理。</li></ol>", "", "<b>注意事项： </b> 报名时须交定金（200欧元）及护照复印件。", "<span class=spanarticle> （支票 ORDRE : Association Des Amis de Nouvelle d'Europe）</span>", "<b>报名表请寄： </b> 欧洲时报之友协会-夏令营   ", "<span class=spanarticle> Association Des Amis de Nouvelle d'Europe</span>", "<span class=spanarticle> 50 RUE BENOIT MALON  94250 GENTILLY</span>", "<b>详情咨询：  </b> ", "<span class=spanarticle>电话 : 01 41 24 41 42 / 44 / 40 </span>        ", "<span class=spanarticle>传真 : 01 41 24 41 49   </span>", "<span class=spanarticle>Email : <a href='mailto:chenxiaojing@oushinet.com'>chenxiaojing@oushinet.com</a> 或 <a href='mailto:ecole@oushinet.com'>ecole@oushinet.com</a></span>", 
" ", 
"<div class=note_title><h1><a href='../register/?registerref=summerxungen'>在线报名</a> / <a href='../files/summerbaoming.pdf' target=_blank>下载报名表</a> </h1></div>", 
"1. <a href='../files/beijing.pdf' target=_blank>查看北京团行程</a> / <a href='../files/beijingmoguli.pdf' target=_blank>北京—内蒙古团行程</a>", 
"2. 相关链接：", 
"<span class=spanarticle>1)	<a href='http://fzone.oushinet.com/bbs/forum.php?mod=viewthread&tid=13001&highlight=%E5%A4%8F%E4%BB%A4%E8%90%A5' target=_blank>2013年欧洲时报中文学校青少年寻根夏令营活动掠影</a></span>",
"<span class=spanarticle>2)	<a href='http://www.sclf.org/ztjj/2013gjjly/index.htm' target=_blank>第四届宋庆龄国际青少年交流营</a></span>",

"")
);
?>