<?php

include_once("french_top.inc");
include_once ("french_news_jy.inc");
include_once ("french_news_jl.inc");
include_once ("french_news_wy.inc");
include_once ("french_news_hj.inc");

/*
$TOPPHOTOS = array(
array($DIVER_NEWS1, "top/stage2014-650x380.jpg", $HOST_URL."/french/album.php"),
array($WY_NEWS12, "top/quyi650x380.jpg"),
array($WY_NEWS13, "top/Melun_650x380.jpg"),
array($JL_NEWS18, "top/diaolou650x380.jpg"),
array($WY_NEWS11, "top/mulan_retraite650x380.jpg"),
array($JL_NEWS17, "top/wenzi650x380.jpg"),
array($JL_NEWS16, "top/gxj648.jpg"),
array($JY_NEWS12, "top/aduilt650.jpg"),
array($JL_NEWS15, "top/plaque650.jpg"),
array($ASSO_NEWS4, "top/Amiens650x380.jpg"),
array($JL_NEWS14, "top/rando650x380.jpg"),

array($JL_NEWS13, "top/jiangtan650x380.jpg"),
array($JL_NEWS12, "top/su650x380.jpg"),
array($WY_NEWS10, "top/Armainvilliers650x380.jpg"),
array($JY_NEWS11, "top/redaction650x380.jpg"),
array($WY_NEWS9, "top/mulan650x380.jpg"),
array($JL_NEWS11, "top/zhang650x380.jpg"),
array($WY_NEWS8, "top/greatwall650-380.jpg"),
array($JY_NEWS10, "top/jiaoyu650x380.jpg"),
array($JY_NEWS9, "top/vacance650x380.jpg"),
array($JL_NEWS10, "top/wulong650x380.jpg"),
array($WY_NEWS7, "top/sceaux650x380.jpg"),
array($JL_NEWS9, "top/exposhanghai650-380.jpg"),
array($JY_NEWS8, "top/shufa650x380.jpg"),
array($JL_NEWS8, "jiaoliunews/fete650-380.jpg"),
array($JL_NEWS7, "jiaoliunews/expo650-380.jpg"),
array($JL_NEWS1, "top/topma1.jpg"),
array($JL_NEWS4, "top/top1-650x380.jpg"),
);
*/
/*
$FHOME_KZXX_NEWS = array($JY_NEWS1, $JY_NEWS3, $JY_NEWS6, $JY_NEWS2);

$FHOME_JY_NEWS = array(
	$JY_NEWS15, $JY_NEWS14, $JY_NEWS13, $JY_NEWS12, $JY_NEWS11, $WY_NEWS8, $JY_NEWS10, $JY_NEWS9,$JY_NEWS8, 
	$JY_NEWS1, $JY_NEWS4, $JY_NEWS3, $JY_NEWS6, $JY_NEWS7, $JY_NEWS5, $JY_NEWS2
);

$FHOME_JL_NEWS = array(
	$JL_NEWS20,$JL_NEWS21,$JL_NEWS19,$JL_NEWS18,$JL_NEWS17, $JL_NEWS16, $JL_NEWS15, $JL_NEWS14, $JL_NEWS13, $JL_NEWS12, $JL_NEWS11, $JL_NEWS10, 
	$JL_NEWS9, $JL_NEWS8, $JL_NEWS7, $JL_NEWS1, $JL_NEWS2, $JL_NEWS4, $JL_NEWS3, $JL_NEWS5, $JL_NEWS6
);

$FHOME_YL_NEWS = array(
	$WY_NEWS17,$WY_NEWS16,$WY_NEWS15,$WY_NEWS14, $WY_NEWS13, $WY_NEWS12, $WY_NEWS11,
	$ASSO_NEWS4, $WY_NEWS9, $WY_NEWS6, $JY_NEWS8, 
	$WY_NEWS1, $WY_NEWS2, $WY_NEWS3, $WY_NEWS4, $WY_NEWS5
);

$FHOME_HUAWEN_NEWS = array(
	$ASSO_NEWS4, $JY_NEWS4, $JY_NEWS7, $JY_NEWS5
);	
*/
/* add a star for the last news */
$FHOME_RIGHT_ITEM_NEW = array($HOME_JY_NEWS_STAR, $HOME_JL_NEWS_STAR, $HOME_YL_NEWS_STAR);

?>
