<?php
include_once("CoursTimeForm.php");
include_once("JLPageForm.php");
include_once("JLPageBaseForm.php");
include_once("JYStudentForm.php");
include_once("NewsForm.php");
include_once("NewsBaseForm.php");
include_once("NewsPageForm.php");
include_once("ScheduleForm.php");
include_once("WYPageForm.php");
include_once("AdminUserForm.php");
?>