<?php

$COURS_NAME= array(
	array("拼音班(7岁起）", "T_CC0"),
	array("汉语一册", 	"T_HY1"),
	array("汉语二册", 	"T_HY2"),
	array("汉语三册", 	"T_HY3"),
	array("汉语四册", 	"T_HY4"),
	array("汉语五册", 	"T_HY5"),
	array("汉语六册", 	"T_HY6"),
	array("汉语七册",  	"T_HY7"),
	array("汉语八册", 	"T_HY8"),
	array("汉语十册", 	"T_HY10"),
	array("汉语十二册", 	"T_HY12"),
	array("HSK5级", 		"T_ZW10"),
	array("LV1-2", 		"T_LV12"),
	array("LV3", 		"T_LV23"),
);

?>
