<?php

$T_G_C =				// 中学生中文班
array("上课时间 ", "",
		array(6, "14:00-16:00 (N1)"),		
);

$T_A_C =				// 成人中文课
array("上课时间 ", "",
		array(6, "10H30-12H30 (N4)"),
		array(7, "10H30-12H30 (N1)", "13H30-15H30 (N2)", "15H45-17H45 (N3)")
		
);

$T_A_C_F =				// 成人中文课
array("Horaires", "",
	array("Samedi", "10H30-12H30 (N3)", "13H30-15H30 (N4)"),
	array("Dimanche", "10H30-12H30 (N1)", "15H00-17H00 (N2)")
);

$T_A_F	= 				// 成人法文课 
array("上课时间 ", "", 
	array(4, "10H00-12H00")
);

$T_C_C = 				//幼儿中文课, 
array("上课时间 ", "", 
	array(7, "10H30—11H30（5岁班）", "11H40—12H40（6岁班）"),
);
$T_C_C_F = 				//幼儿中文课, 
array("Horaires", "",
	array("Dimanche", "10H30—11H30 (5 ans) ", "11H40—12H40 (6 ans)"),
);


$T_A_H = 				// 汉法双语会话角" 
array("上课时间 ", "", 
	array(5, "14H30-16H30")
);
$T_A_H_F = 				// 汉法双语会话角" 
array("Horaires ", "", 
	array("Vendredi", "14H30-16H30")
);

$T_XT = 
array("上课时间 ", "", 	// 中国民族舞" 
	array(3, "15H30-17H30"), 
);

$T_YJ = 
array("上课时间 ", "", 	// 瑜伽 
	array(6, "10H30-12H00", "14H00-15H30", "15H45-17H15"),
	//array(7, "15H45-17H15")
);

$T_YJF = 
array("Horaires", "", // joga
	array("Samedi", "10h30 – 12h00", "14h00 – 15h30", "15H45-17H15"),
	//array("Dimanche", "15h45 – 17h10"),
);

$T_ML = 
array("上课时间 ", "",	//木兰拳 
	array(5, "14H30-16H00")
);

$T_GCW = 
array("上课时间 ", "",	//广场舞 
	array(6, "14H00-15H30")
);
$T_GCWF = 
array("Horaires", "", 
	array("Samedi", "14H00—15H30")
);

$T_QG =
array("上课时间 ", "",	// 气功课
		array(5, "12H30-13H30")
);
$T_TJ =
array("上课时间 ", "",	// 太极
		array(7, "10H30-12H00")
);

$T_TB = 
array("上课时间 ", "",	// 徒步健身俱乐部 
	array(6, "4月12日14:30-17:30")
);

$T_SL =	
array("上课时间 ", "",	// "交谊舞" 
	array(6, "15H30-17H30")
);

$T_JS = 
array("上课时间 ", "",	// 健身舞 
	array(4, "14H30-16H30")
);

$T_GD = 
array("上课时间 ", "",	// 中国古典舞
	array(7, "10H30-12H30")
);


$T_HC =
array("上课时间 ", "",	// 合唱团 
	array(7, "14H00-18H00")
);



$T_DL1 =
array("上课时间 ", "",	// 电脑初级班 
	array(7, "10H30-13H00")
);

$T_DL2 =
array("上课时间 ", "",	// 电脑高级班 
	array(7, "14H00-16H00")
);

$T_WL =
array("上课时间 ", "",	// 网络销售速成班
		array(6, "14H30-16H30")
);

$T_GUQ =
array("上课时间 ", "",	// 古琴课
		array(3, "13:20-14:20","14:25-15:25","15:35-16:35","16:40-17:40")
);

$T_SH =	
array("上课时间 ", "",	// 书画班  
	array(3, /*"14:00—15:30",*/ "15:15—17:15"),
	//array(6, "14:00—15:30", "15:45—17:15"),
	//array(7, "10:30—12:30"),
);
$T_CSH =
array("上课时间 ", "",	// 少儿美术班
		array(6, "14:00—15:30", "15:45—17:15"),
);
$T_CYG =
array("上课时间 ", "",	// 少儿腰鼓班
		array(7, "14:00—15:30", "15:45—17:15"),
);
$T_SH_F =	
array("Horaires", "",
	array("Mercredi", /*"14:00—15:30",*/ "15:45—17:15"),
	//array("Samedi", "14:00—15:30", "15:45—17:15"),
	array("Dimanche", "10:30—12:30"),
);

$T_GQ = 
array("上课时间 ", "",	// 钢琴课 
	array(3, ""), 
	array(6, ""),
	array(7, "")
);

$T_WD = 
array("上课时间 ", "",	// 少儿民族健身舞班 
	array(3, "14H00—15H30", "15H45—17H15"),
);

$T_WD_F = 
array("Horaires", "",
	array("Mercredi","14H00—15H30", "15H45—17H15"),
);

$T_WS = 
array("上课时间 ", "",	// 少儿武术课 
	array(6, "14H00—15H30", "15H45—17H15")
);

$T_FS = 
array("上课时间 ", "",	// 女子防身术 
	array(6, "11H00—12H30")
);


$T_WS_F = 
array("Horaires", "",
	array("Mercredi", "14H30—15H30", "15H45—17H15")
);

$T_YCT = 		array("星期日 : 10H30-12H30");
$T_CONCOURS = 	array("星期日 : 10H30-12H30");

// 暑期班
//$T_SQ = 		array("星期一至六:14h00-15h30和15h45-17h15");
$T_SQ = 		
array("上课时间 ", "",	// 暑期班  
	array("星期一至五 14h00-17h15"),
);

//暑期少儿武术班
$T_SQWS = 		array("星期一至六:14h00-15h30或15h45-17h15");

//"冬季大乐园"
$T_DLY = array("巴黎:12月27日-1月2日");
$T_DLY_P = array("100 € /人 ");

//"夏令营"
$T_ETE =	array("北京团:7月7日-8月2日", 	"北京-内蒙团:7月7日-8月2日");
$T_ETE_P = 	array(" 2100 € /人 （签证自理）", 	" 2300 € /人 （签证自理）");


$REGISTER_TAB = array(
array("语言学习", "langage", 1,
//	array("成人法文课", "francais", 		1, 	$T_A_F),
	array("幼儿中文课", "children", 		0, 	$T_C_C),
	array("青少年中文课", "chinois", 		1),
	array("成人中文课", "adulte", 		1, 	$T_A_C),
	array("中学生中文班", "college", 		1, 	$T_G_C),
	//	array("汉法双语会话角", "huihua", 	0, $T_A_H),
	
),
array("文体活动", "wenti", 1,
	array("瑜伽", "yujia", 				1,	$T_YJ),
	array("中国民族舞", "xingti", 			1,	$T_XT),
	array("气功", "qigong", 			1,	$T_QG),
	array("木兰", "mulan", 			1,	$T_ML),
	array("交谊舞提高班", "shalongwu", 		1,	$T_SL),
	array("集体健身舞", "jianshenwu", 		1, 	$T_JS),
	//array("古琴课", 	"guqin", 				1,	$T_GUQ), 
	array("太极", 	"taiji", 				1,	$T_TJ), 
	array("合唱团", "hechangtuan", 		1, 	$T_HC),
		//	array("徒步健身俱乐部", "tubu", 		1, 	$T_TB, array("免费")),

),
array("文娱活动", "wenyu", 1,
//	array("广场舞", "guanchangwu", 		1, 	$T_GCW),
//	array("中国古典舞", "guodian", 		1, 	$T_GD),
	
),
/*
array("夏令营", "summer", 1,
	array("冬季大乐园", "daleyuan", 		0, $T_DLY, $T_DLY_P),
	array("夏令营", "summerxungen", 		0, $T_ETE, $T_ETE_P),
),
*/
array("暑期活动", "shuqihuodong", 1,
	array("暑期班7月10日-7月21日", "shuqipinyin", 1, $T_SQ),
//	array("暑期少儿武术班", "shuqiwushu", 		0, $T_SQWS),
),
array("电脑培训", "diannao", 1,
	array("电脑初级班", "diannaochuji", 			1,	$T_DL1),
	array("电脑中高级班", "diannaogaoji", 			1,	$T_DL2),
//	array("网络销售速成班", "wangluoxiaoshou", 	1, 	$T_WL),
),
array("才艺培训", "caiyi", 1,
	array("成人书画课 ", "shuhua", 					1, $T_SH),
	array("少儿美术班", "cshuhua", 					1, $T_CSH),
	array("少儿腰鼓班", "cyaogu", 					1, $T_CYG),
	array("钢琴课 ", "piano", 					1, $T_GQ),
	array("少儿舞蹈课", "dance", 				1, $T_WD),
//	array("少儿武术课 ", "wushu", 				1, $T_WS),
//	array("女子防身术 ", "fansheng", 				1, $T_FS),	
),
/*
array("汉语考试", "concours", 1,
	array("YCT考试", "concoursyct", 				0,	$T_YCT),
	array("中华文化大赛知识竞赛", "concourswenhua", 		1, 	$T_CONCOURS),
),
*/
);

?>
