<?php
$YUNNAN_PHOTOS = array(
	"../photos/yunnan/yunnan1.jpg", " ", 
	"../photos/yunnan/yunnan11.jpg", " ", 
	"../photos/yunnan/yunnan12.jpg", " ", 
	"../photos/yunnan/yunnan13.jpg",	" ",
	"../photos/yunnan/yunnan2.jpg", " ", 
	"../photos/yunnan/yunnan4.jpg",	" ",
	"../photos/yunnan/yunnan10.jpg", " ", 
);

$TONEWSCHOOL_PHOTOS = array(
		"../photos/school/top_newschool.jpg", 	"欧洲时报文化中心新址",
		"../photos/school/top_deng.jpg",      	"", 
		"../photos/school/top_zhang.jpg",		"", 
		"../photos/school/top_maire.jpg",		"",
		"../photos/school/top_zhong.jpg",		"", 
		"../photos/school/top1.jpg",			""
);

$NEWSCHOOL_PHOTOS = array(
	"../photos/school/school.jpg", 		"欧洲时报文化中心",
	"../photos/school/school2.jpg", 	"大厅",
	"../photos/school/classroom.jpg",	"教室",
	"../photos/school/danceroom.jpg",	"舞厅",
);

$PHOTOEXPO_PHOTOS = array(
	"../photos/expo/expo1.jpg", "", 
	"../photos/expo/expo2.jpg", "", 
	"../photos/expo/expo3.jpg", "", 
	"../photos/expo/expo4.jpg", "", 
	"../photos/expo/expo5.jpg", ""
); 

?>
