<?php
$ALLNEWSLISTS = array(
	array("迎羊年华法联欢会", "chevre.jpg", "chevre.jpg", "JL_NEWS29"),
	array("2014年12月YCT、HSK成绩揭晓", "QQ截图20150125065605.png", "QQ截图20150125070236.png", "JY_NEWS23"),
	array("2014“中华文化大乐园”巴黎营成功闭营", "cloture.jpg", "cloture.jpg", "JY_NEWS22"),
	array("2014年中国文化大乐园-法国巴黎营开营", "ouverture.jpg", "ouverture.jpg", "JY_NEWS21"),
	array("文化讲座-由戏剧交流看跨文化对话（法语）", "conf-dongchun.png", "conf-dongchun.png", "JL_NEWS28"),
	array("圣诞快乐", "noel.jpg", "noel.jpg", "JY_NEWS20"),
	array("气功讲座（法语）", "", "", "JL_NEWS27"),
	array("新增气功八段锦班", "qigong.PNG", "qigong.PNG", "WY_NEWS19"),
	array("新增舞蹈初级班", "danse M.png", "danse M.png", "WY_NEWS18"),
	array("民间艺术展及少数民族歌舞表演", "chant-danse.jpg", "chant-danse.jpg", "JL_NEWS26"),
	array("2014年中华文化大乐园-法国巴黎营", "dly-ch.JPG", "dly-fr.JPG", "JY_NEWS19"),
	array("YCT和HSK汉语考试开始报名", "ycthsk-ch.JPG", "ycthsk-fr.JPG", "JY_NEWS17"),
	array("增开周六书法、山水画班", "caligraphie.jpg", "caligraphie.jpg", "JY_NEWS18"),
	array("文化讲座-伏尔泰与中国", "voltaire.jpg", "voltaire.jpg", "JL_NEWS25"),
); 

?>
