<?php
include ("jy_news23.inc");
include ("jy_news22.inc");
include ("jy_news21.inc");
include ("jy_news20.inc");

include ("jy_news1.inc");
include ("jy_news2.inc");
include ("jy_news3.inc");
include ("jy_news4.inc");
include ("jy_news5.inc");
include ("jy_news6.inc");
include ("jy_news7.inc");
include ("jy_news8.inc");
include ("jy_news9.inc");
include ("jy_news10.inc");
include ("jy_news11.inc");
include ("jy_news12.inc");
include ("jy_news13.inc");
include ("jy_news14.inc");
include ("jy_news15.inc");
include ("jy_news16.inc");
include ("jy_news17.inc");
include ("jy_news18.inc");
include ("jy_news19.inc");







?>

