<?php
 $JY_NEWS11 = array(
"祝贺在第十四届华人少年作文比赛中获奖学生",
"“华人少年作文比赛”已成功举办了十四届，",
"",
"2014年4月29日",
array(
),
array("“华人少年作文比赛”已成功举办了十四届，组委会是由国侨办、汉办、北京市/天津市/河南省/河北省/山东省教委等联合组成。
", "第十四届华人少年作文比赛有26个国家的230所华校参赛，收到稿件共计十二万两千余份。第十四届华人少年作文比赛成绩刚刚揭晓，欧洲时报孔子课堂的学生取得了两个一等奖、一个二等奖、五个三等奖的好成绩。
", "&nbsp;&nbsp;&nbsp;<b>一等奖：</b> 王盈《我的家庭》、陈嘉玲《我的家乡和家庭》；
", "<IMG SRC='../photos/wenyunews/huojiang.jpg' width=500>
", "<IMG SRC='../photos/wenyunews/huojiang1.jpg' width=500>
", "&nbsp;&nbsp;&nbsp;<b>二等奖：</b> 陈健洁《姑姑》、陈品臻《我的家庭》
", "&nbsp;&nbsp;&nbsp;<b>三等奖：</b>罗茗阡菾《我的家乡》、梁昭旋《我的家庭》、徐雅琳《我的家庭》、
", "<span class=spanarticle>林佳亭《我的家庭》。</span>
", "在祝贺获奖学生的同时，也希望更多的学生参加第十五届华人少年作文比赛。
", "有关华人少年作文比赛的信息：
", "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &bull; &nbsp;&nbsp;<a href='http://www.hwjyw.com/info/content/2014/03/25/30264.shtml'>第十五届“华人少年作文比赛“征文启事(海外)</a>
", "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &bull; &nbsp;&nbsp;<a href=http://www.hwjyw.com/activity/content/2013/03/22/27566.shtml>第十四届“华人少年作文比赛”征文启事(海外)</a>
", "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &bull; &nbsp;&nbsp;<a href=http://culture-oushi.com/jiaoyu/education.php?resource=student&nindex=5>欧洲时报孔子课堂学生优秀习作  </a>
", "
", "")
);
?>