<?php
 $JY_NEWS16 = array(
"寓教于乐，寓教于舞",
"孩子们在民族民间美妙的音乐中以轻松快乐的方式学习舞蹈",
"",
"2014年9月19日",
array(
),
array(	"<IMG src='".$PHOTO_PATH."jiaoyunews/danseenfant-1.JPG' width=500>",
	"首先让孩子们在学习中感到快乐进而想去探索和体验舞蹈的乐趣，在跳舞中获取审美和情感的愉悦，同时让孩子们在舞蹈学习过程中获取中华民族文化知识并有所体验。用简单、自然的动作编排舞蹈使少儿的身心得到全面的发展，在各民族优秀舞蹈舞曲的基础上重新创意编排，呈现出一个个充满异域风采的舞蹈，有力激发孩子们学习舞蹈的兴趣，给孩子们辅就通向民族的艺术阶梯，以民族民间舞蹈内容为主的教学，也给海外华人的孩子们架起了友谊的桥梁。",
	"<IMG src='".$PHOTO_PATH."jiaoyunews/danseenfant2.JPG' width=500>",
	"孩子们在民族民间美妙的音乐中以轻松快乐的方式学习舞蹈，在无压力的状态下感受美、体验美，在快乐中收获成果。愿孩子们能快乐健康地成长！",
	"孩子们，赶快来和我们一起跳舞吧！",
	"<IMG src='".$PHOTO_PATH."jiaoyunews/danseenfant-3.jpg' width=500>",
	"开班日期：2014年9月17日至2015年6月17日",
	"上课时间: 星期三 14H00 – 15H30，15H45 – 17H15",
	"授课老师: 朱玉霞",
	"报名电话：01 41 24 41 42（陈老师）/ 06 64 85 15 19（朱老师）",
	""),
array(
"Apprendre en dansant",
"Les enfants apprennent avec plaisir d’exprimer des émotions et des sensations",
"",
"Le 19 septembre 2014",
array(
),
array(	"<IMG src='".$PHOTO_PATH."jiaoyunews/danseenfant-1.JPG' width=500>",
	"Les enfants apprennent avec plaisir à exprimer leurs émotions et leurs sensations à travers les gestes, les regards,  la danse  apporte également beaucoup au corps comme à l’esprit. Avec la danse chinoise, les enfants connaissent davantage la culture chinoise, ainsi que plusieurs styles de danse  illustrent de différents paysages.",
	"<IMG src='".$PHOTO_PATH."jiaoyunews/danseenfant2.JPG' width=500>",
	"Les enfants, venez danser avec nous ! ",
	"<IMG src='".$PHOTO_PATH."jiaoyunews/danseenfant-3.jpg' width=500>",
	"Date：17/09/2014 - 17/06/2015",
	"Horaire: Mercredi 14H00 – 15H30，15H45 – 17H15",
	"Professeur: Mme Zhu",
	"Contact：01 41 24 41 42(Mme Chen)/ 06 64 85 15 19(Mme Zhu)",
	""),
)
);
?>