<?php
$ALBUM_ITEM_NAME  = array(
	array("2014年夏令营", "2014年夏令营生活", "2014 Stage linguistique d'été", 28, "2014-07-07", "2014-08-02", "summer2014.jpg", 0,
		array("",
),
		array("",
)),
	array("2015年夏令营", "2015年夏令营生活", "2015 Stage linguistique d'été", 25, "2015-07-05", "2015-07-29", "depart.jpg", 0,
		array("",
),
		array("",
)),
	array("2016年夏令营", "2016年夏令营生活", "2016 Stage linguistique d'été", 31, "2016-07-03", "2016-08-02", "greatwall650-380.jpg", 0,
		array("",
),
		array("",
)),
	array("2017年金鸡迎春嘉年华相册", "2017年金鸡迎春嘉年华相册", "Album de la Fête du Printemps - Nouvel An chinois ", 2, "2017-01-21", "2017-01-22", "LED.jpg", 1,
		array("欧洲时报文化中心再度联手欧洲时报旗下法语网站Chine-info，于2017年1月21、22日为中法朋友献上一场喜气洋洋的新春活动 —— 2017年“金鸡迎春嘉年华”。",
"在欧洲时报文化中心，过精彩纷呈、开心愉悦的中国年！",
),
		array("Suite au succès de l'édition de 2016, le Centre Culturel les Amis de Nouvelles d'Europe organise de nouveau, en partenariat avec Chine-info.com, la Fête du Printemps le week-end du 21 et 22 janvier 2017, à l'occasion du Nouvel an chinois qui débutera le 28 janvier, accueillant l'année du Coq de feu.",
)),
);

?>

