<?php
 $ASSO_NEWS4 = array(
"Une Sortie du Printemps est organisée par l’APELCF",
"APELCF a organisé une sortie à Amiens et dans ses environs",
"",
"30 mai 2014",
array(
),
array(
"<IMG src='".$PHOTO_PATH."wenyunews/Amiens600x400.jpg' width=500>",
"L’Association pour la Promotion de l’Education de la Langue chinoise en France (APELCF) a organisé une sortie à Amiens et dans ses environs.  Bien que la pluie menaçait, les parapluies et les imperméables ont été inutiles.", 
"Dès son arrivée à Amiens, le groupe a visité les hortillonnages dans des barques à cornets dotées de moteurs électriques. Les hortillonnages sont des jardins flottants entourés d’eau provenant de la Somme et de son affluent l’Avre. Les hortillonnages amiénois sont inscrits à l'Inventaire national des Sites et l'UNESCO envisage leur classement comme site d'intérêt mondial. Après cette visite, la plupart des membres ont profité du moment du repas pour visiter le centre d’Amiens et de sa cathédrale, plus vaste cathédrale de France par ses dimensions intérieures, de style gothique classique, inscrite depuis 1981 au patrimoine mondial de l’UNESCO.", 
"Le groupe s’est retrouvé pour visiter la maison de Jules Verne qui avait épousé une Amiénoise et qui a passé les dernières années de sa vie dans cette ville. Il a écrit en 1879 le roman d’aventures « Les Tribulations d'un Chinois en Chine » bien qu’il n’ait jamais été en Chine. Après cette visite instructive, le groupe s’est rendu sous terre (à -33 mètres sous terre) pour visiter à quelques kilomètres d’Amiens la ville souterraine de Naours. Cet immense site souterrain creusé dans le calcaire du plateau picard est remarquablement organisé et reconnu comme l’un des plus vastes du Nord de la France. Cette cité a servi de refuge pour les habitants depuis le Moyen Âge, puis lieu de contrebande sous la Révolution Française, hôpital de l'armée britannique lors de la Première Guerre mondiale, puis dépôt de munitions stratégique de l'armée allemande pendant la Seconde Guerre mondiale.",
"Le groupe est rentré après sur Paris après cette journée instructive et bien remplie.", 
"<IMG src='".$PHOTO_PATH."wenyunews/Cathedrale_Amiens600.jpg' width=500>",
"")
);
?>