<?php
 $ASSO_NEWS2 = array(
"La clôture du stage de la Ruche Culturelle Chinoise",
"",
"",
"4 janvier 2014",
array( ),
array(
"<IMG SRC='".$PHOTO_PATH."huodong/leyuan2014-1.jpg' width=500>",
"Le stage de la Ruche Culturelle Chinoise 2013 de Paris organisé par le bureau des affaires des Chinois d’outre-mer, assisté par le bureau des affaires des Chinois d’outre-mer de la province du Zhejiang et l’Association pour la Promotion de l’Éducation de la Langue chinoise en France s’est achevé le 4 janvier. ",
"Des centaines d’adolescents (principalement d’origine chinoise) ont suivi les cours de peinture chinoise, de calligraphie, de danse tibétaine, d’arts martiaux, de sculpture de pâte de riz etc. Pendant 15 jours, cela leur a permis de ressentir le charme de la culture chinoise. ", 
"<IMG SRC='".$PHOTO_PATH."huodong/leyuan2014-3.jpg' width=500>", 
"<IMG SRC='".$PHOTO_PATH."huodong/leyuan2014-4.jpg' width=500>", 
"Les 11 enseignants de niveau supérieur sélectionnés par le bureau des affaires des Chinois d’outre-mer de la province Zhejiang ont donné 120 cours, riches de contenus diversifiés. ", 
"<IMG SRC='".$PHOTO_PATH."huodong/leyuan2014-2.jpg' width=500>", 
 "")
);
?>