<?php
include ("jlpage_75_s.inc");
include ("jl_news24_3_s.inc");
include ("wy_news12_s.inc");
include ("jl_news22_s.inc");
include ("jl_news19_s.inc");
include ("jl_news_sf_s.inc");
include ("jl_news_ml_s.inc");
include ("jl_news_expo_s.inc");
include ("jl_news_db_s.inc");
/*
include ("jl_news6_s.inc");
include ("jl_news8_s.inc");
include ("jl_news5_s.inc");
include ("jl_news12_s.inc");
include ("jl_news13_s.inc");
include ("jl_news14_s.inc");
include ("jl_news16_s.inc");
include ("jl_news3_s.inc");
include ("jl_news7_s.inc");
include ("jl_news9_s.inc");
include ("jl_news10_s.inc");
include ("jl_news11_s.inc");
include ("jl_news17_s.inc");


*/
?>

