<?php
 $JL_NEWS13_s = array(
"文化中国•名家讲坛",
array("jiaoliunews/jiangtan600x450.jpg",	 "文化中国•名家讲坛",	 "JL_NEWS13_sp"),
array("受国务院侨务办公室委托，湖南省外事侨务办公室承办的“文化中国*名家讲坛”团将于5月27日下午14点半在欧洲时报文化中心举办讲座。", "本次名家讲坛由湖南省委宣传部原副部长、第六届省社科联主席、电视剧《雍正王朝》总监制郑佳明和省作家协会主席、《曾国藩》作者唐浩明两位专家担任讲坛主讲嘉宾。郑佳明教授的讲座主题为：戏里戏外说雍正，唐浩明教授将就曾国藩的家庭教育与观众进行探讨。", ""),
$JL_NEWS13_sp,

array(
"Culture chinoise • Conférence d’Experts",
array("jiaoliunews/jiangtan600x450.jpg", "Culture chinoise • Conférence d’Experts"),
array(
"La conférence comportera deux thèmes :", 
" — un thème sur la «Dynastie Yongzheng», célèbre série télévisée de l’année 1998, animée par le Directeur de la série M. ZHENG Jiaming", 
" — un thème sur l’éducation familiale de ZENG Guofan, par le Professeur TANG Haoming. ", 
"<b>Conférencier : </b>M. ZHENG Jiaming et M. TANG Haoming",
"<b>Date : </b>Mardi 27 mai 2014  14h-17h",
"<b>Lieu : </b>Centre Culturel de Nouvelles d’Europe: 48-50，Rue Benoît Malon, 94250 Gentilly",
),
$JL_NEWS13_sp
),
1 // new version with franch
);
?>