<?php
 $JL_NEWS14_s = array(
"«行走大巴黎»新书推介",
array("jiaoliunews/rando600x450.jpg",	 "«行走大巴黎»新书推介",	 "JL_NEWS14_sp"),
array("由旅法文化人张汉钧、旅法作家钟敏合著，重庆大学出版社出版的«行走大巴黎»已在中国面市。此书全彩印刷，图片精美，文字优雅，人文与自然知识丰富，趣味横生。有国内外学者评称“这是一本能提高心智、增进健康的好书。”更有网上介绍“是一本底蕴深厚的海外旅游图书。”", "<b>座谈会时间： </b>2014年5月25日星期日16时—18时,  期间有少量样书惠售。", "<b>地点： </b> 欧洲时报文化中心, 48-50，Rue Benoît Malon, 94250 Gentilly", "座谈会由本书两位作者共同主持，并可即时签书。", ""),
$JL_NEWS14_sp,

array(
"«La marche dans le Grand Paris»",
array("jiaoliunews/rando600x450.jpg", "«La marche dans le Grand Paris»"), //images
array(
"Lors de la table ronde pour la promotion du livre «La marche dans le Grand Paris», et de la projection sur 9 années de randonnées, les deux auteurs Messieurs ZHANG Hanjun et ZHONG Min présenteront leur livre «La marche dans le Grand Paris». Dans ce livre, illustré en couleur avec beaucoup de belles photos, et aux textes élégants et amusants, les auteurs apporteront leurs expériences de randonnées culturelles et naturelles. ",
"<b>Date ： </b>Dimanche 25 mai 2014, 16h-18h", 
"<b>Lieu ： </b> Centre Culturel de Nouvelles d’Europe: 48-50 Rue Benoît Malon, 94250 Gentilly", 
""),
$JL_NEWS14_sp
),
1 // new version with franch
);
?>