<?php
 $JL_NEWS8_s = array(
"迎马年，华法联欢会",
array("jiaoliunews/fete600-480.jpg",	 "迎马年，华法联欢会",	 "JL_NEWS8_sp"),
array("2014年2月16日下午，欧洲时报文化中心在Gentilly新址举办了迎马年，华法联欢会。", "联欢会活动共吸引了包括在中心参加各种活动的学员、学生、学生家长，以及Gentilly的市民300余人参加。Gentilly市政府副市长Michèle Cosnard女士、欧洲时报副社长陈晓燕、法国全国退休老师互助协会的部分退休教师等和大家一起欣赏了丰富多彩的节目。", "演出结束后，大家饶有兴趣地品尝了由参加中心活动的学员们精心准备的美食，不少人还加入到舞会中尽情欢跳。精彩纷呈的节目、地道可口的美食、热闹欢快的舞会让大家对新春的到来充满了欢喜之情。", ""),
$JL_NEWS8_sp,

array(
"Le gala du Nouvel An chinois",
array("jiaoliunews/fete600-480.jpg", "Le gala du Nouvel An chinois"),
array(
"Un gala organisé par l’Association des Amis de Nouvelles d’Europe a lieu le 16 février après midi au nouveau site à Gentilly pour fêter le Nouvel An chinois du Cheval. ", 
"Chaque année, à l’occasion du Nouvel An chinois, l’Association des Amis de Nouvelles d’Europe et la Mutuelle Générale de l’Education Nationale (MGEN) organisent ensemble un gala. Cette année, plus de 300 personnes ont participé à cet événement. Madame Michèle COSNARD, la maire adjointe de Gentilly et Madame Xiaoyan CHEN, la vice-présidente de GUANG HUA MEDIA et des membres de la MGEN ont apprécié ensemble les activités proposées.", 
"En lever de rideau, le gala s’est ouvert sur une performance d’arts martiaux par les enfants, qui a rapidement mis de l’ambiance. Des chansons interprétées par la chorale ont succédé, suivies d’une danse chinoise “La lune sur l’étang de lotus”, puis du mulan avec des éventails. Enfin, la danse traditionnelle Yangge de la classe de chinois a fait monter l’ambiance et tout le monde a bougé, suivant son rythme entraînant. ", 
"Les spectacles, l’exposition, le buffet et le bal ont été très appréciés par tous les participants, qui sont ainsi entrés avec joie dans l’année du Cheval. Bonne année à tous!  ", 
),
$JL_NEWS8_sp,

),
1 // new version with franch
);
?>