<?php
 $JL_NEWS16_s = array(
"关于举办“中国艺术品的鉴定与评估”",
array("jiaoliunews/gxj600.jpg",	 "中国艺术品的鉴定与评估",	 "JL_NEWS16_sp"),
array("针对近年来不断升温的海外中国文物大规模回流以及目前海外“淘宝”队伍的日益壮大的现状，为了提高海外华人的收藏知识和鉴定水平，弘扬中华文化，更好地服务于对中国古董艺术品有兴趣的侨胞，丰富广大旅法华侨华人文化业余生活，在2013年12月成功举办“共建中国艺术品的国际化市场 --- 海外华人收藏的意义及策略”讲座的基础上，今再次特邀中国著名古董鉴定专家、北京华辰拍卖有限公司董事长兼总经理甘学军在巴黎举办“中国艺术品的鉴定与评估”，希望通过讲授经典和面对面的交流，让大家感受中华文化的无穷魅力，增进对中华文化的了解和兴趣。", "", "", "", "<b>主办单位：</b>法国欧洲时报传媒集团", "", "<b>协办单位：</b>法国基石文化", "", "<b>媒体支持：</b>欧时网、法纵网、天工传媒、新欧洲、华人街", "", "<b>主讲嘉宾：</b>甘学军", "", "", "", "<b>附 : 甘学军介绍</b>", "", "甘学军，北京华辰拍卖有限公司董事长兼总经理。1962年出生，湖北仙桃沙湖人，1983年毕业于中国人民大学中文系，曾在文化部和国家文物局工作，于1993年辞去公职从事艺术品拍卖。先后任中国嘉德国际拍卖有限公司副总经理，北京华观文化发展有限公司总经理，北京荣宝拍卖有限公司总经理。2001年创办北京华辰拍卖有限公司。", "", "", "", "", ""),
$JL_NEWS16_sp,

array(
"Identification et l’évaluation de l'art chinois",
array("jiaoliunews/gxj600.jpg", "Identification et l’évaluation de l'art chinois"),
array(
"Au cours des dernières années, de plus en plus de Chinois d’outre-mer s’intéressent au \"Taobao\" (collection d’objets anciens). Afin d'améliorer leur collecte, de les aider à identifier et à évaluer ces objets, M. GAN Xuejun, Président et PDG de Huachen Auction Co. à Beijing, donnera, en langue chinoise, une conférence interactive pour vous enseigner et expliquer le charme de la culture chinoise. À l’issue de la conférence, il sera possible de faire évaluer des objets.", 
"<b>Conférencier ：</b>M. GAN Xuejun", 
"<b>Date ：</b>Samedi 4 juin 2014  15h-18h", 
"<b>Lieu ：</b>Centre Culturel de Nouvelles d’Europe: 50 Rue Benoit Malon 94250 GENTILLY", 
""),
$JL_NEWS16_sp

),
1 // new version with franch
);
?>