<?php
 $JL_NEWS6_s = array(
"新址开幕酒会",
array("spectcocktail/cocktailtitre-600.jpg",	 "新址开幕酒会",	 "JL_NEWS6_sp"),
array("2013年12月15日下午，欧洲时报文化中心在当日上午的新址揭牌仪式后，举办了香槟酒会招待新朋旧友。", "在邀请大家参观设计雅致大方的新馆同时，中心不但以香槟美食相待，更用丰富的图片向大家介绍了文化中心举办的各种群众文化活动。大家欣喜地欢聚一堂，频频举杯，共祝美好未来！", ""),
$JL_NEWS6_sp,

array(
"Pendaison de crémaillère de l’Association des amis de Nouvelles d’Europe", 
array("spectcocktail/cocktailtitre-600.jpg","Pendaison de crémaillère de l’Association des amis de Nouvelles d’Europe"), 
array(
"Après l’inauguration du nouveau Centre culturel dans la matinée du 15 décembre 2013, l’Association des Amis de Nouvelles d’Europe a organisé l’après-midi un cocktail d’ouverture pour pendre la crémaillère. ",
"Le nouveau site se trouve dans un endroit culturel et historique de Gentilly. De nombreux voisins et les anciens amis de l’Association ont été chaleureusement invités à visiter le nouveau bâtiment. ",
"En même temps qu’ils pouvaient déguster le champagne, les invités ont eu un aperçu général de toutes les activités culturelles grâce aux photos exposées. Ils ont porté des toasts pour souhaiter un bel avenir au nouveau Centre culturel."
),

$JL_NEWS6_sp,			


),
1 // new version with franch
);
?>