<?php
 $JL_NEWS24_3_s = array(
"中华文化大乐园优秀才艺学生交流团专场演出",
array("jiaoliunews/dlyspectacle.jpg",	 "中华文化大乐园优秀才艺学生交流团专场演出",	 "JL_NEWS24_3_sp"),
array("2014中华文化大乐园优秀才艺学生交流团法国展演巴黎专场于2014年10月19日下午15点和晚上19点30分在巴黎ISSY会议中心 (Palais des Congrès d'Issy, 25 avenue Victor Cresson 92130 Issy les Moulineaux) 拉开帷幕。由中国国务院侨务办公室主办，湖南快乐出发传媒有限公司承办，欧洲时报传媒集团协办的这两场演出，聚集了从国内选拔出来的19名6岁到21岁的优秀青少年，他们为大家呈现了一台歌舞、乐器、杂技、京剧、川剧变脸及武术等精彩节目.", "这些传播中华文化精髓的小使者，用他们辛勤的汗水、精湛的技艺、完美的演出，赢得了在场所有师生和热爱中国文化的法国朋友的一阵阵热烈掌声。", "", "", "", "", ""),
$JL_NEWS24_3_sp,

array(
"Gala des jeunes talents artistiques chinois (Paris)",
array("jiaoliunews/dlyspectacle.jpg",	 "Gala des jeunes talents artistiques chinois (Paris)",	 "JL_NEWS24_3_sp"),
array("Dans le cadre des échanges culturels entre la Chine et la France, un spectacle a eu lieu à Paris le dimanche 19 octobre 2014 au Palais des Congrès d'Issy (25 avenue Victor Cresson 92130 Issy les Moulineaux) à 15H et à 19H30.", "Son but est de contribuer au développement de l'intérêt pour la connaissance de la culture chinoise, ainsi qu'au dialogue entre les jeunes chinois et étrangers.  ", "Ce spectacle exceptionnel regroupe 19 jeunes talents de 6 ans à 21 ans qui ont fait une démonstration de leurs dons.", "Bravo ces jeunes talents !", "", "", "", ""),
$JL_NEWS24_3_sp
),
1 // new version with franch
);
?>