<?php
 $JL_NEWS5_s = array(
"中欧华文传媒高峰对话",
array("confmedia/titre-600.jpg",	 "中欧华文传媒高峰对话",	 "JL_NEWS5_sp"),
array("2013年12月15日，“中欧华文传媒高峰对话”在法国巴黎欧洲时报文化中心新址隆重开幕。此次高峰对话由欧洲华文传媒协会主办、欧洲时报承办，来自欧洲近十个国家十多家华文媒体及中国驻法主要媒体负责人齐聚一堂。", "正在法国访问的中国国务院侨务办公室何亚非副主任出席并做了中心发言。出席高峰对话的法国历史学家及政治专家分别就自己关心的方面提出了问题，何亚非副主任在回答问题的同时，也给法国友人深入准确地解读了国家相关政策。", ""),
$JL_NEWS5_sp,

array(
"L’inauguration du symposium en média entre la Chine et l’UE", 	
array("confmedia/titre-600.jpg",	"L’inauguration du symposium en média entre la Chine et l’UE",	 "JL_NEWS5_sp"),
array("Le symposium en média entre la Chine et l’UE, organisé par l’Association des Médias chinois d’outre-mer en Europe, entrepris par GUANG HUA MEDIA, a été inauguré le 15 décembre 2013. Les directeurs et les chefs de rédactions des entreprises de presse en langue chinoise éditant en Europe (la France, la Grande-Bretagne, l’Allemagne, l’Espagne, le Portugal, la Hongrie…) se sont réunis au le Centre culturel de Nouvelles d’Europe et ils ont eu un dialogue chaleureux avec Monsieur HE Yafei, le directeur adjoint du bureau des affaires des Chinois d’outre-mer.",
"Monsieur HE Yafei et tous les participants ont étudié les moyens d’améliorer la presse en chinois à l’étranger après la troisième session plénière du 18ème comité central du Parti Communiste chinois.",

"En répondant aux questions posées par des historiens et des experts français en politique, Monsieur HE a donné ders précisions pertinentes sur la politique chinoise. ",
),
$JL_NEWS5_sp
),
1 // new version with franch
);
?>

