<?php
 $JL_NEWS11_s = array(
"著名画家张剑峰作品世界巡回展",
array("expo/zhang600x400.jpg",	 "著名画家张剑峰作品世界巡回展",	 "JL_NEWS11_sp"),
array("值中法建交50周年之际，画坛奇才、齐派第三代传人，中国当代著名画家张剑峰将于4月16日至17日，在欧洲时报文化中心二楼展厅举办其作品世界巡回展《中国梦 世界梦》。", "画展开幕酒会定于4月16日18时举办。", "张剑峰先生是已故国画大师娄师白先生的亲传弟子，其作品水墨淋漓，洋溢着自然界生机勃勃的气息，独出手眼、卓尔不群，极富创造性。", "巴黎中国文化中心、欧洲时报文化中心首度联手，隆重推荐！", "欢迎大家的光临！", ""),
$JL_NEWS11_sp,

array(
"Exposition des peintures de Zhang Jianfeng", 
array("expo/zhang600x400.jpg", "Exposition des peintures de Zhang Jianfeng"),  
array(
"Exposition des peintures de Zhang Jianfeng «Le rêve de Chine, le rêve du Monde» du 16 avril au 17 avril 2014", 
"ZHANG Jianfeng, célèbre peintre chinois, représente la troisième génération d’élèves du peintre Maître QI Baishi. Ses œuvres réalisées dans la plus grande concision ont beaucoup de charme ses représentations de paysages et d’animaux tels que des poissons, des coqs, évoquent la richesse et le bonheur. ", 
"Venez vite admirer son talent et ses œuvres exceptionnelles!",
),
$JL_NEWS11_sp
),
1 // new version with franch
);
?>