<?php
$JL_NEWS10_s = array(
"中国重庆武隆国家公园（巴黎）大型图片展", 
array("expo/wulong600-480.jpg", "中国重庆武隆国家公园（巴黎）大型图片展", "JL_NEWS10_sp"),  
array(
"武隆位于中国重庆市东南部乌江下游，有汉族、苗族、土家族、仡佬族等13个民族，幅员面积2901平方公里，41万人，是中国少数几个同时拥有“世界自然遗产”、“国家5A级旅游景区”两块金字招牌的国际旅游目的地。",
"武隆是世界喀斯特生态博物馆，县域全境260多处精美景点将建成“中国武隆公园”。包括：地下艺术宫殿和洞穴科学博物馆——芙蓉洞，水上喀斯特森林——芙蓉江，落在凡间的伊甸园——仙女山，世界规模最大、最高的串珠式天生桥群——天生三硚，峡谷地质奇观——龙水峡地缝，世界唯一的冲蚀型天坑——后坪天坑，天然生物基因库——白马山，水墨山水画廊——乌江。此外，万峰林海、鸭江小三峡、神奇大洞河、黄莺大峡谷、天星竖井群等景点，更是深闺不漏，秀色天然。",
"武隆山奇水秀、神秘旖旎，展示了大自然的完美，被誉为“自然的遗产  世界的武隆”，已经成为吸引人类注意力的一片神秘之地，期待着世界各国朋友们的到来。",
"“中国武隆公园”欢迎您！"
),
$JL_NEWS10_sp,

$JL_NEWS10_s = array(
"Parc national de Wulong à Chongqing", 
array("expo/wulong600-480.jpg", "Exposition des photos (Paris) du Parc national de Wulong à Chongqing"),  
array(
"La ville de Wulong est située au sud-est de Chongqing, dans le sud de la Chine. Elle est connue comme «Patrimoine naturel du monde» et attire plus en plus de touristes par son relief karstiqu« et ses paysages mystérieux.  ", 
"L'exposition donne une vue panoramique sur cette terre merveilleuse. ", 
),
$JL_NEWS10_sp
),
1 // new version with franch
);
?>