<?php
 $JL_NEWS7_s = array(
"《活佛父子镜头下的西藏今昔》摄影图片展",
array("jiaoliunews/expo600-480.jpg",	 "活佛父子镜头下的西藏今昔",	 "JL_NEWS7_sp"),
array("2014年2月16日下午，《活佛父子镜头下的西藏今昔》摄影图片展在欧洲时报文化中心展出。", "西藏第一位摄影家活佛十世德木•丹增加措及其子——西藏摄影家协会主席德木•旺久多吉，用镜头记述了新旧西藏社会的变迁。十世德木活佛是清王朝册封的西藏四大活佛之一，于青年时因缘际会接触到相机，遂拍下数十万张底片，以细腻的触感记录下旧西藏社会的点滴。父子两代以影像衔接记录了20世纪乃至21世纪的西藏。摄影展展出作品前后跨度80多年，透过父子俩的镜头，人们能更直观地认识西藏的历史、现实与变化。", ""),
$JL_NEWS7_sp,

array(
"Le présent et le passé du Tibet sous la caméra de Bouddha Vivant et son fils",
array("jiaoliunews/expo600-480.jpg",	 "la caméra de Bouddha Vivant et son fils",	 "JL_NEWS7_sp"),
array(
"L’exposition des photos ‘Le présent et le passé du Tibet sous la caméra de Bouddha Vivant et son fils’ est ouverte le 16 février après midi. ", 
"Toutes les photos exposées sont les travaux du premier photographe tibétain – Bouddha Vivant Demu X – et de son fils, le président de l’Association des Photographes Tibétains. Par leurs photos, ils ont raconté plus de 80 ans de l’histoire du Tibet du 20ème au 21ème siècle.",
"Conviée pour le gala du Nouvel An chinois, Mme Michèle COSNARD, maire adjointe de Gentilly, déclare que l’exposition de ces images précieuses ouvre, pour le visiteur, une fenêtre à la compréhension de la vie locale tibétaine. Cette exposition permet aux résidents de Gentilly de mieux connaître la Chine, et particulièrement le Tibet. ", 
"Les photos seront exposées jusqu’au 10 mars. Entrée libre.", 
),
$JL_NEWS7_sp
),
1 // new version with franch
);
?>