<?php
 $JL_NEWS12_s = array(
"苏曼殊：中国僧侣诗人，“情僧”",
array("jiaoliunews/sumanshu600x400.jpg",	 "苏曼殊：中国僧侣诗人",	 "JL_NEWS12_sp"),
array("作为第一个将雨果的《悲惨世界》译成中文的翻译家，苏曼殊短暂的一生充满着传奇。", "混血儿？私生子？僧人？情种？诗人？画家？革命者？ ", "法兰西共和国艺术与文学骑士勋章获得者董纯教授将带您走近苏曼殊，认识一个真实的苏曼殊。", "<b>时间： </b> 2014年5月18日 16点30", "<b>地点： </b> 欧洲时报文化中心 48-50 RUE BENOIT MALON，94250 GENTILLY", ""),
$JL_NEWS12_sp,


array(
"SU Manshu, un moine poète chinois",
array(
	"jiaoliunews/sumanshu600x400.jpg", "SU Manshu, un moine poète chinois"
),
array(
"SU Manshu, écrivain, peintre et journaliste, est le premier traducteur du roman de Victor Hugo «Les Misérables».",
"Le Professeur DONG Chun va montrer la véritable personnalité de SU Manshu.",
"<b>Date : </b>Mardi 18 mai 2014  16h30",
"<b>Lieu : </b>Centre Culturel de Nouvelles d’Europe: 48-50，Rue Benoît Malon, 94250 Gentilly",

),
$JL_NEWS12_sp
),
1 // new version with franch
);
?>