INSERT INTO oushinews (IDS, TITLE, FTITLE, PUBLIE, STITLE, FSTITLE, RESUME, FRESUME, CONTENTS, FCONTENTS, MAINNEWS, STARS, KONGZI, POSITION, LASTMODIF, NEWSTYPE, TOP5, TOPPHOTOC, TOPPHOTOF, LINKC, LINKF, DELETED) VALUES 
('100', 'eaze', '', '2016-10-12', '', '', '', '', 'azeaz', '', '0', '0', '0', '117', '10/12/2016 - 15:39:29', '0', '0', '', '', '', '', '0');
