<?php
 $WY_NEWS5 = array(
 
 "Les nouvelles classes de la nouvelle année 2014", " ","","3 janvier 2014",
	array(),
array(
"<h5>Danse en Ligne et Sociale</h5>",
"<IMG SRC='".$PHOTO_PATH."school/dance1.jpg' width=500>",	
"Cette danse américaine permet d’évoluer avec des pas de danse de salon, sous forme de danse en ligne. Cette danse collective et sociale est non seulement bonne pour mise en forme, mais crée aussi une ambiance très chaleureuse.",
"La nouvelle classe de Danse en Ligne et Danse Sociale va commencer à partir du 9 janvier 2014 jusqu’au 3 avril 2014 pour une durée de 3 mois. ",

"Les cours proposés sont : la danse en ligne, la danse duo et la danse sociale etc. ",
"<b>Horaires </b>:  jeudi 14h30 - 16h00 (première séance) ; 16h00 - 17h30 (deuxième séance) ",
"<b>Professeurs </b>: Mme WU Xue Xuehui et M. Wu Ganwen ",
"<b>Contacts </b>: 06 06 59 79 73 (Mme WU XUE) / 01 41 24 41 42 (Madame Chen) ",

"<h5>Classe de Fitness et danses chinoises</h5>",
"<IMG SRC='".$PHOTO_PATH."school/dance2.jpg' width=500>",
"Les femmes modernes font attention à leur corps et à leur élégance ; le fitness et la danse chinoise les aideront à améliorer leur ligne.",
"Deux classes seront ouvertes de février à juin pour une durée de 4 mois et demi",
"<b>Horaires </b>: mercredi 15h15 - 16h45 (du 5 février 2014 jusqu’au 18 juin 2014) ;  ",
"dimanche 10h30 - 12h00 (du 9 février 2014 jusqu’au 22 juin 2014). ",
"<b>Professeur </b>： Mlle LU Dong  ",
"<b>Contact </b>: 01 41 24 41 42 ou 01 41 24 41 40 (Madame Chen) ",

"<h5>Classe de yoga </h5>",
"<IMG SRC='".$PHOTO_PATH."school/yoga.jpg' width=500>",	
"Le yoga est à la fois une science et un sport efficace et sans danger, si l’on prend soin de suivre un échauffement avant de le pratiquer. Le professeur, certifié et qualifié, guidera les élèves dans la maîtrise des exercices.",
"Deux classes de yoga seront ouvertes : une classe le samedi matin et l’autre le samedi après-midi. Ces deux classes commenceront le 8 février et finiront le 21 juin. ",
"Horaires: 10h30 - 12h00, 13h30 - 15h00  ",
"<b>Professeur </b>: Mme ZHU Yuxia ",
"<b>Contact </b>: 01 41 24 41 42 ou 01 41 24 41 40 (Madame Chen) ",
"<div class=note_title><h1>Places limitées !</h1></div>",
)

);
?>