<?php
 $WY_NEWS19 = array(
"Cours de Qi Gong-Ba Duan Ji",
"Le Qi Gong est une discipline où s'harmonise le corps, la respiration et l'esprit pour une",
"",
"Le 16 décembre 2014",
array(
),
array(	"<IMG src='".$PHOTO_PATH."wenyunews/qigong.PNG' width=500>   ",
	"Le Qi Gong est une discipline où s'harmonise le corps, la respiration et l'esprit pour une meilleure gestion de votre vitalité quotidienne.",
	"Le &quot;Ba Duan Jin&quot; est un des plus anciens et des plus traditionnels enchaînements de Qi Gong. Il est pratiqué en Chine depuis des siècles.",
	"Dans ce cours, vous pratiquerez principalement un enchaînement traditionnel : « Les huit pièces de brocard » (Ba Duan Jin) tel que le transmettent les experts de « l'Association chinoise du Qi Gong pour la santé ». ",
	"Cet enchaînement de huit mouvements a pour avantage d'être simple et facile à pratiquer. Il est prouvé que sa pratique permet d'améliorer les fonctions du système neuro-hormonal, de favoriser la circulation de l'énergie et du sang, d'augmenter la force des muscles, et de masser profondément les organes internes. Il exerce donc une réelle influence sur la prévention des maladies et l'amélioration de la santé.",
	"Date : du 10 janvier 2015 à fin juin 2015",
	"Horaire : Vendredi   12h30 – 13h30",
	"Professeur : Chrystel",
	"Contactez ：06 81 23 99 78（Chrystel）/ 01 41 24 41 41	（Mme XU）		",
	"<a href='http://www.freres-d-ames.fr' target='_blank'>Lien utile</A> ",
	""),
);
?>