<?php
 $WY_NEWS14 = array(
"Le cours de Yoga commence",
"Plus en plus de gens pratiquent le Yoga pour se perfectionner et aussi pour avoir une vie saine",
"",
"le 5 septembre 2014",
array(
),
array("<IMG src='".$PHOTO_PATH."wenyunews/yoga2.JPG' width=500>", "Maintenant  de plus en plus de gens pratiquent le Yoga pour se perfectionner et aussi pour avoir une vie saine.", " Dans la pratique du yoga, la chose essentielle est la respiration. Nous travaillons beaucoup sur la respiration, comment se concentrer, comment observer sa respiration et comment faire et comment  se positionner  etc.", "Venez nombreux, vous trouverez de changement magnifique à travers la pratique du Yoga.", "", "Professeur : Mme Rebeyrolle Zhu (Certificat du YOGA Intermédiaire Instructeur de Hong Kong)", "Date : du 13 septembre 2014 au janvier 2015", "Horaire : Samedi   10h30 – 12h00    13h30 –  15h00", "Contact ：01 41 24 41 42", "<IMG src='".$PHOTO_PATH."wenyunews/yoga3.jpg' width=500>"),
);
?>