<?php
 $WY_NEWS18 = array(
"Ouverture d’une nouvelle classe de danse",
"A partir du 10 janvier 2015, une nouvelle classe de danse ouvrira spécialement pour adul",
"Danse en Ligne（adulte & débutant）",
"Le 16 décembre 2014",
array(
),
array(	"<IMG src='".$PHOTO_PATH."wenyunews/danse M.png' width=500> ",
	"	Vous aimeriez danser, mais vous ne savez pas ?",
	"	Vous souhaitez apprendre à danser ?",
	"	Danser est une joie et une activité sportive.",
	"A partir du 10 janvier 2015, une nouvelle classe de danse va ouvrir spécialement pour adulte débutant tous les samedis 14H—15H (prolongation d’une 1/2H possible). ",
	"<span class='spanarticle'> 3 cours d’essai gratuits ! </span>",
	"Explications claires, apprentissage progressif，découverte de la joie de danser!",
	"（les inscriptions pour les cours de Danse en ligne (sociale & country) niveau intermédiaire de 15H/16H et de Danse de salon niveau intermédiaire / avancé  de 16H/18H sont encore ouvertes）",
	"Date : du 10 janvier 2015 au 4 juillet 2015",
	"Horaire : samedi 14H-15H",
	"Professeurs : M. Kim LIM & Mme Jenny LIM",
	"Contact : 06 29 46 50 91 (M. LIM)、06 99 68 98 25 (Mme LIM)",
	"          01 41 24 41 42/44（Mme CHEN）",
	""),
);
?>