<?php 

$WY_NEWS2 = array(
"Les élèves de la classe de Moulan Quan sont en train de faire la vidéo du concours", 
" ","","le 15 janvier 2014",
array(),
array(	
"<IMG SRC='".$PHOTO_PATH."mulan.jpg' width=500>",
"Le concours international de Mulan Quan de 2013 est un grand challenge et une opportunité de tester son niveau pour tous les amateurs et praticiens de Mulan Quan. ", 
"Dirigés par un professeur de plus de 80 ans, les élèves de la classe de Mulan Quan de l’Association des amis de Nouvelles d’Europe s’entraînent avec assiduité pour ce concours. Les photographes professionnels sont invités à les filmer afin d’avoir une bonne qualité de vidéo. Neuf performances individuelles et une performance collective ont été sélectionnées pour ce concours. Elles concernent des démonstrations avec ou sans armes, comme l’éventail, l’épée, le couteau ou le cercle. Les vidéos ont été déjà envoyées. Les participants sont impatients dans l’attente des résultats."
),

);
?>