<?php
 $WY_NEWS4 = array(
 
 "Préparation assidue de la chorale pour la fête du printemps chinois", 
 " ","","8 janvier 2014",
array(),
array(
"<IMG SRC='".$PHOTO_PATH."school/hechangtuan.jpg' width=500>",
"Les chorales sont toujours très chargées à chaque occasion d’événement important comme le Nouvel An chinois. Elles sont invitées à participer à la messe de salutation organisée par la mairie du 13e arrondissement. Ils vont également chanter pour le gala du nouvel an chinois du cheval. ",
"Les chorales sont très actives dans la communauté chinoise et elles ont déjà participé à de nombreux spectacles. Malgré leur expérience, elles s’entraînent consciencieusement pour chaque événement proposé. Elles sélectionnent les chansons et font la répétition attentivement afin de montrer les meilleures performances. ",
"<IMG SRC='".$PHOTO_PATH."school/hechangtuan2.jpg' width=500>",
"Beaucoup de membres de la chorale sont venus de l’Asie du Sud-Est, et ils sont en France depuis de nombreuses années. Grâce à leur passion de la musique et leur sentiment profond pour leur pays natal, ils se réunissent chaque dimanche. Ils participent à de nombreux spectacles et sont devenus des représentants de la communauté chinoise à Paris. La fête comme celle du Nouvel An chinois nous fait toujours penser à la famille absente. Les choristes expriment leurs bénédictions à leur famille et leurs meilleurs vœux pour la Chine à travers leur voix. " 
)		 
);
?>