<?php
 $WY_NEWS17 = array(
"Danse à Samedi",
"Danse de salon,plusieurs niveaux à vous proposer par les professeurs Monsieur et Madame Lin","",
"le 16 septembre 2014",
array(
),
array("<IMG src='".$PHOTO_PATH."wenyunews/dansesamedi.jpg' width=500>", "Danse de salon,plusieurs niveaux à vous proposer par les professeurs Monsieur et Madame Lim.", "", "14H—15H : Débutant, Country et Duo Danse", "15H—16H : Intermédiaire， Country et Duo Danse", "16H—17H : Danse de salon (Rumba, Jitterbug，Rock，Valse)", "17H—18H : Danse de salon（Bachata，Tango，Valse-Viennoise)，& Danse Pratique", "", "Contact：06 29 46 50 91 (M. LIM)/06 99 68 98 25 (Mme LIM)、", "Centre culture: 01 41 24 41 42/44（Mme Chen）", "", ""),
);
?>