<?php
 $WY_NEWS1 = array(
 "L'inscription des formations d'informatique", 
 "Formation d'informatique et d’E-commerce","", 
 "Le 6 février 2014",
	array(),
	array(
"<h5>Formation d'informatique pour les débutants</h5>",
"Les ordinateurs ont désormais un rôle essentiel dans nos vies ou à notre travail, et cela concerne également les personnes âgées. ",
"Une classe de premier niveau est proposée pour en apprendre l'utilisation aux débutants. Un ordinateur est mis à la disposition de chaque élève. L'enseignant vous emmènera pas à pas dans le monde de l'informatique. Les cours portent sur les applications pratiques, dont l'Internet, l'écriture et l’envoi des e-mails, l'installation et le téléchargement des logiciels et des outils antivirus, la transmission des données numériques d'un appareil photo, etc. Apprendre à entrer des caractères chinois par Pinyin vous sera également proposé.",
"<IMG SRC='".$PHOTO_PATH."school/infoavance.jpg' width=500>",
"La classe commencera le 23 mars 2014 et finira le 20 juin pour une durée de trois mois. ",
"<b>Horaires </b>: dimanche 10h30 - 11h30 (Pinyin), 11h30 - 13h00",
"<b>Contact </b>: 01 41 24 41 42 ou 01 41 24 41 40 (Madame Chen)",

"<h5>Formation d'informatique pour les non-débutants</h5>",
"Durant 10 semaines, ceux qui ont une certaine base d'informatique pourront bénéficier d’un cours flexible selon les besoins de chacun : requêtes Google Maps, Facebook, QQ, création de blogs n’auront plus de secrets pour vous, de même que d’autres applications ou logiciels bureautiques, ainsi que des fonctions avancées de messagerie, de téléchargements de musique ou de films. Chaque élève aura un ordinateur à sa disposition.",
"<IMG SRC='".$PHOTO_PATH."school/infodebutant.jpg' width=500>",
"Cette classe commencera le 23 mars 2014 et finira le 6 juin pour une durée 10 semaines. ",
"<b>Horaires </b>: dimanche 14h30 - 16h30 ",
"<b>Contact </b>: 01 41 24 41 42 ou 01 41 24 41 40 (Madame Chen)",

"<h5>Formation d’E-commerce</h5>",
"Près de 17 millions de Français, et plus de 80 millions de Chinois font leurs achats sur internet. En 6 semaines, le professeur  aidera les hommes d'affaires chinois en France, qui ont une certaine base en informatique, à organiser leurs ventes en ligne. Un ordinateur est affecté à chaque élève.",
"Cette classe commencera le 26 avril 2014 et finira le 31 mai 2014 pour une durée de 6 semaines.",
"<b>Horaires </b>: samedi 15h30 - 17h30 ",
"<b>Contact </b>: 01 41 24 41 42 ou 01 41 24 41 40 (Madame Chen)",
)
 
);
?>