<?php
 $WY_NEWS11 = array(
"Une démonstration de Mulan Quan dans la maison de long séjour",
"un spectacle pour les personnes âgées de la maison de long séjour",
"",
"11 juin 2014",
array(
),
array("Les élèves du Mulan de l’Association des Amis de Nouvelles d’Europe ont donné un spectacle pour les personnes âgées de la maison de long séjour de l’ Hôpital Louis Mourier à Colombe, au nord de Paris. ", "<IMG SRC='".$PHOTO_PATH."wenyunews/mulan_retraite600.jpg' width=500>", "Avec leur professeur Madame WANG Xianqin, ils ont préparé un programme riche et varié : «Les papillons multicolores tourbillonnement », deux cerceaux « Nezha sonde la mer », l’éventail armé « Le parfum des fleurs de pêches », l’éventail fortifié « La santé de Mulan », l’éventail de « Os de dragon », « Parfum de Mulan» et l’éventail en soierie longue. Les personnes âgées ont beaucoup applaudi et apprécié cette démonstration de l’art martial chinois.", " L’amour est sans frontière, et les élèves souhaitent sincèrement aux personnes âgées des vœux de bonne santé et de longévité.", ""),
);
?>