<?php
 $WY_NEWS3 = array(
 
 "L'inscriptions pour les nouvelles classes à partir de février", 
 " ","","le 14 janvier 2014",
array(),
array(
"<h3>La classe de la calligraphie et de la peinture chinoise</h3>", 
"La calligraphie et la peinture chinoises ont une histoire commune vieille de milliers d'années, et représentent la quintessence profonde de la Chine. Pratiquer l’art de la calligraphie c’est non seulement se cultiver, mais c’est aussi le plaisir d'acquérir de l'élégance et la paix de l’âme. L'enseignement est très personnalisé.",
"<IMG SRC='".$PHOTO_PATH."school/shufa-600.jpg' width=500>",
"La classe commencera le 9 février 2014 et finira le 22 juin 2014, pour une durée de 4 mois et demi.  ",
"<b>Horaires : </b> dimanche 10h30 - 12h00",
"<b>Professeur ：</b> M. Jianhong MA, calligraphe chinois connu, habitant en France, président de l'Association le Pinceau d’Or. ",
"<b>Contact  ：</b> 01 41 24 41 42 ou 01 41 24 41 40 (Madame Chen)",
" ",
)
			 
);
?>