<?php
 $WY_NEWS8 = array(
"Stage linguistique d'été 2014",
"Beijing et Mongolie intérieur ",
"",
"11 avril 2014",
array(
),
array(
"<h5>Groupe 1 : Beijing   </h5>", "<IMG SRC='".$PHOTO_PATH."huodong/greatwall600-480.jpg' width=500>", "<ol class=listarticle>
<li><b>Date ：  </b> 07/07-02/08, 26 jours</li>
<li><b>Âge： </b> de 12–17 ans （en bonne santé）   </li>
<li><b>Cours ： </b> Cours de chinois, peinture, origami, ping-pong, natation, visites des monuments de Beijing…</li>
<li><b>Frais ： </b> 2100 euros（visa non inclus）     </li></ol>", "<h5>Groupe 2 : Beijing et Mongolie intérieur</h5>", "<IMG SRC='".$PHOTO_PATH."huodong/V1mongolie600-480.jpg' width=500>", "<ol class=listarticle>
<li><b>Date ：  </b> 07/07-02/08, 26 jours</li>
<li><b>Âge： </b> de 12–17 ans （en bonne santé）   </li>
<li><b>Cours ： </b> Cours de chinois, peinture, origami, ping-pong, natation, visites des monuments de Beijing…</li>
<li> Voyage en train pour la Mongolie-Intérieure, pour découvrir un autre monde…</li>
<li><b>Frais ： </b> 2300 euros（visa non inclus）     </li></ol>", "", "<b>Remarques ： </b> fournir une copie du passeport avec le règlement des frais de réservation de 200 euros en espèces ou par chèque à l'ORDRE : Association Des Amis de Nouvelle d'Europe ", "<b>Fiche à envoyer à ： </b>  ", "<span class=spanarticle> Association Des Amis de Nouvelle d'Europe</span>", "<span class=spanarticle> 50 RUE BENOIT MALON  94250 GENTILLY</span>", "<b>Renseignements：  </b> ", "<span class=spanarticle>Tel :  01 41 24 41 42 / 44 / 40 </span>        ", "<span class=spanarticle>Fax: 01 41 24 41 49   </span>", "<span class=spanarticle>Email : <a href='mailto:chenxiaojing@oushinet.com'>chenxiaojing@oushinet.com</a> ou <a href='mailto:ecole@oushinet.com'>ecole@oushinet.com</a></span>", 
" ", 

"")
);
?>