<?php
 $WY_NEWS12 = array(
"Festival de Quyi de Chine à Paris",
"le 3ème Festival des arts chinois du divertissement à Paris débutera le 30 juin",
"",
"15 juin 2014",
array(
),
array("<IMG width=500 src='".$PHOTO_PATH."wenyunews/quyi600.jpg'>", "A l’occasion du 50ème anniversaire de l’établissement des relations diplomatiques entre la France et la République populaire de Chine, le 3ème Festival des arts chinois du divertissement à Paris débutera le 30 juin à l’Espace Pierre Cardin (1-3, avenue Gabriel 75008 PARIS). ", "", "<b>Organisateurs : </b> Association des Artistes de Quyi de Chine; le Centre culturel de Chine à Paris", "<b>Co-organisateurs : </b> Journal de Nouvelles d’Europe; Association des Commercants Chinois en France", "<b>Date du spectacle : </b>lundi 30 juin 2014 ", "<b>Lieu du spectacle : </b>Espace Pierre Cardin, 1-3, avenue Gabriel 75008 PARIS", "", "<b>Vente des billets au bureau commercial de Nouvelles d’Europe</b>", "<b>Adresse： </b>90 -92 avenue de Choisy 75013 PARIS", "<b>Information： </b> 01 53 82 78 94", "", ""),
);

$WY_NEWS12_s = array(
"Festival de Quyi de Chine à Paris",
array("wenyunews/quyi600.jpg", "Festival de Quyi de Chine à Paris"),
array( "A l’occasion du 50ème anniversaire de l’établissement des relations diplomatiques entre la France et la République populaire de Chine, le 3ème Festival des arts chinois du divertissement à Paris débutera le 30 juin à l’Espace Pierre Cardin (1-3, avenue Gabriel 75008 PARIS). 
", "
", "<b>Organisateurs : </b> Association des Artistes de Quyi de Chine; le Centre culturel de Chine à Paris
", "<b>Co-organisateurs : </b> Journal de Nouvelles d’Europe; Association des Commercants Chinois en France
", "<b>Date du spectacle : </b>lundi 30 juin 2014 
", "<b>Lieu du spectacle : </b>Espace Pierre Cardin, 1-3, avenue Gabriel 75008 PARIS
", ""),
$WY_NEWS12_sp
);

?>