<?php
 $WY_NEWS9 = array(
"Félicitations aux lauréats de la Compétition de Mulan Quan",
"Félicitation aux gagnants des Compétitions internationales de Mulan Quan ",
"",
"29 avril 2014",
array(
),
array("Félicitations aux gagnants des Compétitions internationales de Mulan Quan: ", 
"<IMG SRC='".$PHOTO_PATH."wenyunews/mulan_groupe800x600.jpg' width=500>","Félicitation au club CEGYM-PARIS", "<IMG SRC='".$PHOTO_PATH."wenyunews/mulanquan12.jpg' width=500>", 
"Chrystel,  XING Feiyan,  Hélène, Cynthia", 
"<IMG SRC='".$PHOTO_PATH."wenyunews/mulanjiang2.jpg' width=500>", 
"<IMG SRC='".$PHOTO_PATH."wenyunews/mulanjiang3.jpg' width=500>", 
"<IMG SRC='".$PHOTO_PATH."wenyunews/mulanjiang4.jpg' width=500>", 
"WANG Ying, Aleksandra, Caroline, Petra ", "<IMG SRC='".$PHOTO_PATH."wenyunews/mulanjiang5.jpg' width=500>      ", "<IMG SRC='".$PHOTO_PATH."wenyunews/mulanjiang6.jpg' width=500>  ", "<IMG SRC='".$PHOTO_PATH."wenyunews/mulanjiang7.jpg' width=500>  ", "<IMG SRC='".$PHOTO_PATH."wenyunews/mulanjiang8.jpg' width=500>  ", "Martine; Brigitte ", "<IMG SRC='".$PHOTO_PATH."wenyunews/mulanjiang9.jpg' width=500>  ", "<IMG SRC='".$PHOTO_PATH."wenyunews/mulanjiang10.jpg' width=500>  ", "Elles ont gagné de nombreux prix aux Compétitions internationales de Mulan Quan 2013.",
"Félicitation au Professeur WANG et ses élèves pour leurs performances!", "", "")
);
?>