<?php
 $JL_NEWS11 = array(
"Exposition des peintures de Zhang Jianfeng",
"«Le rêve de Chine, le rêve du Monde»",
" ",
"15 avril 2014",
array(
),
array("<IMG src='".$PHOTO_PATH."expo/zhang_invitation.jpg' width=500>", "Exposition des peintures de Zhang Jianfeng «Le rêve de Chine, le rêve du Monde» du 16 avril au 17 avril 2014", "ZHANG Jianfeng, célèbre peintre chinois, représente la troisième génération d’élèves du peintre Maître QI Baishi. Ses œuvres réalisées dans la plus grande concision ont beaucoup de charme ses représentations de paysages et d’animaux tels que des poissons, des coqs, évoquent la richesse et le bonheur.  ", "Venez vite admirer son talent et ses œuvres exceptionnelles!", "", "")
);

$JL_NEWS11_s = array(
"Exposition des peintures de Zhang Jianfeng", 
array("expo/zhang600x400.jpg", "Exposition des peintures de Zhang Jianfeng"),  
array(
"Exposition des peintures de Zhang Jianfeng «Le rêve de Chine, le rêve du Monde» du 16 avril au 17 avril 2014", 
"ZHANG Jianfeng, célèbre peintre chinois, représente la troisième génération d’élèves du peintre Maître QI Baishi. Ses œuvres réalisées dans la plus grande concision ont beaucoup de charme ses représentations de paysages et d’animaux tels que des poissons, des coqs, évoquent la richesse et le bonheur. ", 
"Venez vite admirer son talent et ses œuvres exceptionnelles!",
),
$JL_NEWS11_sp
);	

?>