<?php
 $JL_NEWS9 = array(
"«Shanghai dans mon cœur» – exposition de peintures",
" ",
"",
"20 mars 2014",
array(
),
array(
"«Shanghai dans mon cœur» – exposition de peintures à l’encre de Chine réalisées par les artistes réputés de Shanghai",
"<IMG src='".$PHOTO_PATH."jiaoliunews/vernissage600-480.jpg' width=500>", 
"<IMG src='".$PHOTO_PATH."jiaoliunews/exposhanghai.jpg' width=500>", 
"Une exposition de peintures à l’encre de Chine sur le thème «Shanghai dans mon cœur» a lieu au site de l’Association des Amis de Nouvelles d’Europe à Gentilly. Cette exposition est organisée par le bureau de la presse et de l’édition de Shanghai, dans le but de célébrer le 50ème anniversaire de l’établissement des relations diplomatiques sino-françaises, et répondant ainsi à l’honneur fait à Shanghai d’être invité comme la ville d’honneur de la 34ème édition du Salon du Livre.  ", 
"52 œuvres de qualité réalisées par 43 artistes différents qui représentent le plus haut niveau de peinture à l’encre de Chine de Shanghai. Tous les amis qui sont intéressés par la culture chinoise, particulièrement la peinture, sont conviés à venir à l’exposition. ", 
"")
);

$JL_NEWS9_s = array(
"«Shanghai dans mon cœur»",
array("jiaoliunews/vernissage600-480.jpg", "«Shanghai dans mon cœur»"),
array(
"«Shanghai dans mon cœur» – exposition de peintures à l’encre de Chine réalisées par les artistes réputés de Shanghai",
"Une exposition de peintures à l’encre de Chine sur le thème «Shanghai dans mon cœur» a lieu au site de l’Association des Amis de Nouvelles d’Europe à Gentilly. Cette exposition est organisée par le bureau de la presse et de l’édition de Shanghai, dans le but de célébrer le 50ème anniversaire de l’établissement des relations diplomatiques sino-françaises, et répondant ainsi à l’honneur fait à Shanghai d’être invité comme la ville d’honneur de la 34ème édition du Salon du Livre.  ", 
"52 œuvres de qualité réalisées par 43 artistes différents qui représentent le plus haut niveau de peinture à l’encre de Chine de Shanghai. Tous les amis qui sont intéressés par la culture chinoise, particulièrement la peinture, sont conviés à venir à l’exposition. ", 
""),
$JL_NEWS9_sp
);

?>