<?php
 $JL_NEWS13 = array(
"Culture chinoise • Conférence d’Experts",
"La conférence comportera deux thèmes: «Dynastie Yongzheng» et l’éducation familiale de Zeng Guofan",
"",
"17 mai 2014",
array(
),
array(
"<IMG SRC='".$PHOTO_PATH."jiaoliunews/jiangtan600x450.jpg' width=500>", 
"La conférence comportera deux thèmes :", 
" — un thème sur la «Dynastie Yongzheng», célèbre série télévisée de l’année 1998, animée par le Directeur de la série M. ZHENG Jiaming", 
" — un thème sur l’éducation familiale de ZENG Guofan, par le Professeur TANG Haoming. ", 
"Conférence en Chinois",
"<b>Conférencier : </b>M. ZHENG Jiaming et M. TANG Haoming",
"<b>Date : </b>Mardi 27 mai 2014  14h-17h",
"<b>Lieu : </b>Centre Culturel de Nouvelles d’Europe: 48-50，Rue Benoît Malon, 94250 Gentilly",

"<div class=note_title><h1>Venez nombreux !</h1></div>", "", "", "")
);

$JL_NEWS13_s = array(
"Culture chinoise • Conférence d’Experts",
array("jiaoliunews/jiangtan600x450.jpg", "Culture chinoise • Conférence d’Experts"),
array(
"La conférence comportera deux thèmes :", 
" — un thème sur la «Dynastie Yongzheng», célèbre série télévisée de l’année 1998, animée par le Directeur de la série M. ZHENG Jiaming", 
" — un thème sur l’éducation familiale de ZENG Guofan, par le Professeur TANG Haoming. ", 
"<b>Conférencier : </b>M. ZHENG Jiaming et M. TANG Haoming",
"<b>Date : </b>Mardi 27 mai 2014  14h-17h",
"<b>Lieu : </b>Centre Culturel de Nouvelles d’Europe: 48-50，Rue Benoît Malon, 94250 Gentilly",
),
$JL_NEWS13_sp
);

?>