<?php 

$JL_NEWS6 =	array(
"Pendaison de crémaillère de l’Association des amis de Nouvelles d’Europe", 
" ", "","15 décembre 2013",
array(), 
array(
"<IMG src='".$PHOTO_PATH."meeting/openparty.jpg' width=500>",
"Après l’inauguration du nouveau Centre culturel dans la matinée du 15 décembre 2013, l’Association des Amis de Nouvelles d’Europe a organisé l’après-midi un cocktail d’ouverture pour pendre la crémaillère. ",
"<IMG src='".$PHOTO_PATH."meeting/party2.jpg' width=500>", 
"Le nouveau site se trouve dans un endroit culturel et historique de Gentilly. De nombreux voisins et les anciens amis de l’Association ont été chaleureusement invités à visiter le nouveau bâtiment. ",
"<IMG src='".$PHOTO_PATH."meeting/party.png' width=500>",
"En même temps qu’ils pouvaient déguster le champagne, les invités ont eu un aperçu général de toutes les activités culturelles grâce aux photos exposées. Ils ont porté des toasts pour souhaiter un bel avenir au nouveau Centre culturel."
),


);

$JL_NEWS6_s =	array(
"Pendaison de crémaillère de l’Association des amis de Nouvelles d’Europe", 
array("spectcocktail/cocktailtitre-600.jpg","Pendaison de crémaillère de l’Association des amis de Nouvelles d’Europe"), 
array(
"Après l’inauguration du nouveau Centre culturel dans la matinée du 15 décembre 2013, l’Association des Amis de Nouvelles d’Europe a organisé l’après-midi un cocktail d’ouverture pour pendre la crémaillère. ",
"Le nouveau site se trouve dans un endroit culturel et historique de Gentilly. De nombreux voisins et les anciens amis de l’Association ont été chaleureusement invités à visiter le nouveau bâtiment. ",
"En même temps qu’ils pouvaient déguster le champagne, les invités ont eu un aperçu général de toutes les activités culturelles grâce aux photos exposées. Ils ont porté des toasts pour souhaiter un bel avenir au nouveau Centre culturel."
),

array(	
	array("spectcocktail/cocktail1-200.jpg", "spectcocktail/cocktail1-800.jpg", " "), 
	array("spectcocktail/cocktail2-200.jpg", "spectcocktail/cocktail2-800.jpg", " "),   
	array("spectcocktail/cocktail3-200.jpg", "spectcocktail/cocktail3-800.jpg", " "), 
),			

);

?>