<?php
 $JL_NEWS20 = array(
"Les journées Portes Ouvertes",
" Nous organisons un événement « Les journées portes ouvertes »  ",
"",
"le 7 septembre 2014",
array(
),
array(	"<IMG src='".$PHOTO_PATH."jiaoliunews/jpo2.JPG' width=500>",
	"L’Association des Amis de Nouvelles d’Europe, créée en 1992,  depuis ces vingt années nous ont permis de nous développer sous la forme d’un Centre culturel qui comprend aujourd'hui des galeries d'exposition, de nombreuses classes et une bibliothèque devenue un véritable Centre d'activités. ",
	"",
	"Le Centre culturel de «Nouvelles d’Europe» organise diverses activités culturelles, telles que des expositions, des conférences, la danse, la chorale, la peinture chinoise et Kung-fu etc ; nous espérons que notre Association pourra ouvrir une fenêtre dans les échanges culturels franco-chinois et apporter une grande contribution à la promotion de la culture chinoise.",
	"",
	"Nous organisons un événement « Les journées portes ouvertes »  pour favoriser les rencontres entres nous et les visiteurs, et aussi pour échanger des informations avec plus de gens.",
	"",
	"Venez participer les cours de Yoga, de chinois, de la calligraphie & peinture chinoise; et venez à la conférence pour découvrir qu'est ce que le Qi Gong et pourquoi le pratiquer, venez danser ou visiter à l'exposition... Nous vous attendrons le week-end du 20 septembre. ",
	"",
	"Information importante à noter :",
	"",
	"Date：les 20 et 21 septembre 2014",
	"Programme: voir le tableau en-dessous",
	"<IMG src='".$PHOTO_PATH."jiaoliunews/jpo3.jpg' width=500>",
	"Horaire: 	10:00 - 17:30",
	"Lieu：48-50 Rue Benoît Malon，94250 Gentilly",
	""),
);
?>