<?php
 $JL_NEWS27 = array(
"Conférence(en français) : Qu'est-ce que le « Qi Gong » et pourquoi le pratiquer",
"Au delà d'un phénomène de mode actuel, le Qi Gong est un art de santé plusieurs fois millénaires.",
"",
"le 15 septembre 2014",
array(
),
array(	"<IMG src='".$PHOTO_PATH."wenyunews/conference qigong.jpg' width=500>",
	"Au delà d'un phénomène de mode actuel, le Qi Gong est un art de santé plusieurs fois millénaires. A travers la compréhension de son histoire, vous comprendrez les différentes influences qui ont fait évoluer le Qi Gong vers les formes modernes que nous pratiquerons cette année.",
	"Durant cette conférence nous aborderons également les concepts de base de cette discipline, les trois trésors (le Jing, le Qi et le Shen), les centres énergétiques du corps, Le Yin et le Yang ou la stimulation de la circulation énergétique dans les méridiens et les organes.",
	"Nous pratiquerons surtout quelques mouvements pour vous donnez un avant goût des exercices qui vous seront proposés dans les cours du jeudi.",
	"Bienvenue ！",
	"",
	"Conférence en français",
	"Date : 18 septembre 2014",
	"Horaire : 15h00 – 16h00",
	""),
);
?>