<?php
 $JL_NEWS12 = array(
"SU Manshu, un moine poète chinois",
"le premier traducteur du roman de Victor Hugo «Les Misérables»",
"",
"Le 14 mai 2014",
array(
	"jiaoliunews/sumanshu650.jpg", ""
),
array(
"SU Manshu, écrivain, peintre et journaliste, est le premier traducteur du roman de Victor Hugo «Les Misérables».",
"Le Professeur DONG Chun va montrer la véritable personnalité de SU Manshu.",
"<b>Date : </b>Mardi 18 mai 2014  16h30",
"<b>Lieu : </b>Centre Culturel de Nouvelles d’Europe: 48-50，Rue Benoît Malon, 94250 Gentilly",
"<div class=note_title><h1>Venez nombreux !</h1></div>",
)
);

$JL_NEWS12_s = array(
"SU Manshu, un moine poète chinois",
array(
	"jiaoliunews/sumanshu600x400.jpg", "SU Manshu, un moine poète chinois"
),
array(
"SU Manshu, écrivain, peintre et journaliste, est le premier traducteur du roman de Victor Hugo «Les Misérables».",
"Le Professeur DONG Chun va montrer la véritable personnalité de SU Manshu.",
"<b>Date : </b>Mardi 18 mai 2014  16h30",
"<b>Lieu : </b>Centre Culturel de Nouvelles d’Europe: 48-50，Rue Benoît Malon, 94250 Gentilly",

),
$JL_NEWS12_sp
);

?>