<?php
 $JL_NEWS26 = array(
"spectacle des chants et des danses des minorités chinoises",
"un spectacle des chants et des danses des minorités chinoises suivi d’un buffet",
"",
"Le 31 octobre 2014",
array(
),
array("<IMG src='".$PHOTO_PATH."jiaoyunews/chant-danse.jpg' width=500>", "A la commémoration du 50ème anniversaire des relations diplomatiques Franco-chinoises, un spectacle des chants et des danses des minorités chinoises suivi d’un buffet co-organisé par Studio central d’Actualités, de Documentaire de Chine et Association Amitié Euro-Chinoise aura lieu le lundi 10 novembre au Centre culturel de l'Association des Amis de Nouvelles d’Europe.", "", "Date : lundi 10 novembre 2014", "Horaire : de 15H00 à 20H ", "Lieu : Salle d’exposition au 1er étage", "Centre culturel de l'Association des Amis de Nouvelles d’Europe", "48-50 rue Benoît Malon, 94250 Gentilly   ", " ", "Veuillez envoyer la demande avant le 7 novembre 2014 à l’Association Amitié Euro-chinoise ", "Email :  contact@aaecf.com ou  aaecf@wanadoo.fr ", "Tel: 01 56 69 12 80 / 01 56 69 12 87 ", "Fax: 01 42 89 16 25", "", "Ne ratez pascette occasion en or. ", ""),
);
?>