<?php 

$JL_NEWS1 = 		array(
"La visite de M. MA Rupei, le directeur adjoint du bureau des affaires des Chinois d’outre-mer.",
" ",
"",	"10 février 2014",
			array(),	
array(
"Le 9 février au matin, un groupe d’investigation, dirigé par Monsieur MA Rupei, directeur adjoint du bureau des affaires des Chinois d’outre-mer, a visité le nouveau Centre culturel de Nouvelles d’Europe. ",
"<IMG SRC='".$PHOTO_PATH."top/topma2.jpg' width=500>",
"Monsieur MA Rupei et son groupe ont visité le bâtiment et regardé la présentation des activités proposées par l’Association des Amis de Nouvelles d’Europe. Monsieur MA Rupei a apprécié les nouvelles installations et il a souligné que le Centre culturel joue un rôle très important dans la promotion des échanges culturels chinois. ",


)
);


?> 
