<?php 

$JL_NEWS2 = array(
"Préparation du gala pour la nouvelle année du Cheval", 
" ",
"",	"6 janvier 2014",
array(),	
array(
"Le Nouvel An chinois s’approche à grands pas alors que l’ambiance de Noël n’est pas encore partie. ",
"La fête du printemps est la fête traditionnelle la plus importante pour tous les Chinois. L’Association des Amis de Nouvelles d’Europe organise régulièrement un gala pour la célébrer. Cette année, ce gala aura lieu dans les nouveaux locaux. Les habitants de Gentilly seront tous conviés chaleureusement à partager nos réjouissances. ",
"<IMG SRC='".$PHOTO_PATH."top/programmeweb.jpg' width=500>",
"Le gala inclura un spectacle (danses et kung-fu d’enfants, mulan, chants et danses chinoises), un buffet de spécialités chinoises et asiatiques, une exposition de photos et un bal. L’Association est prête pour fêter la nouvelle année avec les nouveaux voisins et les anciens amis."
)

);

?>