<?php
 $JL_NEWS21 = array(
"L'Art de Céramique & Thé",
"La conférence autour de &quot; Porcelaine et culture de Thé&quot; sera prensenté par l'expert, ",
"",
"le 12 septembre 2014",
array(
),
array("<IMG src='".$PHOTO_PATH."jiaoliunews/Porcelaine et Thé.jpg' width=500>", "La conférence autour de &quot; Porcelaine et culture de Thé&quot; sera prensenté par l'expert, et directeur général de Chunhuatai de Beijing. Une dégusation de thé sur place. Nous vous invitons pour partager ce moment culturel chinois. ", "", "Tarif : 5 euros", "", "<a href='https://docs.google.com/forms/d/1TYUzohoF8oITqhFWjjZd9T0wN_TIpnN3Gva3VRAwZFg/viewform'>L'inscription en ligne</a>", "", "", "Date: 17 septembre 2014 à 19H00", "", "Lieu: 48-50 Rue Benoît Malon，94250 Gentilly", "entre culturel de l’Association des Amis de Nouvelles d’Europe", "", "Bienvenue!", "", ""),
);
?>