<?php 

$JL_NEWS3 = array(
"Exposition de 10 années de photos sur le thème, «Une journée en Chine»", 
"  ",
"",	"215 décembre 2013",
array(),
array(
"Exposition de 10 années de photos sur le thème, «Une journée en Chine» (travaux réalisés par des photographes de la Chine continentale, de Taiwan, de Macao et de Hongkong)",
"<IMG src='".$PHOTO_PATH."expo/expo1.jpg' width=500>", 
"Le jour même de l’inauguration du Centre culturel de Nouvelles d’Europe, la première exposition dans la galerie a été ouvert au public.",
"<IMG src='".$PHOTO_PATH."expo/expo2.jpg' width=500>", 
"Depuis juin 2002, des photographes de la Chine continentale, de Taiwan, de Macao et de Hongkong ont commencé à travailler ensemble dans le but de collecter des images de la Chine. Le premier lieu choisi a été Taiwan, qui avait ouvert les échanges non gouvernementaux avec la Chine continentale à peine cinq ans auparavant. Les photographes ont saisi des Taïwanais dans leur vie quotidienne. Par la suite, une centaine de photographes se sont rendus dans plus d’une douzaine de provinces, dont Beijing, Guizhou, le Tibet, Shandong, Zhejiang, Shanghai, Macao, Jilin, Yunnan, Qingdao, Xinjiang…",
"<IMG src='".$PHOTO_PATH."expo/expo3.jpg' width=500>", 
"<IMG src='".$PHOTO_PATH."expo/expo4.jpg' width=500>", 
"À travers leurs objectifs, les photographes donnent à voir non seulement les paysages majestueux, la culture spectaculaire, mais aussi la vie quotidienne des gens ordinaires. ",
"<IMG src='".$PHOTO_PATH."expo/expo5.jpg' width=500>", 
)

);

?>