<?php 

$JL_NEWS4 = array(
"L’inauguration du Centre culturel de Nouvelles d’Europe sur le nouveau site", 	
" ",
"","16 décembre 2013",
array(), 
array(
"<IMG src='".$PHOTO_PATH."school/top_newschool.jpg' width=500>", 
"L’inauguration du Centre culturel de Nouvelles d’Europe sur le nouveau site à Gentilly a eu lieu le 15 décembre au matin. Monsieur HE Yafei (le directeur adjoint du bureau des affaires des Chinois d’outre-mer), Monsieur DENG Li (le délégué de l’ambassade chinoise), Madame TORDJMAN Patricia (la maire de Gentilly), et Monsieur ZHANG Xiaobei (le président de GUANG HUA MEDIA) ont dévoilé la plaque du Centre et en ont annoncé l’ouverture.",
"<IMG src='".$PHOTO_PATH."school/top_deng.jpg' width=500>", 
"<IMG src='".$PHOTO_PATH."school/top_zhang.jpg' width=500>", 
"<IMG src='".$PHOTO_PATH."school/top_maire.jpg' width=500>", 

),
);

?>