<?php
 $JL_NEWS8 = array(
"Le gala du Nouvel An chinois",
" ",
" ",
"le 20 février 2014",
array(
),
array(
"<IMG src='".$PHOTO_PATH."jiaoliunews/fete-dansedenfant600-480.jpg' width=500>", 
"Un gala organisé par l’Association des Amis de Nouvelles d’Europe a lieu le 16 février après midi au nouveau site à Gentilly pour fêter le Nouvel An chinois du Cheval. ", 
"<IMG src='".$PHOTO_PATH."jiaoliunews/fete-kungfu600-480.jpg' width=500>", 
"Chaque année, à l’occasion du Nouvel An chinois, l’Association des Amis de Nouvelles d’Europe et la Mutuelle Générale de l’Education Nationale (MGEN) organisent ensemble un gala. Cette année, plus de 300 personnes ont participé à cet événement. Madame Michèle COSNARD, la maire adjointe de Gentilly et Madame Xiaoyan CHEN, la vice-présidente de GUANG HUA MEDIA et des membres de la MGEN ont apprécié ensemble les activités proposées.", 
"<IMG src='".$PHOTO_PATH."jiaoliunews/fete-chorale600-480.jpg' width=500>",  
"En lever de rideau, le gala s’est ouvert sur une performance d’arts martiaux par les enfants, qui a rapidement mis de l’ambiance. Des chansons interprétées par la chorale ont succédé, suivies d’une danse chinoise “La lune sur l’étang de lotus”, puis du mulan avec des éventails. Enfin, la danse traditionnelle Yangge de la classe de chinois a fait monter l’ambiance et tout le monde a bougé, suivant son rythme entraînant. ", 
"<IMG src='".$PHOTO_PATH."jiaoliunews/fete-danse600-480.jpg' width=500>", 
"Les spectacles, l’exposition, le buffet et le bal ont été très appréciés par tous les participants, qui sont ainsi entrés avec joie dans l’année du Cheval. Bonne année à tous!  ", 
"<IMG src='".$PHOTO_PATH."jiaoliunews/fete-maire600-480.jpg' width=500>"
), 
);

$JL_NEWS8_s = array(
"Le gala du Nouvel An chinois",
array("jiaoliunews/fete600-480.jpg", "Le gala du Nouvel An chinois"),
array(
"Un gala organisé par l’Association des Amis de Nouvelles d’Europe a lieu le 16 février après midi au nouveau site à Gentilly pour fêter le Nouvel An chinois du Cheval. ", 
"Chaque année, à l’occasion du Nouvel An chinois, l’Association des Amis de Nouvelles d’Europe et la Mutuelle Générale de l’Education Nationale (MGEN) organisent ensemble un gala. Cette année, plus de 300 personnes ont participé à cet événement. Madame Michèle COSNARD, la maire adjointe de Gentilly et Madame Xiaoyan CHEN, la vice-présidente de GUANG HUA MEDIA et des membres de la MGEN ont apprécié ensemble les activités proposées.", 
"En lever de rideau, le gala s’est ouvert sur une performance d’arts martiaux par les enfants, qui a rapidement mis de l’ambiance. Des chansons interprétées par la chorale ont succédé, suivies d’une danse chinoise “La lune sur l’étang de lotus”, puis du mulan avec des éventails. Enfin, la danse traditionnelle Yangge de la classe de chinois a fait monter l’ambiance et tout le monde a bougé, suivant son rythme entraînant. ", 
"Les spectacles, l’exposition, le buffet et le bal ont été très appréciés par tous les participants, qui sont ainsi entrés avec joie dans l’année du Cheval. Bonne année à tous!  ", 
),
$JL_NEWS8_sp,

);

?>