<?php
 $JL_NEWS24 = array(
"Gala des jeunes talents artistiques chinois (Paris)",
"Un spectacle est organisé à Paris prochainement le dimanche 19 octobre 2014 ",
"",
"le 6 octobre 2014",
array(
),
array("<IMG src='".$PHOTO_PATH."jiaoliunews/dlyspectacle.jpg' width=500>", "Dans le cadre des échanges culturels entre la Chine et la France, un spectacle est organisé à Paris prochainement le dimanche 19 octobre 2014 au Palais des Congrès d'Issy (25 avenue Victor Cresson 92130 Issy les Moulineaux) Il y aura 2 séances: 15H ou 19H30.", "Son but est de contribuer au développement de l'intérêt pour la connaissance de la culture chinoise, ainsi qu'au dialogue entre les jeunes chinois et étrangers.  ", "Ce spectacle exceptionnel regroupe 19 jeunes talents de 7 ans à 21 ans qui vont faire une démonstration de leurs dons.", "", "", "Date : Dimanche 19 octobre 2014 à 15h00 et 19h30", "Lieu : Palais des Congrès d'Issy ", "25 avenue Victor Cresson 92130 Issy les Moulineaux", "", "", "", ""),
);

$JL_NEWS24_s = array(
"Gala des jeunes talents artistiques chinois (Paris)",
array("jiaoliunews/dlyspectacle.jpg",	 "Gala des jeunes talents artistiques chinois (Paris)",	 "JL_NEWS24_3_sp"),
array("Dans le cadre des échanges culturels entre la Chine et la France, un spectacle a eu lieu à Paris le dimanche 19 octobre 2014 au Palais des Congrès d'Issy (25 avenue Victor Cresson 92130 Issy les Moulineaux) à 15H et à 19H30.
", "Son but est de contribuer au développement de l'intérêt pour la connaissance de la culture chinoise, ainsi qu'au dialogue entre les jeunes chinois et étrangers.  
", "Ce spectacle exceptionnel regroupe 19 jeunes talents de 6 ans à 21 ans qui ont fait une démonstration de leurs dons.
", "Bravo ces jeunes talents !
", "
", "
", "
", ""),
$JL_NEWS24_3_sp
);


?>