<?php
 $JL_NEWS15 = array(
"Une Cérémonie Commémorative",
"Centre culturel de Nouvelles d’Europe va organiser une cérémonie commémorative",
"",
"31 mai 2014",
array(
),
array(
"<IMG src='".$PHOTO_PATH."wenyunews/plaque600.jpg' width=500>", 
"Le 1er juin 2014, pour le 70e anniversaire du Débarquement, le Centre culturel de Nouvelles d’Europe va organiser une cérémonie commémorative pour poser une plaque bilingue en français et en chinois à l’intérieur du Centre culturel en hommage aux martyrs de l’usine Sanders déportés en 1942. Le Centre culturel occupe aujourd’hui les locaux de l’ancienne usine Sanders, qui fabriquait des caisses enregistreuses sous licence américaine.",
"Cette cérémonie se fera en présence du maire, Mme Patricia Tordjman, de deux descendants des déportés et de représentant de l’Association Mémoire vive des convois des 45 000 et 31 000 d’Auschwitz-Birkenau. Des fleurs seront déposées en hommage par des élèves de l’Ecole chinoise de Nouvelles d’Europe.", 
"")
);
?>