<?php
 $JL_NEWS16 = array(
"Conférence sur l’identification et l’évaluation de l'art chinois",
"de plus en plus de Chinois d’outre-mer s’intéressent au \"Taobao\" (collection d’objets anciens)",
"",
"3 huin 2014",
array(
),
array("<IMG src='".$PHOTO_PATH."jiaoliunews/gxj600.jpg' width=500>", 
"Au cours des dernières années, de plus en plus de Chinois d’outre-mer s’intéressent au \"Taobao\" (collection d’objets anciens). Afin d'améliorer leur collecte, de les aider à identifier et à évaluer ces objets, M. GAN Xuejun, Président et PDG de Huachen Auction Co. à Beijing, donnera, en langue chinoise, une conférence interactive pour vous enseigner et expliquer le charme de la culture chinoise. À l’issue de la conférence, il sera possible de faire évaluer des objets.", 
"", "<div class=note_title><h1>La conférence est payante.</h1></div>", "<b>Conférencier ：</b>M. GAN Xuejun
", "<b>Date ：</b>Samedi 4 juin 2014,  15h-18h
", "<b>Lieu ：</b>Centre Culturel de Nouvelles d’Europe: 50 Rue Benoit Malon 94250 GENTILLY", "<b>Transport ：</b>RER B GENTILLY", "", "<div class=note_title><h1>Vente des billets au bureau commercial des Nouvelles d’Europe</h1></div>", "<b>Adresse：</b> 90-92 avenue de choisy, 75013 Paris", "<b>Information： </b> 01 53 82 78 94", "", "", "", "", "", "")
);

$JL_NEWS16_s = array(
"Identification et l’évaluation de l'art chinois",
array("jiaoliunews/gxj600.jpg", "Identification et l’évaluation de l'art chinois"),
array(
"Au cours des dernières années, de plus en plus de Chinois d’outre-mer s’intéressent au \"Taobao\" (collection d’objets anciens). Afin d'améliorer leur collecte, de les aider à identifier et à évaluer ces objets, M. GAN Xuejun, Président et PDG de Huachen Auction Co. à Beijing, donnera, en langue chinoise, une conférence interactive pour vous enseigner et expliquer le charme de la culture chinoise. À l’issue de la conférence, il sera possible de faire évaluer des objets.", 
"<b>Conférencier ：</b>M. GAN Xuejun", 
"<b>Date ：</b>Samedi 4 juin 2014  15h-18h", 
"<b>Lieu ：</b>Centre Culturel de Nouvelles d’Europe: 50 Rue Benoit Malon 94250 GENTILLY", 
""),
$JL_NEWS16_sp
);

?>