<?php
 $JL_NEWS10 = array(
"Exposition des photos (Paris) du Parc national de Wulong à Chongqing",
"Exposition du 16 avril au 18 avril 2014",
"",
"11 avril 2014",
array(
),
array(
"<IMG src='".$PHOTO_PATH."expo/wulong1-800.jpg' width=500>",
"Exposition du 16 avril au 18 avril 2014",
"<b>Ouverture : </b> 10:00 - 12:30;       13:30 - 17:30",
"La ville de Wulong est située au sud-est de Chongqing, dans le sud de la Chine. Elle est connue comme «Patrimoine naturel du monde» et attire plus en plus de touristes par son relief karstiqu« et ses paysages mystérieux.  ", 
"L'exposition donne une vue panoramique sur cette terre merveilleuse. ", 
"<IMG src='".$PHOTO_PATH."expo/wulong2-800.jpg' width=500>", 
"<IMG src='".$PHOTO_PATH."expo/wulong3-800.jpg' width=500>", 
"<div class=note_title><h1>Bienvenue à Wulong !</h1></div> ",

)
);

$JL_NEWS10_s = array(
"Parc national de Wulong à Chongqing", 
array("expo/wulong600-480.jpg", "Exposition des photos (Paris) du Parc national de Wulong à Chongqing"),  
array(
"La ville de Wulong est située au sud-est de Chongqing, dans le sud de la Chine. Elle est connue comme «Patrimoine naturel du monde» et attire plus en plus de touristes par son relief karstiqu« et ses paysages mystérieux.  ", 
"L'exposition donne une vue panoramique sur cette terre merveilleuse. ", 
),
$JL_NEWS10_sp,

);	

?>