<?php
 $JL_NEWS14 = array(
"La promotion du livre «La marche dans le Grand Paris», ",
"Table ronde pour la promotion du livre «La marche dans le Grand Paris», ",
"",
"17 mai 2014",
array(
),
array(
"Lors de la table ronde pour la promotion du livre «La marche dans le Grand Paris», et de la projection sur 9 années de randonnées, les deux auteurs Messieurs ZHANG Hanjun et ZHONG Min présenteront leur livre «La marche dans le Grand Paris». Dans ce livre, illustré en couleur avec beaucoup de belles photos, et aux textes élégants et amusants, les auteurs apporteront leurs expériences de randonnées culturelles et naturelles. ",
"<IMG SRC='".$PHOTO_PATH."jiaoliunews/rando600x450.jpg' width=500>", 
"<b>Date ： </b>Dimanche 25 mai 2014, 16h-18h", 
"<b>Lieu ： </b> Centre Culturel de Nouvelles d’Europe: 48-50 Rue Benoît Malon, 94250 Gentilly", 
"<div class=note_title><h1>Venez nombreux !</h1></div>", "", "", "", "")
);

$JL_NEWS14_s = array(
"«La marche dans le Grand Paris»",
array("jiaoliunews/rando600x450.jpg", "«La marche dans le Grand Paris»"), //images
array(
"Lors de la table ronde pour la promotion du livre «La marche dans le Grand Paris», et de la projection sur 9 années de randonnées, les deux auteurs Messieurs ZHANG Hanjun et ZHONG Min présenteront leur livre «La marche dans le Grand Paris». Dans ce livre, illustré en couleur avec beaucoup de belles photos, et aux textes élégants et amusants, les auteurs apporteront leurs expériences de randonnées culturelles et naturelles. ",
"<b>Date ： </b>Dimanche 25 mai 2014, 16h-18h", 
"<b>Lieu ： </b> Centre Culturel de Nouvelles d’Europe: 48-50 Rue Benoît Malon, 94250 Gentilly", 
""),
$JL_NEWS14_sp
);

?>