<?php 

$JL_NEWS5 = array(
"L’inauguration du symposium en média entre la Chine et l’UE", 	
" ",
"","15 décembre 2013",
array( ), 
array(
"<IMG SRC='".$PHOTO_PATH."meeting/meeting.jpg' width=500>",
"Le symposium en média entre la Chine et l’UE, organisé par l’Association des Médias chinois d’outre-mer en Europe, entrepris par GUANG HUA MEDIA, a été inauguré le 15 décembre 2013. Les directeurs et les chefs de rédactions des entreprises de presse en langue chinoise éditant en Europe (la France, la Grande-Bretagne, l’Allemagne, l’Espagne, le Portugal, la Hongrie…) se sont réunis au le Centre culturel de Nouvelles d’Europe et ils ont eu un dialogue chaleureux avec Monsieur HE Yafei, le directeur adjoint du bureau des affaires des Chinois d’outre-mer.",
"<IMG SRC='".$PHOTO_PATH."meeting/meeting2.jpg' width=500>",
"Monsieur HE Yafei et tous les participants ont étudié les moyens d’améliorer la presse en chinois à l’étranger après la troisième session plénière du 18ème comité central du Parti Communiste chinois.",
"<IMG SRC='".$PHOTO_PATH."meeting/meeting3.jpg' width=500>",
"En répondant aux questions posées par des historiens et des experts français en politique, Monsieur HE a donné ders précisions pertinentes sur la politique chinoise. ",
)
);

?>