<?php
 $JL_NEWS7 = array(
"Le présent et le passé du Tibet sous la caméra de Bouddha Vivant et son fils",
" ",
"",
"20 février 2014",
array(
),
array(
"<IMG src='".$PHOTO_PATH."jiaoliunews/expo600-480.jpg' width=500>", 
"L’exposition des photos ‘Le présent et le passé du Tibet sous la caméra de Bouddha Vivant et son fils’ est ouverte le 16 février après midi. ", 
"Toutes les photos exposées sont les travaux du premier photographe tibétain – Bouddha Vivant Demu X – et de son fils, le président de l’Association des Photographes Tibétains. Par leurs photos, ils ont raconté plus de 80 ans de l’histoire du Tibet du 20ème au 21ème siècle.",
"<IMG src='".$PHOTO_PATH."jiaoliunews/expo2.600-480.jpg' width=500>", 
"Conviée pour le gala du Nouvel An chinois, Mme Michèle COSNARD, maire adjointe de Gentilly, déclare que l’exposition de ces images précieuses ouvre, pour le visiteur, une fenêtre à la compréhension de la vie locale tibétaine. Cette exposition permet aux résidents de Gentilly de mieux connaître la Chine, et particulièrement le Tibet. ", 
"<IMG src='".$PHOTO_PATH."jiaoliunews/expo1.600-480.jpg' width=500>", 
"Les photos seront exposées jusqu’au 10 mars. Entrée libre.", 
"")
);
?>