<?php

$JL_NEWS24_3_sp = array(
	 array("jl_news24_sp/s_IMG_8514.JPG",	"jl_news24_sp/IMG_8514.JPG",	"",	""),
	 array("jl_news24_sp/s_IMG_8544.JPG",	"jl_news24_sp/IMG_8544.JPG",	"",	""),
	 array("jl_news24_sp/s_IMG_8474.JPG",	"jl_news24_sp/IMG_8474.JPG",	"",	""),
	 array("jl_news24_sp/s_IMG_8519.JPG",	"jl_news24_sp/IMG_8519.JPG",	"",	""),
	 array("jl_news24_sp/s_IMG_8534.JPG",	"jl_news24_sp/IMG_8534.JPG",	"",	""),
	 array("jl_news24_sp/s_IMG_8472.JPG",	"jl_news24_sp/IMG_8472.JPG",	"",	""),
	 array("jl_news24_sp/s_IMG_8410.JPG",	"jl_news24_sp/IMG_8410.JPG",	"",	""),
	 array("jl_news24_sp/s_IMG_8428.JPG",	"jl_news24_sp/IMG_8428.JPG",	"",	""),
	 array("jl_news24_sp/s_IMG_8424.JPG",	"jl_news24_sp/IMG_8428.JPG",	"",	""),
	 array("jl_news24_sp/s_IMG_8448.JPG",	"jl_news24_sp/IMG_8448.JPG",	"",	""),
	 array("jl_news24_sp/s_IMG_8444.JPG",	"jl_news24_sp/IMG_8444.JPG",	"",	""),
	 array("jl_news24_sp/s_IMG_8456.JPG",	"jl_news24_sp/IMG_8456.JPG",	"",	""),
	 array("jl_news24_sp/s_IMG_8592.JPG",	"jl_news24_sp/IMG_8592.JPG",	"",	""),
);
?>
