<?php

$JL_NEWS8_sp = array(
	 array("jiaoliunews/fete-dansedenfant600-480.jpg",	"jiaoliunews/fete-dansedenfant600-480.jpg",	"舞蹈", "Danse"),
	 array("jiaoliunews/fete-danse600-480.jpg",	"jiaoliunews/fete-danse600-480.jpg",	"舞蹈", "Danse"),
	 array("jiaoliunews/fete-chorale600-480.jpg",	"jiaoliunews/fete-chorale600-480.jpg",	"合唱", "Chorale"),
	 array("jiaoliunews/fete-kungfu600-480.jpg",	"jiaoliunews/fete-kungfu600-480.jpg",	"功夫", "Kongfu"),
);
?>