<?php

$jlpage_75_sp = array(
	 array("jlpage_75_sp/s_danse1.jpg",	"jlpage_75_sp/danse1.jpg",	"",	""),
	 array("jlpage_75_sp/s_danse2.jpg",	"jlpage_75_sp/danse2.jpg",	"双人舞",	"danse à deux"),
	 array("jlpage_75_sp/s_yoga.jpg",	"jlpage_75_sp/yoga.jpg",	"瑜伽展示",	"yoga"),
	 array("jlpage_75_sp/s_mulan.jpg",	"jlpage_75_sp/mulan.jpg",	"木兰双剑",	""),
	 array("jlpage_75_sp/s_tous.jpg",	"jlpage_75_sp/tous.jpg",	"百年",	"Bon Nouvel An"),
);
?>
