<?php

include_once ($DOC_PATH."/jiaoliu/jiaoliupagephoto/jiaoliuphotos.inc");
include_once ($DOC_PATH."/jiaoliu/jiaoliupage/jiaoliupageinfos.inc");
include_once ("jiaoyunews/jiaoyulastnews.inc");
include_once ("jiaoliunews/jiaoliulastnews.inc");
include_once ("wenyunews/wenyulastnews.inc");
include_once ($DOC_PATH."/public/lastnews/huigunews/huigulists.inc");
include_once ("huajianews/huajialastnews.inc");
include_once ("diversnews/divernews.inc");

?>