<?php
$HGNEWS1 = array(
	"Gala de la Fête du Printemps en ligne de l’Institut Confucius 2013", 
	array("oushi/huigu.jpg", "Gala de la Fête du Printemps 2013", "youtube"),
	array(

"Le Gala de Printemps en ligne des Instituts Confucius 2013 est le deuxième évènement de ce type organisé par 
Hanban/Siège de l’Institut Confucius. Plus de 500 vidéos des 112 Instituts/Classes Confucius de 46 pays ont été collectées. 
Parmi elles, \"Danse de Papillon\" et \"Petit Dragon\" de notre Classe Confucius ont gagné le Prix de la Meilleure Interprétation. 
Nous avons également obtenu le Prix de l'Organisation."
	),

array(	
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：儿歌《新年好》", "《Nouvel An》", "", "zuZgU-T9sA4", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：儿歌《两只老虎》 ", "《两只老虎》", "", "pgFTIs6gO-g", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：儿歌《我爱我的家》 ", "《我爱我的家》", "", "sGZJGi_DxYo", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：儿歌《咏鹅》 ", "《咏鹅》", "", "Gs6ry2Vlxtg", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：儿歌《春晓》 ",  "《春晓》", "", "Y-SfyLBoeGA", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：武术《长穗剑》 ", "《长穗剑》", "",  "A9nSHTIPAAM", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：武术《单扇》 ", "《单扇》", "", "j07OL9WXhBA", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：武术《木兰剑》 ", "《木兰剑》", "", "irJgKY-J-Ik", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：舞蹈《蝶舞》", "《蝶舞》", "", "TD6BVq_ZLC0", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：舞蹈《水果歌》 ", "《水果歌》", "", "jtdP2pjlpjk", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：舞蹈《在树上唱歌》 ", "《在树上唱歌》", "", "i-rMvoQQLn8", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：舞蹈《种太阳》 ", "《种太阳》", "", "UY_AWqcnv68", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：舞蹈《木兰辞》", "《木兰辞》", "", "2y36N72ZMbc", ""),
	array("2013孔子学院网络春晚——欧洲时报孔子课堂：舞蹈《小龙人》 ", "《小龙人》", "", "JKoRaq6RxxI", ""),
)
);

?>
