<?php

$WY_BIBLIO = array(
	"图书馆",
array("school/biblio-600.jpg",	 "图书馆",	 "图书馆",	 "WY_BIBLIO"),
array("欧洲时报文化中心图书馆成立于1996年，拥有近万册中文藏书，2000余套影像资料。图书类别多样，涉及中、外小说、散文、杂记、传记、历史和哲学、社科和经管、旅游和休闲、养生等等，可满足各年龄多层次需求。除了每两、三个月添加国内新出版发行的电视和电影DVD外，最近几年加入了不少国内极有影响的纪录片和专题讲座片，深受大家欢迎。", "", "", "", "", ""),
array(
	array("开放时间 ", "",
		array("星期六", "12h00—12h30", "15h00—16h00"),
		array("星期日", "12h00—12h30", "15h00—16h00"),
	),
),
// francais 
array(
	"Bibliothèque",
array("school/biblio-600.jpg",	 "Bibliothèque",	 "Bibliothèque",	 "WY_BIBLIO"),
array("La bibliothèque du centre culturel de «Nouvelles d’Europe» a été fondée en 1996. Vous pourrez y trouver environ 10 000 livres en chinois : des romans chinois et étrangers, des essais, des recueils, des biographies, et puis des ouvrages sur l'histoire, la philosophie, les sciences sociales, l’administration, les voyages, les loisirs ou la santé, afin de satisfaire les goûts du plus large public.", "De plus, tous les deux ou trois mois, de nouvelles séries de la télévision et des films nationaux en DVD viendront compléter la collection de vidéodisques qui en comporte déjà plus de 2 000, dont un grand nombre de documentaires et d’importantes conférences.", "", "", ""),
array(
	array("Horaires", "",
		array("Samedi", "12H00—12H30", "15H00—16H00"),
		array("Dimanche", "12H00—12H30", "15H00—16H00"),
	),
),
),
1 // new version with franch
);
?>