<?php

$WY_COMPUTE = array(
	"电脑培训",
array("school/infodebutant.jpg",	 "电脑培训",	 "电脑初级班",	 "WY_COMPUTE"),
array("<h3>电脑初级班</h3>", "电脑已经成为现代人生活工作中必不可少的一部分。中老年学电脑，更是生活在当下的需要。", "欧洲时报文化中心开设的电脑初级班适合零基础或者基础不太牢固的学员，为每位学员都配备了一台电脑，从电脑的基础输入开始，由浅入深，慢慢带你进入计算机的世界。课程设置注重实际应用，包括计算机鼠标键盘的介绍、如何上网、电子邮件的应用、数码相机与电脑数据的传输、软件的安装与下载、病毒的预防与查杀、网上看电影等等基础的电脑应用。", "为了帮助没有系统学过中文简体拼音但是说中文的学员，电脑初级班还专门设置了汉语拼音的授课内容，通过学习，学员们可以更加自如地完成计算机汉字的输入，更好地为电脑学习服务。", ""),
array(
	array("上课时间 ", "",
		array("星期日", "10H30—11H30（拼音）", "11H30—13H00（电脑）"),
	),
	array("报名表", "registerref=diannaochuji"),
),
array(" ",
array("school/infoavance.jpg",	 "电脑高级班",	 "电脑高级班",	 ""),
array("<h3>电脑高级班</h3>", "电脑高级班适合有一定基础，并且希望能掌握更多电脑知识的学员。课程设置注重从实际应用出发，老师会根据大家的要求灵活安排。学员们通过一人一台电脑的实际操练，用10周的时间学会一些大家感兴趣、并且在实际生活中很实用的内容，例如谷歌地图的查询、facebook等社交网站的应用、办公软件office的应用、电子邮件的高级应用、电影音乐的下载、qq等聊天软件的应用、美图秀秀等图片处理软件的应用及博客微博等等。学员们也可以根据自己的兴趣及需要，向老师建议一些教学内容。", ""),
array(
	array("上课时间 ", "",
		array("星期日", "14H30—16H30"),
	),
	array("报名表", "registerref=diannaogaoji"),
),
),
array(" ",
array("school/e-commerce600-480.JPG",	 "网络销售速成班",	 "网络销售速成班",	 ""),
array("<h3>网络销售速成班</h3>", "法国现有1千7百万人通过网络消费，中国每年在网络上购物的人数已超过8千万 ！网络销售将给你创造全新的商业天地！", "为推动华人逐渐熟悉网络购物的新消费方式，帮助华商开展网络销售业务，欧洲时报文化中心开办了网络销售速成班。网络销售速成班要求学员必须具备初步的电脑操作技能，通过六周的集中培训，让学员了解网络市场，确定销售方向，学会建设销售网站和宣传。为了保证学员的操作实践，文化中心的电脑室为每位学员都配备了一台电脑。", ""),
array(
	array("上课时间 ", "",
		array("星期六", "14H30—16H30"),
	),
	array("报名表", "registerref=wangluoxiaoshou"),
),
),
// francais 
array(
	"Informatique",
array("school/infodebutant.jpg",	 "Informatique",	 "Formation d'informatidue débutant",	 "WY_COMPUTE"),
array("<h3>Formation d'informatidue dédutant</h3>", "Les ordinateurs ont désormais un rôle essentiel dans nos vies ou à notre travail, et cela concerne également les personnes âgées. ", "Une classe de premier niveau est proposée pour en apprendre l'utilisation aux débutants. Un ordinateur est mis à la disposition de chaque élève. L'enseignant vous emmènera pas à pas dans le monde de l'informatique. Les cours portent sur les applications pratiques, dont l'Internet, l'écriture et l’envoi des e-mails, l'installation et le téléchargement des logiciels et des outils anti-virus, la transmission des données numériques d'un appareil photo, etc. Apprendre à entrer des caractères chinois par Pinyin vous sera également proposé.", ""),
array(
	array("Horaires", "",
		array("Dimanche", "10H30—11H30(Pingyin)", "11H30—13H00"),
	),
	array("Inscription", "registerref=diannaochuji"),
),
array(" ",
array("school/infoavance.jpg",	 "Formation d'informatidue avancé",	 "Formation d'informatidue avancé",	 ""),
array("<h3>Formation d'informatidue (niveau 2)</h3>", "Durant 10 semaines, ceux qui ont une certaine base d'informatique pourront bénéficier d’un cours flexible selon les besoins de chacun : requêtes Google Maps, Facebook, QQ, création de blogs n’auront plus de secrets pour vous, de même que d’autres applications ou logiciels bureautiques, ainsi que des fonctions avancées de messagerie, de téléchargements de musique ou de films. Chaque élève aura un ordinateur à sa disposition.", ""),
array(
	array("Horaires", "",
		array("Dimanche", "14H30—16H30"),
	),
	array("Inscription", "registerref=diannaogaoji"),
),
),
array(" ",
array("school/e-commerce600-480.JPG",	 "Formation E-commerce",	 "Formation E-commerce",	 ""),
array("<h3>Formation d'E-commerce</h3>", "Près de 17 millions de Français, et plus de 80 millions de Chinois font leurs achats sur internet. En 6 semaines, le professeur  aidera les hommes d'affaires chinois en France, qui ont une certaine base en informatique, à organiser leurs ventes en ligne. Un ordinateur est affecté à chaque élève.", ""),
array(
	array("Horaires", "",
		array("Samedi", "15H30—17H30"),
	),
	array("Inscription", "registerref=wangluoxiaoshou"),
),
),
),
1 // new version with franch
);
?>