<?php

$WY_LANGUE = array(
	"语言学习",
array("school/adulte.jpg",	 "语言学习",	 "成人中文课",	 "WY_LANGUE"),
array("<h3>成人中文课</h3>
", "汉语学习在法国持续升温，除了青少年外，越来越多的成年人也投入到学习汉语的热潮中。成人汉语班即是针对希望学习汉语的成年人而开办的。成人汉语班使用《当代中文》作为主教材，《长城汉语》作为辅助教材，根据学生的汉语程度分为初级班和提高班。在教学过程中借助现代教学手段，注重教学内容的实用性，以练为主，使学生能学有所用。
", ""),
array(
	array("上课时间 ", "",
		array("星期六", "10H30-12H30(初级)", "13H30-15H30(中级)"),
		array("星期天", "10H30-12H30 (高级)"),
	),
	array("报名表", "registerref=adulte"),
),
array(" ",
	array("school/huiha.jpg",	 "汉法双语会话角",	 "汉法双语会话角",	 ""),
	array("<h3>汉法双语会话角</h3>		", "为了提高语言学习者的口语表达能力，欧洲时报孔子课堂定期举办双语角活动，为学习汉语或法语的有关人士提供了一个交流和练习的平台。每次活动的主题广泛取材于《汉语900句》、《汉语301句》以及《体验汉语》等教材。同时，双语角以中国文化为切入点，紧扣时事，并结合欧洲时报文化中心的相关展览或讲座，组织大家进行有目的的学习和研讨。		", ""),
	array(
		array("上课时间 ", "",
			array("星期五", "14H30 - 16H30"),
		),
	),
),
array(" ",
	array("school/coursfrancais-600.jpg",	 "成人法文课",	 "成人法文课",	 ""),
	array("<h3>成人法文课</h3>
		", "为了帮助旅法的华侨、华裔更好地融入法国社会，提高法语水平，加强交流能力，欧洲时报文化中心开办了成人法文班。
		", "成人法文班提倡纯语境的小班教学，每班不超过10人。教学内容紧密结合日常生活需要，注重听说能力的培养。任教老师曾在法国公立学校执教多年，具备教授外国人法语的教师资格证书，具有丰富的教学经验。报名后将由老师进行一对一的水平测试，提出分班建议。
		", ""),
	array(
		array("上课时间 ", "",
			array("星期四", "10H00—12H00 （中级班）"),
		),
		array("报名表", "registerref=francais"),
	),
),
// francais 
array(
	"Cours de Langues",
array("school/adulte.jpg",	 "Cours de langue",	 "Cours de chinois pour adultes",	 "WY_LANGUE"),
array("<h3>Cours de chinois pour adultes</h3>", "Pour répondre aux besoins des adultes, on a mis en place depuis quelques années des cours pour ceux qui souhaitent acquérir certaines connaissances sur la langue chinoise. Le manuel principal est 《Le chinois contemporain》,avec en complément 《Great Wall Chinese》, tous les deux édités par Hanban. Les élèves sont répartis dans deux classes selon leur niveau. Étant donné la faible disponibilité des élèves après les cours, on sélectionne les textes et on consacre plus de temps aux xercices en classe.", ""),
array(
	array("Horaires", "",
		array("Samedi", "10H30-12H30(débutant)", "13H30-15H30(intermédiaire)"),
		array("Dimance", "10H30-12H30(avancé)"),
	),
	array("Inscription", "registerref=adulte"),
),
array(" ",
	array("school/huiha.jpg",	 "Cours de conversation",	 "Cours de conversation",	 ""),
	array("<h3>Cours de conversation</h3>", "Le cours de conversation constitue une plateforme d’échanges où se rencontrent des Français et des Chinois pour faire des exercices oraux pendant une heure. Ceux qui apprennent le chinois et ceux qui apprennent le français échangent leurs idées dans la langue voulue sous la direction d’un enseignant qui choisit le thème, soit dans le manuel, soit autour d’une exposition ou d’une conférence du centre culturel.", "", "", "", "", ""),
	array(
		array("Horaires", "",
			array("Vendredi", "14H30 - 16H30"),
		),
	),
),

array(" ",
	array("school/coursfrancais-600.jpg",	 "Cours de français pour adultes",	 "Cours de français pour adultes",	 ""),
	array("<h3>Cours de français pour adultes</h3>
", "Le cours de langue française s’adresse à tous les niveaux. L’objectif est de pouvoir commencer à communiquer en français pour les débutants, puis d’acquérir une autonomie permettant de faire face à la plupart des situations de la vie courante. Puis les cours peuvent permettre de perfectionner la pratique et la compréhension du français. Ces cours sont basés sur les méthodes de communication, et supposent la participation active des élèves.
", "Le professeur de français, qui a reçu une formation à l’Alliance française de Paris, a longtemps été instituteur dans le 13è arrondissement de Paris, et il a déjà enseigné aux adultes dans diverses associations.
", "Après l’inscription, le professeur fait passer un test ndividuel pour trouver le cours correspondant au niveau de chacun.
", "
", ""),
	array(
		array("Horaires", "",
			array("Dimance", "10H00—12H00 （Avancé）"),
		),
		array("Inscription", "registerref=francais"),
	),
),
),
1 // new version with franch
);
?>