<?php
$WY_MULAN =	array("木兰拳",
		array("mulan.jpg","木兰拳", "木兰拳", "WY_MULAN"),  
		array(
		"木兰拳是融中国武术之刚健和现代健美操之柔和为一体的健身拳术。它将太极拳基本功、气功要领、武术技击基本功、体操基本功及舞台艺术造型有机地结合在一起，以中国民族传统养生理论为指导，强调对人体身心的全面锻炼和培养。木兰拳拳舞相融、动作舒展，具有动作美、姿态美、造型美、音乐悦耳等特点，形成似拳非拳、似舞非舞的独特风格。",
		"欧洲时报文化中心的木兰拳班教授徒手、单双扇、剑、圈等多项内容。在年过八旬的王贤琴老师的悉心指导下，木兰拳班的学员屡次在国际木兰拳比赛中荣获冠军。"
		),
		array(
			array("上课时间 ", " ",
				array("星期五", "14H30—16H00"),
			),
			array("报名表", "../register/?registerref=mulan")
		),
	array("Mulan",
		array("mulan.jpg","Mulan", "Mulan"),  
		array(
"Mulan Quan est une forme de gymnastique douce, mélange de Tai Chi et d’arts martiaux. Tout au long de l'année, on peut pratiquer les trois enchaînements réglementaires du Mulan Quan : l'enchaînement à mains nues, avec l'éventail ou avec l'épée.",
"Les élèves du Mulan ont gagné plusieurs premiers prix dans des compétitions internationales.",
"Professeur： Mme WANG Xian Qin"
		),
		array(
			array("Horaires", "", 
				array("Vendredi", "14H30—16H00"),
			),
			array("Inscription", "/french/register/?registerref=mulan")
		),
	),
		
		1		
		);

?>