<?php

$WY_QIGONG =	array("气功", 
		array("wenyunews/journeeqigong3.jpg", "气功", "气功", "WY_QIGONG"),  
		array(
		"气功是一种以呼吸的调整、身体活动的调整和意识的调整为手段，以强身健体、防病治病、健身延年、开发潜能为目的的一种身心锻炼方法。",
		"通过各种调整呼吸的方法加上自我按摩，特别用腹式呼吸所产生的“内脏按摩”作用，以调整和增强全身各个系统的生理功能，达到祛病延年的作用。中医认为气功运用得法，就能养精化气，练气化神。"
		),
		array(
			array("上课时间 ", " ", 
				array("星期四", "18:30 – 19:30", "19:30 – 20:30"),
			),
			array("报名表", "../register/?registerref=qigong")
		),
	array("Qigong", 
		array("wenyunews/journeeqigong3.jpg", "Qigong", "Qigong"),  
		array(
"Le Qi Gong est une discipline où s'harmonise le corps, la respiration et l'esprit pour une meilleure gestion de votre vitalité quotidienne.", 
"Dans ce cours, tout au long de l'année vous pratiquerez principalement un enchaînement traditionnel : « Les huit pièces de brocard » (Ba Duan Jin) tel que le transmettent les experts de «l'Association chinoise du Qi Gong pour la santé». ",
"Le &quot;Ba Duan Jin&quot; est un des plus anciens et des plus traditionnels enchaînements de Qi Gong. Il est pratiqué en Chine depuis des siècles.",
				),
		array(
			array("Horaires ", " ", 
				array("Jeudi", "18:30 – 19:30", "19:30 – 20:30"),
			),
			array("Inscription","/french/register/?registerref=qigong")
		),
	),
		1
		
		);

	
?>