<?php

$WY_SHUHUA = array(
	"书画/摄影",
array("school/shufa-600.jpg",	 "书画/摄影",	 "书画课",	 "WY_SHUHUA"),
array("<h3>书画课</h3>", "中国书法和绘画经过几千年的历史沉淀，已经成为中国的国粹。练习书画不仅能陶冶人的情操，培养高雅的业余爱好和文明的风度，还能给人以愉悦，激发人的感情，宁神健魄。教学中，教师注重因材施教，针对个人的水平和特色做个性化的辅导。", "执教老师：王小军（中国美术学院毕业）", ""),
array(
	array("上课时间 ", "",
		array("星期三", "14H00—15H30", "15H45—17H15"),
		array("星期六", "14H00—15H30", "15H45—17H15"),
		array("星期天", "10:30—12:30(马老师)"),
	),
	array("报名表", "registerref=shuhua"),
),
array(" ",
array("school/clubphoto.jpg",	 "摄影俱乐部",	 "摄影俱乐部",	 ""),
array("<h3>摄影俱乐部</h3>", "用镜头捕捉美，用镜头将瞬间定格为永恒。", "生活在法国的华人中有不少摄影爱好者，其中不乏资深高手。出于共同的爱好，大家聚集在一起成立了摄影俱乐部。俱乐部不定期地组织外拍和摄影交流活动，时机成熟的时候也举办过摄影作品展。大家通过互相观摩、切磋，既分享了自己在摄影过程中的收获，又博采众长，提高了自己的摄影水平。", ""),
array(
	array("", "",
	),
),
),
// francais 
array(
	"Cours de calligraphie et de peinture chinoise",
array("school/shufa-600.jpg",	 "Calligraphie et peinture",	 "Calligraphie et peinture",	 "WY_SHUHUA"),
array("<h3>Calligraphie et Peinture chinoise</h3>", "La calligraphie et la peinture chinoises ont une histoire commune vieille de milliers d'années, et représentent la quintessence profonde de la Chine. Pratiquer l’art de la calligraphie c’est non seulement se cultiver, mais c’est aussi le plaisir d'acquérir de l'élégance et la paix de l’âme. L'enseignement est très personnalisé. ", "Professeur: WANG Xiaojun (Diplômé de l’Ecole des Beaux-Arts de Chine)", ""),
array(
	array("Horaires", "",
		array("Mercredi", "14H00—15H30", "15H45—17H15"),
		array("Samedi", "14H00—15H30", "15H45—17H15"),
		array("Dimance", "10H30—12H30(Prof. Ma)"),
	),
	array("Inscription", "registerref=shuhua"),
),
array(" ",
array("school/clubphoto.jpg",	 "Club photographie",	 "Club photographie",	 ""),
array("<h3>Club de photographie</h3>", "Un appareil photo pour capturer instantanément la beauté et la garder éternellement ! Il y a de nombreux Chinois amateurs de photographie en France, dont beaucoup sont des artistes reconnus qui ont créé ce club ensemble. Le club organise occasionnellement des sorties en plein air dans le but d'échanger les expériences de chacun. Des expositions sont également organisées pour partager les œuvres de ses membres.", ""),
array(
	array("", "",
	),
),
),
),
1 // new version with franch
);
?>