<?php
$WY_SINGING =	array("声乐", 
		array("school/music-600.jpg", "声乐", "合唱", "WY_SINGING"),  
		array("<h3>合唱</h3>",
		"欧洲时报丝绸之路合唱团成员多为旅居海外多年的东南亚华侨，因为对音乐的热爱，更因为对祖（籍）国的深厚感情，他们聚集在一起，以歌传情，以歌会友。",
		"长年以来，合唱团成员坚持每周在欧洲时报文化排练一次，接受老师的指导，提高演唱技巧。合唱团还不定期地举行歌唱会，成员们纷纷登台一展歌艺，更是为了互相观摩，共同提高。欧洲时报丝绸之路合唱团多次参加各种规模的演出，早已成为了活跃在法国侨界一道独特的风景线。",
		"指导老师 ： 赵柏（音乐博士在读）"
		),
		array(
			array("活动时间 ", " ", 
				array("星期日", "14H00—18H00"),
			),
			array("报名表", "../register/?registerref=hechangtuan")
		),
	array("Chant", 
		array("school/music-600.jpg", "Chant", "Chant"),  
		array("<h3>Chorale</h3>",
"Beaucoup d'entre eux sont venus de l’Asie du Sud-Est, et ils sont en France depuis de nombreuses années. Grâce à leur passion de la musique et leur sentiment profond pour le pays natal, ils se réunissent chaque dimanche. Ils participent à de nombreux spectacles et sont devenus des représentants de la communauté chinoise à Paris.  ",
"Professeur : ZHAO Bai "
		),
		array(
			array("Horaires", "", 
				array("Dimanche", "14H00—18H00"),
			),
			array("Inscription", "/french/register/?registerref=hechangtuan")
		),
	),
		1
		
		);

?>