<?php


$WY_TUBU =	array("徒步健身俱乐部", 
		array("wh_01.260-0.jpg", "徒步健身俱乐部",  "徒步健身俱乐部","WY_TUBU"),  
		array(
		"世界卫生组织明确指出：“最好的运动就是走步”。",
		"没有适量的运动，许多疾病就会莫名其妙地来到身上。虽然现在社会上有很多林林种种的健身方式与方法，但要么学起来复杂，需要场地、器材和大块的时间，要么就算容易也难以坚持下去。而走路是人们天生就会的。欧洲时报文化中心的徒步俱乐部每月组织一次徒步活动，不光带领大家将走进行下去，更是在走的同时欣赏湖光山色，体会风土人情，感受历史烙印，触摸文化脉搏。"
		),
		array(
			array("最新活动",""),
			array("4月12日索公园共赏樱花", "../wenyi/?action=detail&hindex=1"),
			array("3月30日卢万运河及森林徒步行 ", "../wenyi/?action=detail&hindex=2"),
			),

	array("Club de Randonnée", 
		array("wh_01.260-0.jpg", "Club de Randonnée",  "Club de Randonnée"),  
		array(
"L’OMS (Organisation Mondiale de la Santé) préconise la marche comme activité sportive.",
"Le club de randonnée organise chaque mois, soit une découverte de la nature, soit une promenade culturelle. On peut ainsi profiter à la fois des bienfaits des forêts ou des lacs, tout en découvrant l’histoire, et les histoires des lieux visités.",
		),
	),	
			
		1	
			
			);

?>