<?php
$WY_WUDAO =	array("舞蹈", 
		array("school/xingti-600.jpg", "舞蹈", "民族民间舞", "WY_WUDAO"),  
		array(
		"<h3>民族民间舞</h3>",
		"现代女性对自身有着越来越高的要求，一个好的体态，一个好的气质更添加了自信的筹码。形体塑身班在指导学员学习民族舞蹈的同时，揉合形体训练，力求塑造身形、改善线条，并提升身体的协调性、控制力及肌肉的延展性。课程由浅入深，通过练习舞蹈表演的过程使自己变得更加轻盈美丽，从而提高艺术气质和获得更健康的身心。"
		),
		array(
			array("上课时间 ", " ", 
				array("星期三", "15H00—17H00"),
			),
			array("报名表", "../register/?registerref=xingti")
		),
		array("", 
			array("school/dance1.jpg", "集体健身舞", "集体健身舞"),  
array("<h3>集体健身舞</h3>
", "健身舞原型为美国西部牛仔舞，在不断丰富与演变的同时，揉入了国际标准舞的一些舞步，拓宽了表现形式。
", "欧洲时报文化中心的健身舞班一方面注重与音乐相结合的舞蹈练习，另一方面发挥舞蹈做为一种运动锻炼形式的功能，让学员们在舞蹈中达到强身健体的目的。在健身排排舞的基础上，老师也会教授一些基础社交舞，以丰富教学内容。
", "任教老师 ： 薜学慧、巫干文
", "
", "
", "
", "
", ""),
						array(
				array("上课时间 ", " ", 
					array("星期四", "14H30—17H30"),
				),
				array("报名表", "../register/?registerref=jianshenwu")
			),
		),	
		array("", 
			array("school/guanchangwu.jpg", "广场舞", "广场舞"),  
			array(
			"<h3>广场舞</h3>",
			"",
			"",
			"",
			),
			array(
				$T_GCW,
				array("报名表", "../register/?registerref=guanchangwu")
			),
		),	
		array("", 
			array("school/dance-600.jpg", "交谊舞", "交谊舞"),  
array("<h3>交谊舞</h3>
", "交谊舞最早起源于欧洲，在古老民间舞蹈的基础上发展演变而成。它在保持国际标准舞的各种舞种风格的同时，相对降低了一些对舞者的要求，比较随性。
", "交谊舞课程设置不仅包括传统的摩登舞和拉丁舞，还会涉及一些新生舞种。学员在学习舞步的同时，培养优美的舞姿，体会舞蹈带给自身的愉悦！ 
", ""),
			array(
				array("上课时间 ", " ", 
					array("星期六", "15H45—17H15"),
				),
				array("报名表", "../register/?registerref=shalongwu")
			),
		),
		array("Danses", 
		array("school/xingti-600.jpg", "Danses chinoises", "Danses chinoises"),   
		array(
"Les femmes modernes font attention à leur corps et à leur élégance. Le fitness et la danse chinoise les aideront à améliorer leur ligne.",
		"Professeur： Mlle LU Dong"
		),
		array(
			array("Horaires", "",  
				array("Mercredi", "15H00-17H00"),
			),
			array("Inscription", "/french/register/?registerref=xingti")
		),
		array("", 
			array("school/dance1.jpg", "Danse sociale", "Danse sociale"),  
			array(
			"<h3>Danse en ligne et sociale</h3>",
"Cette danse américaine permet d’évoluer avec des pas de danse de salon, sous forme de danse en ligne. Cette danse collective et sociale est non seulement bonne pour mise en forme, mais crée aussi une ambiance très chaleureuse.  ",
"Professeurs : Mme WU Xue Xuehui et M. Wu Ganwen"
			),
			array(
				array("Horaires", "", 
					array("Jeudi", "14H30—16H00", "16H00-17H30"),
				),
				array("Inscription", "/french/register/?registerref=jianshenwu")
			),
		),	
		
		array("", 
			array("school/guanchangwu.jpg", "Danse en ligne", "Danse en ligne"),  
			array(
			"<h3>Danse en ligne</h3>",
			" "
			),
			array(
				$T_GCWF,
				array("Inscription", "/french/register/?registerref=jianshenwu")
			),
		),	
		array("", 
			array("school/dance-600.jpg", "Danse de salon et Country", "Danse de salon et Country"),  
			array(
				"<h3>Danse de salon et Country</h3>",
				"Le cours combine non seulement la danse de bal, les danses latines, mais aussi les nouvelles danses. Un cours spécial pour les débutants vous apprendra les bases en country. Tous les cours sont expliqués lentement afin que les élèves puissent progresser.",
				"Professeurs : M. Lim Kim et Mme Lim"
			),
			array(
				array("Horaires", "", 
					array("Jeudi", "15H45—17H15")
				),
				array("Inscription", "/french/register/?registerref=shalongwu")
			),
		),
	),	
	1
	
	);

?>