<?php
$WY_XINGTI =	
array("形体塑身", 
		array("school/xingti-600.jpg", "民族民间舞", "民族民间舞", "WY_XINGTI"),  
		array(
		"现代女性对自身有着越来越高的要求，一个好的体态，一个好的气质更添加了自信的筹码。形体塑身班在指导学员学习民族舞蹈的同时，揉合形体训练，力求塑造身形、改善线条，并提升身体的协调性、控制力及肌肉的延展性。课程由浅入深，通过练习舞蹈表演的过程使自己变得更加轻盈美丽，从而提高艺术气质和获得更健康的身心。"
		),
		array(
			array("上课时间 ", " ", 
				array("星期三", "14H45—16H45"),
				array("星期日", "10H30—12H30"),
			),
			array("报名表", "../register/?registerref=xingti")
		),
			array("Fitness et danses chinoises", 
		array("school/xingti-600.jpg", "Fitness et danses chinoises", "Fitness et danses chinoises"),  
		array(
"Les femmes modernes font attention à leur corps et à leur élégance. Le fitness et la danse chinoise les aideront à améliorer leur ligne.",
		"Professeur： Mlle LU Dong"
		),
		array(
			array("Horaires", "",  
				array("Mercredi", "14H45-16H45"),
				array("Dimance", "10H30-12H30"),
			),
			array("Inscription", "/french/register/?registerref=xingti")
		),
	),	
		
		1		
		);	


?>