<?php

$WY_YOGA =	array("瑜伽", 
		array("school/yoga.jpg", "瑜伽", "瑜伽", "WY_YOGA"),  
		array(
"瑜伽是一门科学，也是一项安全有效的运动。它不但适合各种年龄层次的人练习，更是人们保持自己身体活动功能的养生之道。欧洲时报文化中心聘请了专业教师，耐心讲解，让学员掌握正确的练习方法并持之以恒的练习，将使其终身受益。",
"执教老师： 朱玉霞 （香港瑜伽教练学会中级瑜伽教练证书） ",
		),
		array(
			$T_YJ,
			array("报名表", "../register/?registerref=yujia")
		),
	array("Yoga", 
		array("school/yoga.jpg", "Yoga", "Yoga"),  
		array(
"Le yoga est à la fois une science et un sport efficace et sans danger, si l’on prend soin de suivre un échauffement avant de le pratiquer. Le professeur, certifié et qualifié, guidera les élèves dans la maîtrise des exercices.",
"Professeur: Mme Rebeyrolle (Certificat du YOGA Intermédiaire Instructeur de Hong Kong)"
		),
		array(
			$T_YJF,
			array("Inscription", "/french/register/?registerref=yujia")
		),
	),
		
		1		
		);



?>