<?php

$EXPO_sp = array(
	 array("salleexpo/int-800x600.jpg",	"salleexpo/int-800x600.jpg",	"一层展厅内侧", "Première Etage"),
	 array("salleexpo/ext-800x600.jpg",	"salleexpo/ext-800x600.jpg",	"展厅入口", "Entrée"),
	 array("salleexpo/mezzanine1-800x1000.jpg",	"salleexpo/mezzanine1-800x1000.jpg",	"廊桥", ""),
	 array("salleexpo/mezzanine3-800x1000.jpg",	"salleexpo/mezzanine3-800x1000.jpg",	"廊桥", ""),
	 array("salleexpo/mezzanine2-800x600.jpg",	"salleexpo/mezzanine2-800x600.jpg",	"廊桥", ""),
	 array("salleexpo/expo1-800x600.jpg",	"salleexpo/expo1-800x600.jpg",	"一层展厅效果", "Première Etage"),
	 array("salleexpo/expo2-800x600.jpg",	"salleexpo/expo2-800x600.jpg",	"一层展厅效果", "Première Etage"),
	 array("salleexpo/expo3-800x600.jpg",	"salleexpo/expo3-800x600.jpg",	"一层展厅效果", "Première Etage"),
	 array("salleexpo/expo4-800x600.jpg",	"salleexpo/expo4-800x600.jpg",	"一层展厅效果", "Première Etage"),
	 array("salleexpo/salleexpo4-800x600.jpg",	"salleexpo/salleexpo4-800x600.jpg",	"二层展厅", "Seconde Etage"),
	 array("salleexpo/salleexpo3-800x1000.jpg",	"salleexpo/salleexpo3-800x1000.jpg",	"一层展厅内侧", "Première Etage"),
	 array("salleexpo/salleexpo2-800x600.jpg",	"salleexpo/salleexpo2-800x600.jpg",	"一层展厅", "Première Etage"),
	 array("salleexpo/salleexpo1-800x600.jpg",	"salleexpo/salleexpo1-800x600.jpg",	"一层展厅", "Première Etage"),
	 array("salleexpo/railetprojecteur-800x600.jpg",	"salleexpo/railetprojecteur-800x600.jpg",	"挂槽和射灯",""),
);
?>
