<?php
include ("jl_news22_sp.inc");
include ("jl_news19_sp.inc");

include ("expo_sp.inc");
include ("jl_news_db_sp.inc");
include ("jl_news_ml_sp.inc");
include ("jl_news_sf_sp.inc");
include ("jl_news3_sp.inc");
include ("jl_news5_sp.inc");
include ("jl_news6_sp.inc");
include ("jl_news7_sp.inc");
include ("jl_news8_sp.inc");
include ("jl_news9_sp.inc");
include ("jl_news10_sp.inc");
include ("jl_news11_sp.inc");
include ("jl_news12_sp.inc");
include ("jl_news13_sp.inc");
include ("jl_news14_sp.inc");
include ("jl_news16_sp.inc");
include ("jl_news17_sp.inc");
include ("wy_news12_sp.inc");
?>

