<?php

$JL_NEWS_DB_sp = array(
	 array("confvoyage/voyage1-200.jpg",	"confvoyage/voyage1-800.jpg",	"中心发言人安娜•卡祖勃斯基女士（前排左1）",	""),
	 array("confvoyage/voyage2-200.jpg",	"confvoyage/voyage2-800.jpg",	"中心发言人乔尚炎先生（图左）",	""),
	 array("confvoyage/voyage3-200.jpg",	"confvoyage/voyage3-800.jpg",	"单游中国边陲研讨会现场 1",	""),
	 array("confvoyage/voyage4-200.jpg",	"confvoyage/voyage4-800.jpg",	"单游中国边陲研讨会现场 2",	""),
);
?>
