<?php

$JL_NEWS9_sp = array(
	 array("jl_news9_sp/s_IMG_4073.JPG",	"jl_news9_sp/IMG_4073.JPG",	"",	""),
	 array("jl_news9_sp/s_IMG_4082.JPG",	"jl_news9_sp/IMG_4082.JPG",	"",	""),
	 array("jl_news9_sp/s_IMG_4085.JPG",	"jl_news9_sp/IMG_4085.JPG",	"",	""),
	 array("jl_news9_sp/s_IMG_4097.JPG",	"jl_news9_sp/IMG_4097.JPG",	"",	""),
	 array("jl_news9_sp/s_IMG_4104.JPG",	"jl_news9_sp/IMG_4104.JPG",	"",	""),
);
?>
