<?php

$JL_NEWS3_sp = array(
	 array("expo24H/24H1-200.jpg",	"expo24H/24H1-800.jpg",	"合拍中国大地24小时十年回顾展  1"),
	 array("expo24H/24H2-200.jpg",	"expo24H/24H2-800.jpg",	"合拍中国大地24小时十年回顾展  2"),
	 array("expo24H/24H3-200.jpg",	"expo24H/24H3-800.jpg",	"合拍中国大地24小时十年回顾展  3"),
	 array("expo24H/24H4-200.jpg",	"expo24H/24H4-800.jpg",	"合拍中国大地24小时十年回顾展  4"),
	 array("expo24H/24H5-200.jpg",	"expo24H/24H5-800.jpg",	"合拍中国大地24小时十年回顾展  5"),
);
?>
