<?php

$JL_NEWS19_sp = array(
	 array("jl_news19_sp/s_IMG_8349.JPG",	"jl_news19_sp/IMG_8349.JPG",	"",	""),
	 array("jl_news19_sp/s_IMG_8350.JPG",	"jl_news19_sp/IMG_8350.JPG",	"",	""),
	 array("jl_news19_sp/s_IMG_8303.JPG",	"jl_news19_sp/IMG_8303.JPG",	"",	""),
	 array("jl_news19_sp/s_IMG_8304.JPG",	"jl_news19_sp/IMG_8304.JPG",	"",	""),
	 array("jl_news19_sp/s_IMG_8291.JPG",	"jl_news19_sp/IMG_8291.JPG",	"",	""),
	 array("jl_news19_sp/s_IMG_8298.JPG",	"jl_news19_sp/IMG_8298.JPG",	"",	""),
	 array("jl_news19_sp/s_IMG_8323.JPG",	"jl_news19_sp/IMG_8323.JPG",	"",	""),
	 array("jl_news19_sp/s_IMG_8339.JPG",	"jl_news19_sp/IMG_8339.JPG",	"",	""),
	 array("jl_news19_sp/s_IMG_8330.JPG",	"jl_news19_sp/IMG_8330.JPG",	"",	""),
);
?>
