<?php

$JL_NEWS_SF_sp = array(
	 array("caligraphie/photo1-200.jpg",	"caligraphie/photo-800.jpg",	"书画班师生与来宾合影"),
	 array("caligraphie/preface-200.jpg",	"caligraphie/preface-800.jpg",	"马剑虹老师为本次汇报展题写的前言"),
	 array("caligraphie/ma1-200.jpg",	"caligraphie/ma1-800.jpg",	"马剑虹老师作品 1"),
	 array("caligraphie/ma2-200.jpg",	"caligraphie/ma2-800.jpg",	"马剑虹老师作品 2"),
	 array("caligraphie/caligraphie1-200.jpg",	"caligraphie/caligraphie1-800.jpg",	"书画班学生书法作品 1"),
	 array("caligraphie/caligraphie2-200.jpg",	"caligraphie/caligraphie2-800.jpg",	"书画班学生书法作品 2"),
	 array("caligraphie/caligraphie3-200.jpg",	"caligraphie/caligraphie3-800.jpg",	"书画班学生书法作品 3"),
	 array("caligraphie/caligraphie4-200.jpg",	"caligraphie/caligraphie4-800.jpg",	"书画班学生书法作品 4"),
	 array("caligraphie/caligraphie5-200.jpg",	"caligraphie/caligraphie5-800.jpg",	"书画班学生书法作品 5"),
	 array("caligraphie/caligraphie6-200.jpg",	"caligraphie/caligraphie6-800.jpg",	"书画班学生书法作品 6"),
	 array("caligraphie/peinture1-200.jpg",	"caligraphie/peinture1-800.jpg",	"书画班学生国画作品 1"),
	 array("caligraphie/peinture2-200.jpg",	"caligraphie/peinture2-800.jpg",	"书画班学生国画作品 2"),
	 array("caligraphie/peinture3-200.jpg",	"caligraphie/peinture3-800.jpg",	"书画班学生国画作品 3"),
	 array("caligraphie/peinture4-200.jpg",	"caligraphie/peinture4-800.jpg",	"书画班学生国画作品 4"),
	 array("caligraphie/peinture5-200.jpg",	"caligraphie/peinture5-800.jpg",	"书画班学生国画作品 5"),
	 array("caligraphie/peinture6-200.jpg",	"caligraphie/peinture6-800.jpg",	"书画班学生国画作品 6"),
	 array("caligraphie/peinture7-200.jpg",	"caligraphie/peinture7-800.jpg",	"书画班学生国画作品 7"),
	 array("caligraphie/peinture8-200.jpg",	"caligraphie/peinture8-800.jpg",	"书画班学生国画作品 8"),
	 array("caligraphie/peinture9-200.jpg",	"caligraphie/peinture9-800.jpg",	"书画班学生国画作品 9"),
);
?>
